-- GREAT LAKE STATE KEEPERS — LEAGUE OFFICE FOUNDATION v1
-- Adds season-aware league management tables for contracts, rules, deadlines,
-- redistribution, finances and audit history. Safe to run on the existing GLSK26 database.
-- Does NOT reset or alter draft rooms, PINs, bids, sales, rosters, Supplemental or Phase 3 state.

begin;

create table if not exists public.league_seasons (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  season_year integer not null,
  status text not null default 'active' check(status in ('setup','active','complete','archived')),
  roster_limit integer not null default 18 check(roster_limit between 1 and 100),
  salary_cap_points integer not null default 100 check(salary_cap_points between 1 and 10000),
  is_current boolean not null default false,
  created_at timestamptz not null default now(),
  unique(room_id, season_year)
);
create unique index if not exists league_seasons_current_one
  on public.league_seasons(room_id) where is_current;

create table if not exists public.league_rule_settings (
  id bigint generated by default as identity primary key,
  season_id uuid not null references public.league_seasons(id) on delete cascade,
  rule_key text not null,
  category text not null,
  label text not null,
  numeric_value numeric,
  text_value text,
  boolean_value boolean,
  unit text,
  sort_order integer not null default 0,
  locked boolean not null default false,
  updated_at timestamptz not null default now(),
  unique(season_id, rule_key)
);

create table if not exists public.redistribution_rules (
  id bigint generated by default as identity primary key,
  season_id uuid not null references public.league_seasons(id) on delete cascade,
  bracket text not null check(bracket in ('championship','consolation')),
  finish integer not null check(finish between 1 and 6),
  label text not null,
  percentage numeric(7,3) not null check(percentage >= 0 and percentage <= 100),
  sort_order integer not null,
  updated_at timestamptz not null default now(),
  unique(season_id, bracket, finish)
);

create table if not exists public.contract_options (
  id bigint generated by default as identity primary key,
  season_id uuid not null references public.league_seasons(id) on delete cascade,
  years integer not null check(years between 1 and 10),
  cap_cost integer not null check(cap_cost >= 0),
  active boolean not null default true,
  unique(season_id, years)
);

create table if not exists public.league_contracts (
  id bigint generated by default as identity primary key,
  season_id uuid not null references public.league_seasons(id) on delete cascade,
  team_id uuid not null references public.teams(id),
  player_key text not null,
  player_name text not null,
  start_year integer not null,
  end_year integer not null,
  length_years integer not null check(length_years between 1 and 10),
  cap_cost integer not null check(cap_cost >= 0),
  status text not null default 'active' check(status in ('active','expired','released','traded','void')),
  source text not null default 'import',
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(season_id, player_key)
);
create index if not exists league_contracts_team_idx on public.league_contracts(season_id,team_id,status);

create table if not exists public.league_deadlines (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.league_seasons(id) on delete cascade,
  title text not null,
  deadline_type text not null default 'general',
  due_at timestamptz not null,
  auto_lock boolean not null default true,
  allow_commish_override boolean not null default true,
  status text not null default 'open' check(status in ('open','closed','completed','cancelled')),
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.league_deadline_team_status (
  deadline_id uuid not null references public.league_deadlines(id) on delete cascade,
  team_id uuid not null references public.teams(id) on delete cascade,
  status text not null default 'pending' check(status in ('pending','submitted','late','waived')),
  submitted_at timestamptz,
  updated_at timestamptz not null default now(),
  primary key(deadline_id, team_id)
);

-- Finance rows intentionally have NO public SELECT policy. Access is through PIN-validated RPCs below.
create table if not exists public.league_finance_items (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.league_seasons(id) on delete cascade,
  team_id uuid references public.teams(id),
  category text not null check(category in ('dues','prize','expense','adjustment','other')),
  description text not null,
  amount_cents integer not null,
  status text not null default 'due' check(status in ('due','paid','waived')),
  due_at date,
  paid_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);
create index if not exists league_finance_team_idx on public.league_finance_items(season_id,team_id,status);

create table if not exists public.league_audit_log (
  id bigint generated by default as identity primary key,
  season_id uuid not null references public.league_seasons(id) on delete cascade,
  actor_team_id uuid references public.teams(id),
  action text not null,
  entity_type text not null,
  entity_id text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now()
);

-- Current season.
insert into public.league_seasons(room_id,season_year,status,roster_limit,salary_cap_points,is_current)
select r.id,2026,'active',18,100,true
from public.rooms r where r.code='GLSK26'
on conflict(room_id,season_year) do update
set status='active', roster_limit=18, salary_cap_points=100, is_current=true;

-- Known configurable league rules. These are management values, not replacements for historical draft records.
with s as (
  select ls.id from public.league_seasons ls join public.rooms r on r.id=ls.room_id where r.code='GLSK26' and ls.season_year=2026
), vals(rule_key,category,label,numeric_value,text_value,boolean_value,unit,sort_order,locked) as (values
  ('roster_limit','Roster','Roster limit',18,null,null,'players',10,false),
  ('salary_cap_points','Contracts','Salary cap',100,null,null,'points',20,false),
  ('auction_pool_size','Auction','Auction player pool',40,null,null,'players',30,false),
  ('auction_qb_slots','Auction','QB slots in auction pool',3,null,null,'players',31,false),
  ('auction_te_slots','Auction','TE slots in auction pool',3,null,null,'players',32,false),
  ('auction_initial_clock','Auction','Initial auction clock',30,null,null,'seconds',33,false),
  ('auction_bid_reset','Auction','Clock after accepted bid',10,null,null,'seconds',34,false),
  ('supplemental_rounds','Supplemental','Supplemental rounds',2,null,null,'rounds',40,false),
  ('supplemental_pick_clock','Supplemental','Pick clock',45,null,null,'seconds',41,false),
  ('supplemental_challenge_clock','Supplemental','Challenge window',10,null,null,'seconds',42,false),
  ('supplemental_auction_clock','Supplemental','Auction clock',30,null,null,'seconds',43,false),
  ('supplemental_challenge_bid','Supplemental','Normal challenge opening bid',6,null,null,'bids',44,false),
  ('supplemental_rights_h2h_bid','Supplemental','Restricted-rights H2H opening bid',2,null,null,'bids',45,false),
  ('phase3_pick_clock','Phase 3','Roster-fill pick clock',30,null,null,'seconds',50,false),
  ('rookie_rights_draft_only','Rookie Rights','Only drafted rookies create rights',null,null,true,null,60,false),
  ('rookie_rights_drop_extinguishes','Rookie Rights','Dropping a rights player permanently ends rights',null,null,true,null,61,false),
  ('rookie_rights_trade_transfers','Rookie Rights','Rights transfer with player on trade',null,null,true,null,62,false),
  ('rookie_rights_waiver_none','Rookie Rights','Waiver-wire rookies receive no rights',null,null,true,null,63,false)
)
insert into public.league_rule_settings(season_id,rule_key,category,label,numeric_value,text_value,boolean_value,unit,sort_order,locked)
select s.id,v.* from s cross join vals v
on conflict(season_id,rule_key) do nothing;

-- Contract options from the constitution.
with s as (
  select ls.id from public.league_seasons ls join public.rooms r on r.id=ls.room_id where r.code='GLSK26' and ls.season_year=2026
)
insert into public.contract_options(season_id,years,cap_cost)
select s.id,x.years,x.cost from s cross join (values (2,15),(3,25),(4,45)) x(years,cost)
on conflict(season_id,years) do update set cap_cost=excluded.cap_cost,active=true;

-- 2026 imported redistribution snapshot. This is editable in League Office.
with s as (
  select ls.id from public.league_seasons ls join public.rooms r on r.id=ls.room_id where r.code='GLSK26' and ls.season_year=2026
), vals(bracket,finish,label,percentage,sort_order) as (values
 ('championship',1,'Champion',9.750,1),
 ('championship',2,'Runner-up',8.750,2),
 ('championship',3,'Championship 3rd',8.250,3),
 ('championship',4,'Championship 4th',8.250,4),
 ('championship',5,'Championship 5th',8.250,5),
 ('championship',6,'Championship 6th',8.250,6),
 ('consolation',1,'Consolation Winner',8.500,7),
 ('consolation',2,'Consolation 2nd',8.000,8),
 ('consolation',3,'Consolation 3rd',8.000,9),
 ('consolation',4,'Consolation 4th',8.000,10),
 ('consolation',5,'Consolation 5th',8.000,11),
 ('consolation',6,'Consolation 6th',8.000,12)
)
insert into public.redistribution_rules(season_id,bracket,finish,label,percentage,sort_order)
select s.id,v.* from s cross join vals v
on conflict(season_id,bracket,finish) do nothing;

-- Corrected 2026 contract import. The source workbook listed AJ Brown for Slim Charles;
-- per commissioner correction, Chase Brown is the contracted player and AJ Brown is a free agent.
with s as (
  select ls.id,ls.season_year from public.league_seasons ls join public.rooms r on r.id=ls.room_id where r.code='GLSK26' and ls.season_year=2026
), vals(team_name,player_name,length_years,start_year,end_year,cap_cost) as (values
 ('The Hebrew Hammer','Lamar Jackson',2,2025,2026,15),
 ('MEGATRONS V2','Josh Jacobs',2,2025,2026,15),
 ('MEGATRONS V2','Jonathan Taylor',2,2025,2026,15),
 ('MEGATRONS V2','Trey McBride',2,2025,2026,15),
 ('Suburban White Kid','Ja''Marr Chase',3,2025,2027,25),
 ('Suburban White Kid','TreVeyon Henderson',2,2025,2026,15),
 ('kerwinning it','Drake London',3,2025,2027,25),
 ('kerwinning it','Jayden Daniels',2,2025,2026,15),
 ('kerwinning it','Jameson Williams',2,2025,2026,15),
 ('7th Floor Crew','Brock Bowers',2,2025,2026,15),
 ('7th Floor Crew','George Kittle',2,2025,2026,15),
 ('hugs not drugs','Ashton Jeanty',2,2025,2026,15),
 ('hugs not drugs','Derrick Henry',2,2025,2026,15),
 ('hugs not drugs','Brian Thomas Jr',2,2025,2026,15),
 ('The Real McCoy','Bucky Irving',2,2025,2026,15),
 ('The Real McCoy','Malik Nabers',2,2025,2026,15),
 ('Weiss Tea & Lemonade','Tee Higgins',2,2025,2026,15),
 ('Weiss Tea & Lemonade','Courtland Sutton',2,2025,2026,15),
 ('Team Ramrod','Tetairoa McMillan',2,2025,2026,15),
 ('Klyde Frogs','Luther Burden III',2,2025,2026,15),
 ('Team Ramrod','Emeka Egbuka',2,2025,2026,15),
 ('Team Ramrod','Dont''e Thornton Jr.',2,2025,2026,15),
 ('Team Ramrod','Christian McCaffrey',2,2025,2026,15),
 ('Slim Charles','Jalen Hurts',2,2025,2026,15),
 ('Slim Charles','Ricky Pearsall',2,2025,2026,15),
 ('Slim Charles','Chase Brown',2,2025,2026,15),
 ('Slim Charles','Mike Evans',2,2025,2026,15),
 ('Klyde Frogs','Kenneth Walker III',2,2025,2026,15),
 ('Klyde Frogs','Marvin Harrison Jr.',2,2025,2026,15),
 ('MEGATRONS V2','Terry McLaurin',2,2025,2026,15),
 ('Reggie Kush','Ladd McConkey',2,2025,2026,15),
 ('Slim Charles','Jonathan Brooks',3,2024,2026,25),
 ('Reggie Kush','Justin Jefferson',3,2024,2026,25),
 ('Weiss Tea & Lemonade','Rashee Rice',3,2024,2026,25),
 ('Suburban White Kid','Chris Olave',3,2024,2026,25),
 ('The Real McCoy','CeeDee Lamb',3,2024,2026,25),
 ('The Real McCoy','Bijan Robinson',3,2024,2026,25),
 ('hugs not drugs','Amon-Ra St Brown',3,2024,2026,25)
)
insert into public.league_contracts(season_id,team_id,player_key,player_name,start_year,end_year,length_years,cap_cost,status,source)
select s.id,t.id,public._league_roster_key(v.player_name),v.player_name,v.start_year,v.end_year,v.length_years,v.cap_cost,'active','2026 workbook import + commissioner corrections'
from s cross join vals v
join public.teams t on t.room_id=(select room_id from public.league_seasons where id=s.id) and t.name=v.team_name
on conflict(season_id,player_key) do update
set team_id=excluded.team_id,player_name=excluded.player_name,start_year=excluded.start_year,end_year=excluded.end_year,
    length_years=excluded.length_years,cap_cost=excluded.cap_cost,status='active',source=excluded.source,updated_at=now();

-- RLS / read access for non-sensitive league data.
alter table public.league_seasons enable row level security;
alter table public.league_rule_settings enable row level security;
alter table public.redistribution_rules enable row level security;
alter table public.contract_options enable row level security;
alter table public.league_contracts enable row level security;
alter table public.league_deadlines enable row level security;
alter table public.league_deadline_team_status enable row level security;
alter table public.league_finance_items enable row level security;
alter table public.league_audit_log enable row level security;

do $$ begin
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='league_seasons' and policyname='public read league seasons') then
    create policy "public read league seasons" on public.league_seasons for select to anon,authenticated using(true);
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='league_rule_settings' and policyname='public read league rules') then
    create policy "public read league rules" on public.league_rule_settings for select to anon,authenticated using(true);
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='redistribution_rules' and policyname='public read redistribution') then
    create policy "public read redistribution" on public.redistribution_rules for select to anon,authenticated using(true);
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='contract_options' and policyname='public read contract options') then
    create policy "public read contract options" on public.contract_options for select to anon,authenticated using(true);
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='league_contracts' and policyname='public read league contracts') then
    create policy "public read league contracts" on public.league_contracts for select to anon,authenticated using(true);
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='league_deadlines' and policyname='public read deadlines') then
    create policy "public read deadlines" on public.league_deadlines for select to anon,authenticated using(true);
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='league_deadline_team_status' and policyname='public read deadline status') then
    create policy "public read deadline status" on public.league_deadline_team_status for select to anon,authenticated using(true);
  end if;
end $$;

grant select on public.league_seasons,public.league_rule_settings,public.redistribution_rules,
  public.contract_options,public.league_contracts,public.league_deadlines,public.league_deadline_team_status to anon,authenticated;
revoke insert,update,delete on public.league_seasons,public.league_rule_settings,public.redistribution_rules,
  public.contract_options,public.league_contracts,public.league_deadlines,public.league_deadline_team_status,
  public.league_finance_items,public.league_audit_log from anon,authenticated;
revoke select on public.league_finance_items,public.league_audit_log from anon,authenticated;

-- Helper: current season id.
create or replace function public._league_current_season_id(p_room_code text)
returns uuid language sql stable security definer set search_path=public,pg_temp as $$
  select ls.id from public.league_seasons ls join public.rooms r on r.id=ls.room_id
  where r.code=p_room_code and ls.is_current order by ls.season_year desc limit 1;
$$;

-- Commissioner: save generic numeric rule settings.
create or replace function public.league_commish_set_rules(p_room_code text,p_commish_pin text,p_updates jsonb)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room public.rooms%rowtype; v_season uuid; v_item jsonb; v_key text; v_value numeric;
begin
  select * into v_room from public.rooms where code=p_room_code;
  if v_room.id is null or not public._valid_commish_pin(v_room.id,p_commish_pin) then raise exception 'Commissioner authorization failed.'; end if;
  v_season:=public._league_current_season_id(p_room_code);
  for v_item in select * from jsonb_array_elements(coalesce(p_updates,'[]'::jsonb)) loop
    v_key:=v_item->>'key'; v_value:=(v_item->>'value')::numeric;
    if v_value < 0 or v_value > 10000 then raise exception 'Invalid value for %',v_key; end if;
    update public.league_rule_settings set numeric_value=v_value,updated_at=now() where season_id=v_season and rule_key=v_key and not locked;
  end loop;
  update public.league_seasons ls set roster_limit=coalesce((select numeric_value::int from public.league_rule_settings where season_id=v_season and rule_key='roster_limit'),ls.roster_limit),
    salary_cap_points=coalesce((select numeric_value::int from public.league_rule_settings where season_id=v_season and rule_key='salary_cap_points'),ls.salary_cap_points)
  where id=v_season;
  insert into public.league_audit_log(season_id,action,entity_type,details) values(v_season,'update_rules','league_rule_settings',jsonb_build_object('updates',p_updates));
  return jsonb_build_object('ok',true);
end; $$;

-- Commissioner: save redistribution; requires exactly 12 rows and 100% total.
create or replace function public.league_commish_save_redistribution(p_room_code text,p_commish_pin text,p_rows jsonb)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room public.rooms%rowtype; v_season uuid; v_count int; v_total numeric; v_item jsonb;
begin
  select * into v_room from public.rooms where code=p_room_code;
  if v_room.id is null or not public._valid_commish_pin(v_room.id,p_commish_pin) then raise exception 'Commissioner authorization failed.'; end if;
  v_season:=public._league_current_season_id(p_room_code);
  select count(*),coalesce(sum((x->>'percentage')::numeric),0) into v_count,v_total from jsonb_array_elements(p_rows) x;
  if v_count<>12 then raise exception 'Redistribution requires exactly 12 finish rows.'; end if;
  if abs(v_total-100)>0.0005 then raise exception 'Redistribution must total 100%%. Current total: %',v_total; end if;
  for v_item in select * from jsonb_array_elements(p_rows) loop
    update public.redistribution_rules
    set percentage=(v_item->>'percentage')::numeric,updated_at=now()
    where season_id=v_season and bracket=v_item->>'bracket' and finish=(v_item->>'finish')::int;
  end loop;
  insert into public.league_audit_log(season_id,action,entity_type,details) values(v_season,'update_redistribution','redistribution_rules',jsonb_build_object('rows',p_rows));
  return jsonb_build_object('ok',true,'total',v_total);
end; $$;

-- Commissioner: contract create/update, with cap validation.
create or replace function public.league_commish_upsert_contract(p_room_code text,p_commish_pin text,p_team_id uuid,p_player_name text,p_length_years integer,p_start_year integer)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room public.rooms%rowtype; v_season uuid; v_cost int; v_cap int; v_used int; v_key text; v_id bigint;
begin
  select * into v_room from public.rooms where code=p_room_code;
  if v_room.id is null or not public._valid_commish_pin(v_room.id,p_commish_pin) then raise exception 'Commissioner authorization failed.'; end if;
  if not exists(select 1 from public.teams where id=p_team_id and room_id=v_room.id) then raise exception 'Team not found.'; end if;
  v_season:=public._league_current_season_id(p_room_code); v_key:=public._league_roster_key(p_player_name);
  select cap_cost into v_cost from public.contract_options where season_id=v_season and years=p_length_years and active;
  if v_cost is null then raise exception 'That contract length is not enabled.'; end if;
  select salary_cap_points into v_cap from public.league_seasons where id=v_season;
  select coalesce(sum(cap_cost),0) into v_used from public.league_contracts where season_id=v_season and team_id=p_team_id and status='active' and player_key<>v_key;
  if v_used+v_cost>v_cap then raise exception 'Contract would exceed the % point salary cap.',v_cap; end if;
  insert into public.league_contracts(season_id,team_id,player_key,player_name,start_year,end_year,length_years,cap_cost,status,source)
  values(v_season,p_team_id,v_key,trim(p_player_name),p_start_year,p_start_year+p_length_years-1,p_length_years,v_cost,'active','commissioner')
  on conflict(season_id,player_key) do update set team_id=excluded.team_id,player_name=excluded.player_name,start_year=excluded.start_year,end_year=excluded.end_year,
    length_years=excluded.length_years,cap_cost=excluded.cap_cost,status='active',source='commissioner',updated_at=now()
  returning id into v_id;
  insert into public.league_audit_log(season_id,action,entity_type,entity_id,details) values(v_season,'upsert_contract','league_contracts',v_id::text,jsonb_build_object('team_id',p_team_id,'player',p_player_name,'years',p_length_years,'cost',v_cost));
  return jsonb_build_object('ok',true,'contract_id',v_id,'cap_used',v_used+v_cost,'cap_limit',v_cap);
end; $$;

create or replace function public.league_commish_void_contract(p_room_code text,p_commish_pin text,p_contract_id bigint)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room public.rooms%rowtype; v_season uuid;
begin
 select * into v_room from public.rooms where code=p_room_code;
 if v_room.id is null or not public._valid_commish_pin(v_room.id,p_commish_pin) then raise exception 'Commissioner authorization failed.'; end if;
 v_season:=public._league_current_season_id(p_room_code);
 update public.league_contracts set status='void',updated_at=now() where id=p_contract_id and season_id=v_season;
 insert into public.league_audit_log(season_id,action,entity_type,entity_id) values(v_season,'void_contract','league_contracts',p_contract_id::text);
 return jsonb_build_object('ok',true);
end; $$;

-- Deadlines.
create or replace function public.league_commish_create_deadline(p_room_code text,p_commish_pin text,p_title text,p_deadline_type text,p_due_at timestamptz,p_auto_lock boolean,p_notes text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room public.rooms%rowtype; v_season uuid; v_id uuid;
begin
 select * into v_room from public.rooms where code=p_room_code;
 if v_room.id is null or not public._valid_commish_pin(v_room.id,p_commish_pin) then raise exception 'Commissioner authorization failed.'; end if;
 if length(trim(p_title))<2 then raise exception 'Deadline title is required.'; end if;
 v_season:=public._league_current_season_id(p_room_code);
 insert into public.league_deadlines(season_id,title,deadline_type,due_at,auto_lock,notes) values(v_season,trim(p_title),coalesce(nullif(trim(p_deadline_type),''),'general'),p_due_at,coalesce(p_auto_lock,true),nullif(trim(p_notes),'')) returning id into v_id;
 insert into public.league_deadline_team_status(deadline_id,team_id) select v_id,t.id from public.teams t where t.room_id=v_room.id on conflict do nothing;
 insert into public.league_audit_log(season_id,action,entity_type,entity_id,details) values(v_season,'create_deadline','league_deadlines',v_id::text,jsonb_build_object('title',p_title,'due_at',p_due_at));
 return jsonb_build_object('ok',true,'deadline_id',v_id);
end; $$;

create or replace function public.league_mark_deadline_submitted(p_room_code text,p_team_id uuid,p_pin text,p_deadline_id uuid)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room public.rooms%rowtype; v_due timestamptz; v_lock boolean; v_new text;
begin
 select * into v_room from public.rooms where code=p_room_code;
 if v_room.id is null or not public._valid_team_pin(p_team_id,p_pin) then raise exception 'Team authorization failed.'; end if;
 select d.due_at,d.auto_lock into v_due,v_lock from public.league_deadlines d join public.league_seasons s on s.id=d.season_id where d.id=p_deadline_id and s.room_id=v_room.id and d.status='open';
 if v_due is null then raise exception 'Deadline is not open.'; end if;
 if now()>v_due and v_lock then raise exception 'This deadline is locked.'; end if;
 v_new:=case when now()>v_due then 'late' else 'submitted' end;
 insert into public.league_deadline_team_status(deadline_id,team_id,status,submitted_at,updated_at) values(p_deadline_id,p_team_id,v_new,now(),now())
 on conflict(deadline_id,team_id) do update set status=excluded.status,submitted_at=excluded.submitted_at,updated_at=now();
 return jsonb_build_object('ok',true,'status',v_new);
end; $$;

create or replace function public.league_commish_set_deadline_status(p_room_code text,p_commish_pin text,p_deadline_id uuid,p_status text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room public.rooms%rowtype; v_season uuid;
begin
 select * into v_room from public.rooms where code=p_room_code;
 if v_room.id is null or not public._valid_commish_pin(v_room.id,p_commish_pin) then raise exception 'Commissioner authorization failed.'; end if;
 if p_status not in ('open','closed','completed','cancelled') then raise exception 'Invalid deadline status.'; end if;
 v_season:=public._league_current_season_id(p_room_code);
 update public.league_deadlines set status=p_status,updated_at=now() where id=p_deadline_id and season_id=v_season;
 insert into public.league_audit_log(season_id,action,entity_type,entity_id,details) values(v_season,'deadline_status','league_deadlines',p_deadline_id::text,jsonb_build_object('status',p_status));
 return jsonb_build_object('ok',true);
end; $$;

-- Secure finance read: owner sees only own team; commissioner sees all.
create or replace function public.league_get_finances(p_room_code text,p_team_id uuid,p_pin text,p_commish_pin text default null)
returns setof public.league_finance_items language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room public.rooms%rowtype; v_season uuid; v_commish boolean:=false;
begin
 select * into v_room from public.rooms where code=p_room_code; if v_room.id is null then return; end if;
 v_season:=public._league_current_season_id(p_room_code);
 if p_commish_pin is not null then v_commish:=public._valid_commish_pin(v_room.id,p_commish_pin); end if;
 if v_commish then return query select * from public.league_finance_items where season_id=v_season order by created_at desc; end if;
 if p_team_id is null or not public._valid_team_pin(p_team_id,p_pin) then raise exception 'Team authorization failed.'; end if;
 return query select * from public.league_finance_items where season_id=v_season and team_id=p_team_id order by created_at desc;
end; $$;

create or replace function public.league_commish_add_finance_item(p_room_code text,p_commish_pin text,p_team_id uuid,p_category text,p_description text,p_amount_cents integer,p_due_at date,p_status text default 'due')
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room public.rooms%rowtype; v_season uuid; v_id uuid;
begin
 select * into v_room from public.rooms where code=p_room_code;
 if v_room.id is null or not public._valid_commish_pin(v_room.id,p_commish_pin) then raise exception 'Commissioner authorization failed.'; end if;
 if p_category not in ('dues','prize','expense','adjustment','other') then raise exception 'Invalid finance category.'; end if;
 if p_status not in ('due','paid','waived') then raise exception 'Invalid finance status.'; end if;
 if p_team_id is not null and not exists(select 1 from public.teams where id=p_team_id and room_id=v_room.id) then raise exception 'Team not found.'; end if;
 v_season:=public._league_current_season_id(p_room_code);
 insert into public.league_finance_items(season_id,team_id,category,description,amount_cents,status,due_at,paid_at)
 values(v_season,p_team_id,p_category,trim(p_description),p_amount_cents,p_status,p_due_at,case when p_status='paid' then now() else null end) returning id into v_id;
 insert into public.league_audit_log(season_id,action,entity_type,entity_id,details) values(v_season,'add_finance','league_finance_items',v_id::text,jsonb_build_object('team_id',p_team_id,'category',p_category,'amount_cents',p_amount_cents));
 return jsonb_build_object('ok',true,'id',v_id);
end; $$;

create or replace function public.league_commish_set_finance_status(p_room_code text,p_commish_pin text,p_finance_id uuid,p_status text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room public.rooms%rowtype; v_season uuid;
begin
 select * into v_room from public.rooms where code=p_room_code;
 if v_room.id is null or not public._valid_commish_pin(v_room.id,p_commish_pin) then raise exception 'Commissioner authorization failed.'; end if;
 if p_status not in ('due','paid','waived') then raise exception 'Invalid finance status.'; end if;
 v_season:=public._league_current_season_id(p_room_code);
 update public.league_finance_items set status=p_status,paid_at=case when p_status='paid' then coalesce(paid_at,now()) else null end,updated_at=now() where id=p_finance_id and season_id=v_season;
 insert into public.league_audit_log(season_id,action,entity_type,entity_id,details) values(v_season,'finance_status','league_finance_items',p_finance_id::text,jsonb_build_object('status',p_status));
 return jsonb_build_object('ok',true);
end; $$;

revoke all on function public._league_current_season_id(text) from public,anon,authenticated;
grant execute on function public.league_commish_set_rules(text,text,jsonb) to anon,authenticated;
grant execute on function public.league_commish_save_redistribution(text,text,jsonb) to anon,authenticated;
grant execute on function public.league_commish_upsert_contract(text,text,uuid,text,integer,integer) to anon,authenticated;
grant execute on function public.league_commish_void_contract(text,text,bigint) to anon,authenticated;
grant execute on function public.league_commish_create_deadline(text,text,text,text,timestamptz,boolean,text) to anon,authenticated;
grant execute on function public.league_mark_deadline_submitted(text,uuid,text,uuid) to anon,authenticated;
grant execute on function public.league_commish_set_deadline_status(text,text,uuid,text) to anon,authenticated;
grant execute on function public.league_get_finances(text,uuid,text,text) to anon,authenticated;
grant execute on function public.league_commish_add_finance_item(text,text,uuid,text,text,integer,date,text) to anon,authenticated;
grant execute on function public.league_commish_set_finance_status(text,text,uuid,text) to anon,authenticated;

-- Realtime for public league-office tables.
do $$ begin
 if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='league_rule_settings') then alter publication supabase_realtime add table public.league_rule_settings; end if;
 if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='redistribution_rules') then alter publication supabase_realtime add table public.redistribution_rules; end if;
 if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='league_contracts') then alter publication supabase_realtime add table public.league_contracts; end if;
 if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='league_deadlines') then alter publication supabase_realtime add table public.league_deadlines; end if;
 if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='league_deadline_team_status') then alter publication supabase_realtime add table public.league_deadline_team_status; end if;
end $$;

commit;

-- Sanity check.
select ls.season_year,ls.status,ls.roster_limit,ls.salary_cap_points,
  (select count(*) from public.league_contracts c where c.season_id=ls.id and c.status='active') as active_contracts,
  (select coalesce(sum(rr.percentage),0) from public.redistribution_rules rr where rr.season_id=ls.id) as redistribution_total,
  (select count(*) from public.league_deadlines d where d.season_id=ls.id and d.status='open') as open_deadlines
from public.league_seasons ls join public.rooms r on r.id=ls.room_id
where r.code='GLSK26' and ls.is_current;
