-- GREAT LAKE STATE KEEPERS — LEAGUE OFFICE v3
-- Transactions, player drops + contract penalties, trades + commissioner approval,
-- one-year-ahead Rookie/Supplemental pick ownership, rookie-rights lifecycle,
-- traded-contract extension eligibility, and live extension-cost reference.
--
-- Safe migration for the existing GLSK26 database. Does NOT reset any draft room,
-- team PIN, roster, bid balance, contract, deadline, auction, Supplemental, or Phase 3 result.
-- Run in Supabase SQL Editor using "Run without RLS".

begin;

-- ---------------------------------------------------------------------------
-- Core ledgers
-- ---------------------------------------------------------------------------
create table if not exists public.league_transactions (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.league_seasons(id) on delete cascade,
  transaction_type text not null,
  team_id uuid references public.teams(id),
  other_team_id uuid references public.teams(id),
  player_key text,
  player_name text,
  description text not null,
  bid_delta integer not null default 0,
  cap_delta integer not null default 0,
  status text not null default 'completed' check(status in ('completed','pending','reversed')),
  related_type text,
  related_id text,
  external_key text,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  reversed_at timestamptz,
  reversed_by uuid references public.league_transactions(id)
);
create unique index if not exists league_transactions_external_uq
  on public.league_transactions(season_id,external_key) where external_key is not null;
create index if not exists league_transactions_created_idx
  on public.league_transactions(season_id,created_at desc);
create index if not exists league_transactions_team_idx
  on public.league_transactions(season_id,team_id,created_at desc);

create table if not exists public.league_future_picks (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  draft_year integer not null,
  draft_type text not null check(draft_type in ('rookie','supplemental')),
  round integer not null check(round between 1 and 10),
  original_team_id uuid not null references public.teams(id),
  owner_team_id uuid not null references public.teams(id),
  status text not null default 'active' check(status in ('active','used','forfeited')),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(room_id,draft_year,draft_type,round,original_team_id)
);
create index if not exists league_future_picks_owner_idx
  on public.league_future_picks(room_id,owner_team_id,draft_year,draft_type,round);

create table if not exists public.league_rookie_rights (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  player_key text not null,
  player_name text not null,
  rookie_draft_year integer not null,
  owner_team_id uuid references public.teams(id),
  origin text not null default 'rookie_draft',
  status text not null default 'active' check(status in ('active','extinguished','expired')),
  extinguished_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(room_id,player_key)
);
create index if not exists league_rookie_rights_owner_idx
  on public.league_rookie_rights(room_id,owner_team_id,status);

create table if not exists public.league_extension_costs (
  season_id uuid not null references public.league_seasons(id) on delete cascade,
  position text not null check(position in ('QB','RB','WR','TE')),
  top_bid_1 integer,
  top_bid_2 integer,
  top_bid_3 integer,
  average_bid numeric(10,2),
  cost_2_to_3 integer,
  cost_3_to_4 integer,
  calculated_at timestamptz not null default now(),
  primary key(season_id,position)
);

create table if not exists public.league_trades (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.league_seasons(id) on delete cascade,
  proposer_team_id uuid not null references public.teams(id),
  partner_team_id uuid not null references public.teams(id),
  status text not null default 'proposed'
    check(status in ('proposed','pending_commish','approved','rejected','denied','cancelled')),
  note text,
  proposed_at timestamptz not null default now(),
  accepted_at timestamptz,
  decided_at timestamptz,
  commissioner_team_id uuid references public.teams(id),
  updated_at timestamptz not null default now(),
  check(proposer_team_id<>partner_team_id)
);
create index if not exists league_trades_season_idx
  on public.league_trades(season_id,status,proposed_at desc);

create table if not exists public.league_trade_assets (
  id bigint generated by default as identity primary key,
  trade_id uuid not null references public.league_trades(id) on delete cascade,
  direction text not null check(direction in ('proposer_to_partner','partner_to_proposer')),
  asset_type text not null check(asset_type in ('player','rookie_rights','rookie_pick','supplemental_pick','bid_dollars')),
  asset_key text,
  player_name text,
  pick_id uuid references public.league_future_picks(id),
  bid_amount integer,
  details jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default now(),
  check((asset_type='bid_dollars' and bid_amount is not null and bid_amount>0) or asset_type<>'bid_dollars')
);
create index if not exists league_trade_assets_trade_idx on public.league_trade_assets(trade_id,direction,id);

create table if not exists public.league_contract_extension_eligibility (
  id uuid primary key default gen_random_uuid(),
  season_id uuid not null references public.league_seasons(id) on delete cascade,
  contract_id bigint not null references public.league_contracts(id) on delete cascade,
  trade_id uuid not null references public.league_trades(id) on delete cascade,
  team_id uuid not null references public.teams(id),
  eligible_to_years integer not null check(eligible_to_years in (3,4)),
  status text not null default 'eligible' check(status in ('eligible','exercised','superseded','expired')),
  created_at timestamptz not null default now(),
  exercised_at timestamptz
);
create index if not exists league_contract_extension_team_idx
  on public.league_contract_extension_eligibility(season_id,team_id,status);

-- ---------------------------------------------------------------------------
-- RLS: league transactions / trade assets are league-visible; writes are RPC-only.
-- ---------------------------------------------------------------------------
alter table public.league_transactions enable row level security;
alter table public.league_future_picks enable row level security;
alter table public.league_rookie_rights enable row level security;
alter table public.league_extension_costs enable row level security;
alter table public.league_trades enable row level security;
alter table public.league_trade_assets enable row level security;
alter table public.league_contract_extension_eligibility enable row level security;

do $$ begin
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='league_transactions' and policyname='public read league transactions') then
    create policy "public read league transactions" on public.league_transactions for select to anon,authenticated using(true);
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='league_future_picks' and policyname='public read league future picks') then
    create policy "public read league future picks" on public.league_future_picks for select to anon,authenticated using(true);
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='league_rookie_rights' and policyname='public read rookie rights') then
    create policy "public read rookie rights" on public.league_rookie_rights for select to anon,authenticated using(true);
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='league_extension_costs' and policyname='public read extension costs') then
    create policy "public read extension costs" on public.league_extension_costs for select to anon,authenticated using(true);
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='league_trades' and policyname='public read league trades') then
    create policy "public read league trades" on public.league_trades for select to anon,authenticated using(true);
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='league_trade_assets' and policyname='public read trade assets') then
    create policy "public read trade assets" on public.league_trade_assets for select to anon,authenticated using(true);
  end if;
  if not exists(select 1 from pg_policies where schemaname='public' and tablename='league_contract_extension_eligibility' and policyname='public read extension eligibility') then
    create policy "public read extension eligibility" on public.league_contract_extension_eligibility for select to anon,authenticated using(true);
  end if;
end $$;

grant select on public.league_transactions,public.league_future_picks,public.league_rookie_rights,
  public.league_extension_costs,public.league_trades,public.league_trade_assets,
  public.league_contract_extension_eligibility to anon,authenticated;
revoke insert,update,delete on public.league_transactions,public.league_future_picks,public.league_rookie_rights,
  public.league_extension_costs,public.league_trades,public.league_trade_assets,
  public.league_contract_extension_eligibility from anon,authenticated;

-- ---------------------------------------------------------------------------
-- 2027 pick ownership. In 2026 only the next league year's picks are tradable.
-- Both the Rookie and Supplemental drafts currently have two rounds.
-- ---------------------------------------------------------------------------
insert into public.league_future_picks(room_id,draft_year,draft_type,round,original_team_id,owner_team_id)
select r.id,2027,d.draft_type,rd.round,t.id,t.id
from public.rooms r
join public.teams t on t.room_id=r.id
cross join (values('rookie'),('supplemental')) d(draft_type)
cross join (values(1),(2)) rd(round)
where r.code='GLSK26'
on conflict(room_id,draft_year,draft_type,round,original_team_id) do nothing;

-- ---------------------------------------------------------------------------
-- Rookie rights foundation.
-- Only drafted rookies are seeded. Rights are only retained if the player is
-- currently rostered; a dropped player therefore does not regain rights here.
-- ---------------------------------------------------------------------------
with r as (select id from public.rooms where code='GLSK26'),
vals(player_name,team_name,rookie_year) as (values
  -- Confirmed Top-40 rights
  ('Omarion Hampton','MEGATRONS V2',2026),('Colston Loveland','hugs not drugs',2026),
  ('Tyler Warren','Reggie Kush',2026),('Cam Skattebo','kerwinning it',2026),
  ('Quinshon Judkins','Suburban White Kid',2026),('Bhayshul Tuten','The Real McCoy',2026),
  -- 2026 Rookie Draft — 24 drafted rookies
  ('Jeremiyah Love','Klyde Frogs',2026),('Jadarian Price','Slim Charles',2026),
  ('Carnell Tate','Klyde Frogs',2026),('Makai Lemon','The Real McCoy',2026),
  ('KC Concepcion','Suburban White Kid',2026),('Jonah Coleman','Weiss Tea & Lemonade',2026),
  ('Jordyn Tyson','kerwinning it',2026),('Kaelon Black','7th Floor Crew',2026),
  ('De''Zhaun Stribling','hugs not drugs',2026),('Denzel Boston','Reggie Kush',2026),
  ('Eli Stowers','MEGATRONS V2',2026),('Emmett Johnson','The Hebrew Hammer',2026),
  ('Mike Washington Jr','Klyde Frogs',2026),('Ja''kobi Lane','Slim Charles',2026),
  ('Kenyon Sadiq','hugs not drugs',2026),('Fernando Mendoza','The Real McCoy',2026),
  ('Omar Cooper Jr.','Suburban White Kid',2026),('Germie Bernard','Weiss Tea & Lemonade',2026),
  ('Eli Raridon','kerwinning it',2026),('Zachariah Branch','7th Floor Crew',2026),
  ('Chris Bell','Team Ramrod',2026),('Nicholas Singleton','Reggie Kush',2026),
  ('Antonio Williams','MEGATRONS V2',2026),('Cyrus Allen','The Hebrew Hammer',2026),
  -- Surviving prior-year drafted-rookie rights used by the 2026 restricted-rights rule
  ('Jaxson Dart','7th Floor Crew',2025),('Woody Marks','The Hebrew Hammer',2025),
  ('Travis Hunter','kerwinning it',2025),('Matthew Golden','Klyde Frogs',2025),
  ('Jacory Croskey-Merritt','Slim Charles',2025),('Ollie Gordon II','Slim Charles',2025),
  ('RJ Harvey','Suburban White Kid',2025),('Cam Ward','Weiss Tea & Lemonade',2025),
  ('Tre'' Harris','Weiss Tea & Lemonade',2025),('Jaydon Blue','Reggie Kush',2025)
)
insert into public.league_rookie_rights(room_id,player_key,player_name,rookie_draft_year,owner_team_id,origin,status)
select r.id,public._league_roster_key(v.player_name),re.player_name,v.rookie_year,t.id,'rookie_draft','active'
from r cross join vals v
join public.teams t on t.room_id=r.id and t.name=v.team_name
join public.league_roster_entries re on re.room_id=r.id
  and re.player_key=public._league_roster_key(v.player_name) and re.active=true
on conflict(room_id,player_key) do update
set player_name=excluded.player_name,
    owner_team_id=case when public.league_rookie_rights.status='active' then excluded.owner_team_id else public.league_rookie_rights.owner_team_id end,
    rookie_draft_year=excluded.rookie_draft_year,
    updated_at=now();

-- ---------------------------------------------------------------------------
-- Extension-cost snapshot: actual top three Auction winning bids by position.
-- QB/RB/WR/TE only; K and D/ST intentionally excluded by league rule.
-- ---------------------------------------------------------------------------
with s as (
  select ls.id season_id,r.id room_id
  from public.league_seasons ls join public.rooms r on r.id=ls.room_id
  where r.code='GLSK26' and ls.is_current
), ranked as (
  select s.season_id,p.position,sa.price,
         row_number() over(partition by p.position order by sa.price desc,sa.sold_at asc) rn
  from s
  join public.sales sa on sa.room_id=s.room_id and sa.undone=false
  join public.players p on p.id=sa.player_id
  where p.position in ('QB','RB','WR','TE')
), top3 as (
  select season_id,position,
         max(price) filter(where rn=1) b1,
         max(price) filter(where rn=2) b2,
         max(price) filter(where rn=3) b3,
         avg(price::numeric) filter(where rn<=3) avg_bid,
         count(*) filter(where rn<=3) cnt
  from ranked group by season_id,position
)
insert into public.league_extension_costs(season_id,position,top_bid_1,top_bid_2,top_bid_3,average_bid,cost_2_to_3,cost_3_to_4,calculated_at)
select season_id,position,b1,b2,b3,round(avg_bid,2),
       case when cnt=3 then round(avg_bid*0.25)::int end,
       case when cnt=3 then round(avg_bid*0.40)::int end,
       now()
from top3
on conflict(season_id,position) do update
set top_bid_1=excluded.top_bid_1,top_bid_2=excluded.top_bid_2,top_bid_3=excluded.top_bid_3,
    average_bid=excluded.average_bid,cost_2_to_3=excluded.cost_2_to_3,cost_3_to_4=excluded.cost_3_to_4,
    calculated_at=now();

-- ---------------------------------------------------------------------------
-- Helper: transaction logging.
-- ---------------------------------------------------------------------------
create or replace function public._league_log_transaction(
  p_season_id uuid,p_type text,p_team_id uuid,p_other_team_id uuid,
  p_player_key text,p_player_name text,p_description text,
  p_bid_delta integer default 0,p_cap_delta integer default 0,
  p_related_type text default null,p_related_id text default null,
  p_external_key text default null,p_details jsonb default '{}'::jsonb
) returns uuid
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_id uuid;
begin
  insert into public.league_transactions(
    season_id,transaction_type,team_id,other_team_id,player_key,player_name,description,
    bid_delta,cap_delta,related_type,related_id,external_key,details
  ) values(
    p_season_id,p_type,p_team_id,p_other_team_id,p_player_key,p_player_name,p_description,
    coalesce(p_bid_delta,0),coalesce(p_cap_delta,0),p_related_type,p_related_id,p_external_key,coalesce(p_details,'{}'::jsonb)
  )
  on conflict(season_id,external_key) where external_key is not null do update
    set description=excluded.description
  returning id into v_id;
  return v_id;
end;
$$;
revoke all on function public._league_log_transaction(uuid,text,uuid,uuid,text,text,text,integer,integer,text,text,text,jsonb)
from public,anon,authenticated;

-- Backfill known completed draft-room transactions once.
with s as (select ls.id season_id,r.id room_id from public.league_seasons ls join public.rooms r on r.id=ls.room_id where r.code='GLSK26' and ls.is_current)
insert into public.league_transactions(season_id,transaction_type,team_id,player_key,player_name,description,bid_delta,related_type,related_id,external_key,details,created_at)
select s.season_id,'auction',coalesce((select art.from_team_id from public.auction_rights_transfers art where art.room_id=sa.room_id and art.player_id=sa.player_id order by art.transferred_at desc limit 1),sa.team_id),public._league_roster_key(p.name),p.name,
       p.name||' won in Free Agent Auction for '||sa.price||' bid dollars',-sa.price,
       'sales',sa.id::text,'auction:'||sa.id::text,jsonb_build_object('price',sa.price,'position',p.position),sa.sold_at
from s join public.sales sa on sa.room_id=s.room_id and sa.undone=false join public.players p on p.id=sa.player_id
on conflict(season_id,external_key) where external_key is not null do nothing;

with s as (select ls.id season_id,r.id room_id from public.league_seasons ls join public.rooms r on r.id=ls.room_id where r.code='GLSK26' and ls.is_current)
insert into public.league_transactions(season_id,transaction_type,team_id,player_key,player_name,description,bid_delta,related_type,related_id,external_key,details,created_at)
select s.season_id,'supplemental',pk.winner_team_id,public._league_roster_key(p.name),p.name,
       p.name||' acquired in Supplemental Draft'||case when pk.price>0 then ' for '||pk.price||' bid dollars' else ' for free' end,
       -pk.price,'supplemental_picks',pk.id::text,'supplemental:'||pk.id::text,
       jsonb_build_object('pick_no',pk.pick_no,'round',pk.round,'outcome',pk.outcome,'price',pk.price),pk.created_at
from s join public.supplemental_picks pk on pk.room_id=s.room_id join public.supplemental_players p on p.id=pk.player_id
on conflict(season_id,external_key) where external_key is not null do nothing;

with s as (select ls.id season_id,r.id room_id from public.league_seasons ls join public.rooms r on r.id=ls.room_id where r.code='GLSK26' and ls.is_current)
insert into public.league_transactions(season_id,transaction_type,team_id,player_key,player_name,description,related_type,related_id,external_key,details,created_at)
select s.season_id,'phase3',pk.team_id,public._league_roster_key(p.name),p.name,
       p.name||' selected in Roster-Fill Snake Draft','phase3_picks',pk.id::text,'phase3:'||pk.id::text,
       jsonb_build_object('pick_no',pk.pick_no,'round',pk.round),pk.created_at
from s join public.phase3_picks pk on pk.room_id=s.room_id join public.phase3_players p on p.id=pk.player_id
on conflict(season_id,external_key) where external_key is not null do nothing;

-- ---------------------------------------------------------------------------
-- Drop penalty helper.
-- Year 1: double assigned contract points. Later years: 2yr=5, 3yr=10, 4yr=20.
-- ---------------------------------------------------------------------------
create or replace function public._league_drop_penalty(p_contract public.league_contracts,p_season_year integer)
returns integer language plpgsql immutable as $$
declare v_year integer;
begin
  if p_contract.id is null then return 0; end if;
  v_year:=greatest(1,p_season_year-p_contract.start_year+1);
  if v_year=1 then return p_contract.cap_cost*2; end if;
  return case p_contract.length_years when 2 then 5 when 3 then 10 when 4 then 20 else 0 end;
end;
$$;
revoke all on function public._league_drop_penalty(public.league_contracts,integer) from public,anon,authenticated;

create or replace function public.league_owner_drop_player(
  p_room_code text,p_team_id uuid,p_pin text,p_player_key text
) returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_room public.rooms%rowtype; v_season uuid; v_year integer;
  v_roster public.league_roster_entries%rowtype; v_contract public.league_contracts%rowtype;
  v_team public.teams%rowtype; v_penalty integer:=0; v_tx uuid;
begin
  select * into v_room from public.rooms where code=p_room_code;
  if v_room.id is null or not public._valid_team_pin(p_team_id,p_pin) then raise exception 'Team authorization failed.'; end if;
  v_season:=public._league_current_season_id(p_room_code);
  select season_year into v_year from public.league_seasons where id=v_season;
  select * into v_team from public.teams where id=p_team_id and room_id=v_room.id for update;
  if v_team.id is null then raise exception 'Team not found.'; end if;
  select * into v_roster from public.league_roster_entries
    where room_id=v_room.id and team_id=p_team_id and player_key=p_player_key and active=true for update;
  if v_roster.id is null then raise exception 'That player is not on your active roster.'; end if;
  select * into v_contract from public.league_contracts
    where season_id=v_season and team_id=p_team_id and player_key=p_player_key and status='active' for update;
  if v_contract.id is not null then v_penalty:=public._league_drop_penalty(v_contract,v_year); end if;
  if v_team.remaining_budget<v_penalty then
    raise exception 'Drop blocked. Contract penalty is % bid dollars but you only have % remaining.',v_penalty,v_team.remaining_budget;
  end if;
  if v_penalty>0 then update public.teams set remaining_budget=remaining_budget-v_penalty where id=p_team_id; end if;
  update public.league_roster_entries set active=false,updated_at=now() where id=v_roster.id;
  if v_contract.id is not null then update public.league_contracts set status='released',updated_at=now() where id=v_contract.id; end if;
  update public.league_rookie_rights
    set status='extinguished',owner_team_id=null,extinguished_reason='player dropped',updated_at=now()
    where room_id=v_room.id and player_key=p_player_key and status='active';
  v_tx:=public._league_log_transaction(v_season,'drop',p_team_id,null,p_player_key,v_roster.player_name,
    v_roster.player_name||' dropped'||case when v_penalty>0 then ' • '||v_penalty||' bid-dollar contract penalty' else '' end,
    -v_penalty,case when v_contract.id is null then 0 else -v_contract.cap_cost end,
    'league_roster_entries',v_roster.id::text,null,
    jsonb_build_object('penalty',v_penalty,'contract_id',v_contract.id,'contract_length',v_contract.length_years,'contract_year',case when v_contract.id is null then null else greatest(1,v_year-v_contract.start_year+1) end,'rookie_rights_extinguished',exists(select 1 from public.league_rookie_rights where room_id=v_room.id and player_key=p_player_key and status='extinguished')));
  return jsonb_build_object('ok',true,'player',v_roster.player_name,'penalty',v_penalty,'transaction_id',v_tx,'remaining_budget',v_team.remaining_budget-v_penalty);
end;
$$;
grant execute on function public.league_owner_drop_player(text,uuid,text,text) to anon,authenticated;

create or replace function public.league_commish_exception_drop(
  p_room_code text,p_commish_pin text,p_team_id uuid,p_player_key text,p_reason text
) returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room public.rooms%rowtype; v_season uuid; v_roster public.league_roster_entries%rowtype; v_contract public.league_contracts%rowtype; v_tx uuid;
begin
  select * into v_room from public.rooms where code=p_room_code;
  if v_room.id is null or not public._valid_commish_pin(v_room.id,p_commish_pin) then raise exception 'Commissioner authorization failed.'; end if;
  if lower(coalesce(p_reason,'')) not in ('retirement','ban','banned') then raise exception 'No-penalty exception is only for retirement or ban.'; end if;
  v_season:=public._league_current_season_id(p_room_code);
  select * into v_roster from public.league_roster_entries where room_id=v_room.id and team_id=p_team_id and player_key=p_player_key and active=true for update;
  if v_roster.id is null then raise exception 'Active roster player not found.'; end if;
  select * into v_contract from public.league_contracts where season_id=v_season and team_id=p_team_id and player_key=p_player_key and status='active' for update;
  update public.league_roster_entries set active=false,updated_at=now() where id=v_roster.id;
  if v_contract.id is not null then update public.league_contracts set status='void',updated_at=now() where id=v_contract.id; end if;
  update public.league_rookie_rights set status='extinguished',owner_team_id=null,extinguished_reason=p_reason,updated_at=now()
    where room_id=v_room.id and player_key=p_player_key and status='active';
  v_tx:=public._league_log_transaction(v_season,'contract_voided',p_team_id,null,p_player_key,v_roster.player_name,
    v_roster.player_name||' removed • contract voided for '||p_reason||' • no penalty',0,
    case when v_contract.id is null then 0 else -v_contract.cap_cost end,'league_roster_entries',v_roster.id::text,null,
    jsonb_build_object('reason',p_reason,'contract_id',v_contract.id));
  return jsonb_build_object('ok',true,'transaction_id',v_tx);
end;
$$;
grant execute on function public.league_commish_exception_drop(text,text,uuid,text,text) to anon,authenticated;

-- ---------------------------------------------------------------------------
-- Trade validation helper. Enforces ownership, one-year-ahead pick rule,
-- bid-dollar availability, and the 100-point contract cap BEFORE a trade can proceed.
-- ---------------------------------------------------------------------------
create or replace function public._league_validate_trade(p_trade_id uuid)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_trade public.league_trades%rowtype; v_season public.league_seasons%rowtype; v_room_id uuid;
  a record; v_owner uuid; v_other uuid; v_give_bid integer:=0; v_receive_bid integer:=0;
  v_prop_cap integer; v_partner_cap integer; v_prop_out integer:=0; v_prop_in integer:=0; v_part_out integer:=0; v_part_in integer:=0;
  v_limit integer;
begin
  select * into v_trade from public.league_trades where id=p_trade_id;
  if v_trade.id is null then return jsonb_build_object('ok',false,'error','Trade not found.'); end if;
  select * into v_season from public.league_seasons where id=v_trade.season_id;
  v_room_id:=v_season.room_id; v_limit:=v_season.salary_cap_points;
  select coalesce(sum(cap_cost),0) into v_prop_cap from public.league_contracts where season_id=v_season.id and team_id=v_trade.proposer_team_id and status='active';
  select coalesce(sum(cap_cost),0) into v_partner_cap from public.league_contracts where season_id=v_season.id and team_id=v_trade.partner_team_id and status='active';

  for a in select * from public.league_trade_assets where trade_id=p_trade_id loop
    v_owner:=case when a.direction='proposer_to_partner' then v_trade.proposer_team_id else v_trade.partner_team_id end;
    v_other:=case when a.direction='proposer_to_partner' then v_trade.partner_team_id else v_trade.proposer_team_id end;
    if a.asset_type='player' then
      if not exists(select 1 from public.league_roster_entries where room_id=v_room_id and team_id=v_owner and player_key=a.asset_key and active=true) then
        return jsonb_build_object('ok',false,'error',coalesce(a.player_name,a.asset_key)||' is no longer owned by the sending team.');
      end if;
      if a.direction='proposer_to_partner' then
        select coalesce(cap_cost,0) into v_prop_out from public.league_contracts where season_id=v_season.id and team_id=v_owner and player_key=a.asset_key and status='active';
        v_prop_out:=coalesce(v_prop_out,0);
        v_part_in:=v_part_in+v_prop_out;
      else
        select coalesce(cap_cost,0) into v_part_out from public.league_contracts where season_id=v_season.id and team_id=v_owner and player_key=a.asset_key and status='active';
        v_part_out:=coalesce(v_part_out,0);
        v_prop_in:=v_prop_in+v_part_out;
      end if;
    elsif a.asset_type='rookie_rights' then
      if not exists(select 1 from public.league_rookie_rights where room_id=v_room_id and player_key=a.asset_key and owner_team_id=v_owner and status='active') then
        return jsonb_build_object('ok',false,'error','Rookie rights are no longer owned by the sending team.');
      end if;
      if exists(select 1 from public.league_trade_assets x where x.trade_id=p_trade_id and x.asset_type='player' and x.asset_key=a.asset_key) then
        return jsonb_build_object('ok',false,'error','Do not add rookie rights separately when the same player is in the trade; rights transfer automatically with the player.');
      end if;
    elsif a.asset_type in ('rookie_pick','supplemental_pick') then
      if a.pick_id is null or not exists(
        select 1 from public.league_future_picks fp where fp.id=a.pick_id and fp.room_id=v_room_id and fp.owner_team_id=v_owner and fp.status='active'
          and fp.draft_year=v_season.season_year+1
          and fp.draft_type=case when a.asset_type='rookie_pick' then 'rookie' else 'supplemental' end
      ) then return jsonb_build_object('ok',false,'error','That future draft pick is not currently tradable by the sending team.'); end if;
    elsif a.asset_type='bid_dollars' then
      if a.direction='proposer_to_partner' then v_give_bid:=v_give_bid+coalesce(a.bid_amount,0); else v_receive_bid:=v_receive_bid+coalesce(a.bid_amount,0); end if;
    end if;
  end loop;

  if v_give_bid>(select remaining_budget from public.teams where id=v_trade.proposer_team_id) then return jsonb_build_object('ok',false,'error','Proposer does not have enough bid dollars.'); end if;
  if v_receive_bid>(select remaining_budget from public.teams where id=v_trade.partner_team_id) then return jsonb_build_object('ok',false,'error','Partner does not have enough bid dollars.'); end if;

  -- Sum outgoing player contract points correctly, independent of row loop ordering.
  select coalesce(sum(c.cap_cost),0) into v_prop_out
  from public.league_trade_assets a join public.league_contracts c on c.season_id=v_season.id and c.team_id=v_trade.proposer_team_id and c.player_key=a.asset_key and c.status='active'
  where a.trade_id=p_trade_id and a.direction='proposer_to_partner' and a.asset_type='player';
  select coalesce(sum(c.cap_cost),0) into v_part_out
  from public.league_trade_assets a join public.league_contracts c on c.season_id=v_season.id and c.team_id=v_trade.partner_team_id and c.player_key=a.asset_key and c.status='active'
  where a.trade_id=p_trade_id and a.direction='partner_to_proposer' and a.asset_type='player';
  v_prop_in:=v_part_out; v_part_in:=v_prop_out;

  if v_prop_cap-v_prop_out+v_prop_in>v_limit then
    return jsonb_build_object('ok',false,'error','Trade blocked: proposer would be over the '||v_limit||'-point contract cap.','proposer_cap_after',v_prop_cap-v_prop_out+v_prop_in,'partner_cap_after',v_partner_cap-v_part_out+v_part_in);
  end if;
  if v_partner_cap-v_part_out+v_part_in>v_limit then
    return jsonb_build_object('ok',false,'error','Trade blocked: partner would be over the '||v_limit||'-point contract cap.','proposer_cap_after',v_prop_cap-v_prop_out+v_prop_in,'partner_cap_after',v_partner_cap-v_part_out+v_part_in);
  end if;
  return jsonb_build_object('ok',true,'proposer_cap_before',v_prop_cap,'partner_cap_before',v_partner_cap,
    'proposer_cap_after',v_prop_cap-v_prop_out+v_prop_in,'partner_cap_after',v_partner_cap-v_part_out+v_part_in,
    'proposer_bid_send',v_give_bid,'partner_bid_send',v_receive_bid);
end;
$$;
revoke all on function public._league_validate_trade(uuid) from public,anon,authenticated;

create or replace function public.league_owner_propose_trade(
  p_room_code text,p_team_id uuid,p_pin text,p_partner_team_id uuid,
  p_give jsonb,p_receive jsonb,p_note text default null
) returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_room public.rooms%rowtype; v_season uuid; v_trade uuid; item jsonb; v_type text; v_validation jsonb; v_name text;
begin
  select * into v_room from public.rooms where code=p_room_code;
  if v_room.id is null or not public._valid_team_pin(p_team_id,p_pin) then raise exception 'Team authorization failed.'; end if;
  if p_partner_team_id=p_team_id or not exists(select 1 from public.teams where id=p_partner_team_id and room_id=v_room.id) then raise exception 'Choose another league team.'; end if;
  v_season:=public._league_current_season_id(p_room_code);
  insert into public.league_trades(season_id,proposer_team_id,partner_team_id,note) values(v_season,p_team_id,p_partner_team_id,nullif(trim(p_note),'')) returning id into v_trade;

  for item in select * from jsonb_array_elements(coalesce(p_give,'[]'::jsonb)) loop
    v_type:=item->>'type'; v_name:=item->>'name';
    insert into public.league_trade_assets(trade_id,direction,asset_type,asset_key,player_name,pick_id,bid_amount,details)
    values(v_trade,'proposer_to_partner',v_type,item->>'key',v_name,nullif(item->>'pick_id','')::uuid,nullif(item->>'amount','')::integer,item);
  end loop;
  for item in select * from jsonb_array_elements(coalesce(p_receive,'[]'::jsonb)) loop
    v_type:=item->>'type'; v_name:=item->>'name';
    insert into public.league_trade_assets(trade_id,direction,asset_type,asset_key,player_name,pick_id,bid_amount,details)
    values(v_trade,'partner_to_proposer',v_type,item->>'key',v_name,nullif(item->>'pick_id','')::uuid,nullif(item->>'amount','')::integer,item);
  end loop;
  if not exists(select 1 from public.league_trade_assets where trade_id=v_trade) then delete from public.league_trades where id=v_trade; raise exception 'A trade needs at least one asset.'; end if;
  v_validation:=public._league_validate_trade(v_trade);
  if coalesce((v_validation->>'ok')::boolean,false)=false then delete from public.league_trades where id=v_trade; raise exception '%',v_validation->>'error'; end if;
  return jsonb_build_object('ok',true,'trade_id',v_trade,'validation',v_validation);
end;
$$;
grant execute on function public.league_owner_propose_trade(text,uuid,text,uuid,jsonb,jsonb,text) to anon,authenticated;

create or replace function public.league_owner_trade_response(
  p_room_code text,p_team_id uuid,p_pin text,p_trade_id uuid,p_accept boolean
) returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room public.rooms%rowtype; v_trade public.league_trades%rowtype; v_validation jsonb;
begin
  select * into v_room from public.rooms where code=p_room_code;
  if v_room.id is null or not public._valid_team_pin(p_team_id,p_pin) then raise exception 'Team authorization failed.'; end if;
  select tr.* into v_trade from public.league_trades tr join public.league_seasons s on s.id=tr.season_id where tr.id=p_trade_id and s.room_id=v_room.id for update;
  if v_trade.id is null or v_trade.partner_team_id<>p_team_id or v_trade.status<>'proposed' then raise exception 'That trade is not awaiting your response.'; end if;
  if not p_accept then update public.league_trades set status='rejected',decided_at=now(),updated_at=now() where id=p_trade_id; return jsonb_build_object('ok',true,'status','rejected'); end if;
  v_validation:=public._league_validate_trade(p_trade_id);
  if coalesce((v_validation->>'ok')::boolean,false)=false then raise exception '%',v_validation->>'error'; end if;
  update public.league_trades set status='pending_commish',accepted_at=now(),updated_at=now() where id=p_trade_id;
  return jsonb_build_object('ok',true,'status','pending_commish','validation',v_validation);
end;
$$;
grant execute on function public.league_owner_trade_response(text,uuid,text,uuid,boolean) to anon,authenticated;

create or replace function public.league_owner_cancel_trade(
  p_room_code text,p_team_id uuid,p_pin text,p_trade_id uuid
) returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room public.rooms%rowtype; v_trade public.league_trades%rowtype;
begin
  select * into v_room from public.rooms where code=p_room_code;
  if v_room.id is null or not public._valid_team_pin(p_team_id,p_pin) then raise exception 'Team authorization failed.'; end if;
  select tr.* into v_trade from public.league_trades tr join public.league_seasons s on s.id=tr.season_id where tr.id=p_trade_id and s.room_id=v_room.id for update;
  if v_trade.id is null or v_trade.proposer_team_id<>p_team_id or v_trade.status not in ('proposed','pending_commish') then raise exception 'That trade cannot be cancelled.'; end if;
  update public.league_trades set status='cancelled',decided_at=now(),updated_at=now() where id=p_trade_id;
  return jsonb_build_object('ok',true);
end;
$$;
grant execute on function public.league_owner_cancel_trade(text,uuid,text,uuid) to anon,authenticated;

create or replace function public.league_commish_trade_decision(
  p_room_code text,p_commish_pin text,p_trade_id uuid,p_approve boolean
) returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_room public.rooms%rowtype; v_trade public.league_trades%rowtype; v_validation jsonb; a record;
  v_from uuid; v_to uuid; v_contract public.league_contracts%rowtype; v_target_years integer; v_tx uuid; v_commish uuid;
  v_prop_name text; v_partner_name text;
begin
  select * into v_room from public.rooms where code=p_room_code;
  if v_room.id is null or not public._valid_commish_pin(v_room.id,p_commish_pin) then raise exception 'Commissioner authorization failed.'; end if;
  select id into v_commish from public.teams where room_id=v_room.id and name='Weiss Tea & Lemonade';
  select tr.* into v_trade from public.league_trades tr join public.league_seasons s on s.id=tr.season_id where tr.id=p_trade_id and s.room_id=v_room.id for update;
  if v_trade.id is null or v_trade.status<>'pending_commish' then raise exception 'Trade is not awaiting commissioner approval.'; end if;
  if not p_approve then update public.league_trades set status='denied',decided_at=now(),commissioner_team_id=v_commish,updated_at=now() where id=p_trade_id; return jsonb_build_object('ok',true,'status','denied'); end if;
  v_validation:=public._league_validate_trade(p_trade_id);
  if coalesce((v_validation->>'ok')::boolean,false)=false then raise exception '%',v_validation->>'error'; end if;

  -- Transfer players first; active contracts follow with unchanged current term/value.
  for a in select * from public.league_trade_assets where trade_id=p_trade_id and asset_type='player' order by id loop
    v_from:=case when a.direction='proposer_to_partner' then v_trade.proposer_team_id else v_trade.partner_team_id end;
    v_to:=case when a.direction='proposer_to_partner' then v_trade.partner_team_id else v_trade.proposer_team_id end;
    update public.league_roster_entries set team_id=v_to,updated_at=now() where room_id=v_room.id and team_id=v_from and player_key=a.asset_key and active=true;
    select * into v_contract from public.league_contracts where season_id=v_trade.season_id and team_id=v_from and player_key=a.asset_key and status='active' for update;
    if v_contract.id is not null then
      update public.league_contracts set team_id=v_to,source='trade',updated_at=now() where id=v_contract.id;
      update public.league_contract_extension_eligibility set status='superseded' where contract_id=v_contract.id and status='eligible';
      v_target_years:=case v_contract.length_years when 2 then 3 when 3 then 4 else null end;
      if v_target_years is not null then
        insert into public.league_contract_extension_eligibility(season_id,contract_id,trade_id,team_id,eligible_to_years,status)
        values(v_trade.season_id,v_contract.id,p_trade_id,v_to,v_target_years,'eligible');
      end if;
    end if;
    -- Constitution: rookie rights automatically follow a rights player when the player is traded.
    update public.league_rookie_rights set owner_team_id=v_to,updated_at=now()
      where room_id=v_room.id and player_key=a.asset_key and status='active';
  end loop;

  -- Separately traded rights.
  for a in select * from public.league_trade_assets where trade_id=p_trade_id and asset_type='rookie_rights' order by id loop
    v_to:=case when a.direction='proposer_to_partner' then v_trade.partner_team_id else v_trade.proposer_team_id end;
    update public.league_rookie_rights set owner_team_id=v_to,updated_at=now() where room_id=v_room.id and player_key=a.asset_key and status='active';
  end loop;
  -- Future picks.
  for a in select * from public.league_trade_assets where trade_id=p_trade_id and asset_type in ('rookie_pick','supplemental_pick') order by id loop
    v_to:=case when a.direction='proposer_to_partner' then v_trade.partner_team_id else v_trade.proposer_team_id end;
    update public.league_future_picks set owner_team_id=v_to,updated_at=now() where id=a.pick_id and status='active';
  end loop;
  -- Bid dollars.
  for a in select * from public.league_trade_assets where trade_id=p_trade_id and asset_type='bid_dollars' order by id loop
    v_from:=case when a.direction='proposer_to_partner' then v_trade.proposer_team_id else v_trade.partner_team_id end;
    v_to:=case when a.direction='proposer_to_partner' then v_trade.partner_team_id else v_trade.proposer_team_id end;
    update public.teams set remaining_budget=remaining_budget-a.bid_amount where id=v_from;
    update public.teams set remaining_budget=remaining_budget+a.bid_amount where id=v_to;
  end loop;

  update public.league_trades set status='approved',decided_at=now(),commissioner_team_id=v_commish,updated_at=now() where id=p_trade_id;
  select name into v_prop_name from public.teams where id=v_trade.proposer_team_id;
  select name into v_partner_name from public.teams where id=v_trade.partner_team_id;
  v_tx:=public._league_log_transaction(v_trade.season_id,'trade',v_trade.proposer_team_id,v_trade.partner_team_id,null,null,
    'Trade approved: '||v_prop_name||' ↔ '||v_partner_name,0,0,'league_trades',p_trade_id::text,'trade:'||p_trade_id::text,
    jsonb_build_object('trade_id',p_trade_id,'validation',v_validation,'assets',(select coalesce(jsonb_agg(to_jsonb(x) order by x.id),'[]'::jsonb) from public.league_trade_assets x where x.trade_id=p_trade_id)));
  return jsonb_build_object('ok',true,'status','approved','transaction_id',v_tx,'validation',v_validation);
end;
$$;
grant execute on function public.league_commish_trade_decision(text,text,uuid,boolean) to anon,authenticated;

-- ---------------------------------------------------------------------------
-- Contract extensions. Only traded 2yr->3yr or 3yr->4yr contracts are eligible,
-- only in the trade season, only before the commissioner extension deadline.
-- Cost is paid in bid dollars and new contract point value applies immediately.
-- ---------------------------------------------------------------------------
create or replace function public.league_owner_extend_contract(
  p_room_code text,p_team_id uuid,p_pin text,p_eligibility_id uuid
) returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_room public.rooms%rowtype; v_season public.league_seasons%rowtype; v_e public.league_contract_extension_eligibility%rowtype;
  v_c public.league_contracts%rowtype; v_r public.league_roster_entries%rowtype; v_deadline public.league_deadlines%rowtype;
  v_costrow public.league_extension_costs%rowtype; v_bid_cost integer; v_new_cap integer; v_used integer; v_team public.teams%rowtype; v_tx uuid;
begin
  select * into v_room from public.rooms where code=p_room_code;
  if v_room.id is null or not public._valid_team_pin(p_team_id,p_pin) then raise exception 'Team authorization failed.'; end if;
  select * into v_season from public.league_seasons where id=public._league_current_season_id(p_room_code);
  select * into v_e from public.league_contract_extension_eligibility where id=p_eligibility_id and season_id=v_season.id and team_id=p_team_id and status='eligible' for update;
  if v_e.id is null then raise exception 'That contract is not extension-eligible.'; end if;
  select * into v_deadline from public.league_deadlines where season_id=v_season.id and deadline_type='contract_extensions' and status='open' order by due_at desc limit 1;
  if v_deadline.id is null then raise exception 'Contract extensions are not currently open.'; end if;
  if v_deadline.auto_lock and now()>v_deadline.due_at then raise exception 'The contract-extension deadline is locked.'; end if;
  select * into v_c from public.league_contracts where id=v_e.contract_id and team_id=p_team_id and status='active' for update;
  if v_c.id is null then raise exception 'Active contract not found.'; end if;
  if not ((v_c.length_years=2 and v_e.eligible_to_years=3) or (v_c.length_years=3 and v_e.eligible_to_years=4)) then raise exception 'Invalid extension path.'; end if;
  select * into v_r from public.league_roster_entries where room_id=v_room.id and team_id=p_team_id and player_key=v_c.player_key and active=true;
  if v_r.id is null then raise exception 'Player is no longer on your roster.'; end if;
  select * into v_costrow from public.league_extension_costs where season_id=v_season.id and position=v_r.position;
  v_bid_cost:=case when v_e.eligible_to_years=3 then v_costrow.cost_2_to_3 else v_costrow.cost_3_to_4 end;
  if v_bid_cost is null then raise exception 'Extension cost is unavailable for this position.'; end if;
  v_new_cap:=case v_e.eligible_to_years when 3 then 25 when 4 then 45 end;
  select * into v_team from public.teams where id=p_team_id for update;
  if v_team.remaining_budget<v_bid_cost then raise exception 'Extension costs % bid dollars; you only have % remaining.',v_bid_cost,v_team.remaining_budget; end if;
  select coalesce(sum(cap_cost),0) into v_used from public.league_contracts where season_id=v_season.id and team_id=p_team_id and status='active' and id<>v_c.id;
  if v_used+v_new_cap>v_season.salary_cap_points then raise exception 'Extension would exceed the % point salary cap.',v_season.salary_cap_points; end if;
  update public.teams set remaining_budget=remaining_budget-v_bid_cost where id=p_team_id;
  update public.league_contracts set length_years=v_e.eligible_to_years,cap_cost=v_new_cap,end_year=start_year+v_e.eligible_to_years-1,source='trade_extension',updated_at=now() where id=v_c.id;
  update public.league_contract_extension_eligibility set status='exercised',exercised_at=now() where id=v_e.id;
  v_tx:=public._league_log_transaction(v_season.id,'contract_extended',p_team_id,null,v_c.player_key,v_c.player_name,
    v_c.player_name||' extended from '||v_c.length_years||' years to '||v_e.eligible_to_years||' years for '||v_bid_cost||' bid dollars',
    -v_bid_cost,v_new_cap-v_c.cap_cost,'league_contracts',v_c.id::text,null,
    jsonb_build_object('from_years',v_c.length_years,'to_years',v_e.eligible_to_years,'from_cap',v_c.cap_cost,'to_cap',v_new_cap,'bid_cost',v_bid_cost,'deadline_id',v_deadline.id,'trade_id',v_e.trade_id));
  return jsonb_build_object('ok',true,'player',v_c.player_name,'bid_cost',v_bid_cost,'new_length',v_e.eligible_to_years,'new_cap_cost',v_new_cap,'transaction_id',v_tx);
end;
$$;
grant execute on function public.league_owner_extend_contract(text,uuid,text,uuid) to anon,authenticated;

-- ---------------------------------------------------------------------------
-- Commissioner correction: preserves audit trail and can adjust bid dollars.
-- ---------------------------------------------------------------------------
create or replace function public.league_commish_correction(
  p_room_code text,p_commish_pin text,p_team_id uuid,p_bid_delta integer,p_description text,p_reverse_transaction_id uuid default null
) returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room public.rooms%rowtype; v_season uuid; v_team public.teams%rowtype; v_tx uuid;
begin
  select * into v_room from public.rooms where code=p_room_code;
  if v_room.id is null or not public._valid_commish_pin(v_room.id,p_commish_pin) then raise exception 'Commissioner authorization failed.'; end if;
  v_season:=public._league_current_season_id(p_room_code);
  if p_team_id is not null then
    select * into v_team from public.teams where id=p_team_id and room_id=v_room.id for update;
    if v_team.id is null then raise exception 'Team not found.'; end if;
    if v_team.remaining_budget+coalesce(p_bid_delta,0)<0 then raise exception 'Correction would make bid dollars negative.'; end if;
    update public.teams set remaining_budget=remaining_budget+coalesce(p_bid_delta,0) where id=p_team_id;
  end if;
  v_tx:=public._league_log_transaction(v_season,'commissioner_correction',p_team_id,null,null,null,trim(p_description),coalesce(p_bid_delta,0),0,'league_transactions',p_reverse_transaction_id::text,null,jsonb_build_object('reverses',p_reverse_transaction_id));
  if p_reverse_transaction_id is not null then
    update public.league_transactions set status='reversed',reversed_at=now(),reversed_by=v_tx where id=p_reverse_transaction_id and season_id=v_season and status<>'reversed';
  end if;
  return jsonb_build_object('ok',true,'transaction_id',v_tx);
end;
$$;
grant execute on function public.league_commish_correction(text,text,uuid,integer,text,uuid) to anon,authenticated;

-- ---------------------------------------------------------------------------
-- Replace contract-assignment RPCs to also populate the transaction ledger.
-- ---------------------------------------------------------------------------
create or replace function public.league_owner_upsert_contract(
  p_room_code text,p_team_id uuid,p_pin text,p_player_key text,p_length_years integer,p_deadline_id uuid
) returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_room public.rooms%rowtype; v_season uuid; v_season_year integer; v_cap integer; v_cost integer; v_used integer;
  v_player public.league_roster_entries%rowtype; v_deadline public.league_deadlines%rowtype; v_existing public.league_contracts%rowtype; v_id bigint; v_old_cost integer:=0;
begin
  select * into v_room from public.rooms where code=p_room_code;
  if v_room.id is null or not public._valid_team_pin(p_team_id,p_pin) then raise exception 'Team authorization failed.'; end if;
  v_season:=public._league_current_season_id(p_room_code);
  select season_year,salary_cap_points into v_season_year,v_cap from public.league_seasons where id=v_season;
  select * into v_deadline from public.league_deadlines where id=p_deadline_id and season_id=v_season and deadline_type='contracts' and status='open';
  if v_deadline.id is null then raise exception 'Contract assignments are not open.'; end if;
  if now()>v_deadline.due_at and v_deadline.auto_lock then raise exception 'The contract deadline is locked.'; end if;
  select * into v_player from public.league_roster_entries where room_id=v_room.id and team_id=p_team_id and player_key=p_player_key and active=true;
  if v_player.id is null then raise exception 'That player is not on your active roster.'; end if;
  select cap_cost into v_cost from public.contract_options where season_id=v_season and years=p_length_years and active=true;
  if v_cost is null then raise exception 'That contract length is not enabled.'; end if;
  select * into v_existing from public.league_contracts where season_id=v_season and player_key=p_player_key and status='active';
  if v_existing.id is not null and not(v_existing.team_id=p_team_id and v_existing.source='owner_assignment' and v_existing.start_year=v_season_year) then raise exception 'That player already has an active contract.'; end if;
  if v_existing.id is not null then v_old_cost:=v_existing.cap_cost; end if;
  select coalesce(sum(cap_cost),0) into v_used from public.league_contracts where season_id=v_season and team_id=p_team_id and status='active' and player_key<>p_player_key;
  if v_used+v_cost>v_cap then raise exception 'Contract would exceed the % point salary cap.',v_cap; end if;
  insert into public.league_contracts(season_id,team_id,player_key,player_name,start_year,end_year,length_years,cap_cost,status,source)
  values(v_season,p_team_id,v_player.player_key,v_player.player_name,v_season_year,v_season_year+p_length_years-1,p_length_years,v_cost,'active','owner_assignment')
  on conflict(season_id,player_key) do update set team_id=excluded.team_id,player_name=excluded.player_name,start_year=excluded.start_year,end_year=excluded.end_year,length_years=excluded.length_years,cap_cost=excluded.cap_cost,status='active',source='owner_assignment',updated_at=now()
  returning id into v_id;
  update public.league_deadline_team_status set status='pending',submitted_at=null,updated_at=now() where deadline_id=p_deadline_id and team_id=p_team_id;
  insert into public.league_audit_log(season_id,actor_team_id,action,entity_type,entity_id,details)
  values(v_season,p_team_id,'owner_assign_contract','league_contracts',v_id::text,jsonb_build_object('player_key',v_player.player_key,'player',v_player.player_name,'years',p_length_years,'cost',v_cost,'deadline_id',p_deadline_id));
  perform public._league_log_transaction(v_season,'contract_assigned',p_team_id,null,v_player.player_key,v_player.player_name,
    v_player.player_name||' assigned a '||p_length_years||'-year contract ('||v_cost||' pts)',0,v_cost-v_old_cost,'league_contracts',v_id::text,null,
    jsonb_build_object('years',p_length_years,'cap_cost',v_cost,'deadline_id',p_deadline_id));
  return jsonb_build_object('ok',true,'contract_id',v_id,'cap_used',v_used+v_cost,'cap_limit',v_cap,'year',1,'length_years',p_length_years);
end;
$$;
grant execute on function public.league_owner_upsert_contract(text,uuid,text,text,integer,uuid) to anon,authenticated;

create or replace function public.league_owner_remove_contract(
  p_room_code text,p_team_id uuid,p_pin text,p_contract_id bigint,p_deadline_id uuid
) returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room public.rooms%rowtype; v_season uuid; v_season_year integer; v_deadline public.league_deadlines%rowtype; v_contract public.league_contracts%rowtype;
begin
  select * into v_room from public.rooms where code=p_room_code;
  if v_room.id is null or not public._valid_team_pin(p_team_id,p_pin) then raise exception 'Team authorization failed.'; end if;
  v_season:=public._league_current_season_id(p_room_code); select season_year into v_season_year from public.league_seasons where id=v_season;
  select * into v_deadline from public.league_deadlines where id=p_deadline_id and season_id=v_season and deadline_type='contracts' and status='open';
  if v_deadline.id is null then raise exception 'Contract assignments are not open.'; end if;
  if now()>v_deadline.due_at and v_deadline.auto_lock then raise exception 'The contract deadline is locked.'; end if;
  select * into v_contract from public.league_contracts where id=p_contract_id and season_id=v_season and team_id=p_team_id and status='active';
  if v_contract.id is null then raise exception 'Contract assignment not found.'; end if;
  if v_contract.source<>'owner_assignment' or v_contract.start_year<>v_season_year then raise exception 'Only your new contract assignments can be removed.'; end if;
  delete from public.league_contracts where id=v_contract.id;
  update public.league_deadline_team_status set status='pending',submitted_at=null,updated_at=now() where deadline_id=p_deadline_id and team_id=p_team_id;
  insert into public.league_audit_log(season_id,actor_team_id,action,entity_type,entity_id,details)
  values(v_season,p_team_id,'owner_remove_contract','league_contracts',p_contract_id::text,jsonb_build_object('player_key',v_contract.player_key,'player',v_contract.player_name,'deadline_id',p_deadline_id));
  perform public._league_log_transaction(v_season,'contract_removed',p_team_id,null,v_contract.player_key,v_contract.player_name,
    v_contract.player_name||' new contract assignment removed',0,-v_contract.cap_cost,'league_contracts',p_contract_id::text,null,jsonb_build_object('deadline_id',p_deadline_id));
  return jsonb_build_object('ok',true);
end;
$$;
grant execute on function public.league_owner_remove_contract(text,uuid,text,bigint,uuid) to anon,authenticated;

create or replace function public.league_commish_upsert_contract(
  p_room_code text,p_commish_pin text,p_team_id uuid,p_player_name text,p_length_years integer,p_start_year integer
) returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room public.rooms%rowtype; v_season uuid; v_cost int; v_cap int; v_used int; v_key text; v_id bigint; v_old public.league_contracts%rowtype; v_old_cost int:=0;
begin
  select * into v_room from public.rooms where code=p_room_code;
  if v_room.id is null or not public._valid_commish_pin(v_room.id,p_commish_pin) then raise exception 'Commissioner authorization failed.'; end if;
  if not exists(select 1 from public.teams where id=p_team_id and room_id=v_room.id) then raise exception 'Team not found.'; end if;
  v_season:=public._league_current_season_id(p_room_code); v_key:=public._league_roster_key(p_player_name);
  select cap_cost into v_cost from public.contract_options where season_id=v_season and years=p_length_years and active;
  if v_cost is null then raise exception 'That contract length is not enabled.'; end if;
  select salary_cap_points into v_cap from public.league_seasons where id=v_season;
  select * into v_old from public.league_contracts where season_id=v_season and player_key=v_key and status='active'; if v_old.id is not null then v_old_cost:=v_old.cap_cost; end if;
  select coalesce(sum(cap_cost),0) into v_used from public.league_contracts where season_id=v_season and team_id=p_team_id and status='active' and player_key<>v_key;
  if v_used+v_cost>v_cap then raise exception 'Contract would exceed the % point salary cap.',v_cap; end if;
  insert into public.league_contracts(season_id,team_id,player_key,player_name,start_year,end_year,length_years,cap_cost,status,source)
  values(v_season,p_team_id,v_key,trim(p_player_name),p_start_year,p_start_year+p_length_years-1,p_length_years,v_cost,'active','commissioner')
  on conflict(season_id,player_key) do update set team_id=excluded.team_id,player_name=excluded.player_name,start_year=excluded.start_year,end_year=excluded.end_year,length_years=excluded.length_years,cap_cost=excluded.cap_cost,status='active',source='commissioner',updated_at=now()
  returning id into v_id;
  insert into public.league_audit_log(season_id,action,entity_type,entity_id,details) values(v_season,'upsert_contract','league_contracts',v_id::text,jsonb_build_object('team_id',p_team_id,'player',p_player_name,'years',p_length_years,'cost',v_cost));
  perform public._league_log_transaction(v_season,'contract_assigned',p_team_id,null,v_key,trim(p_player_name),trim(p_player_name)||' contract set by commissioner: '||p_length_years||' years • '||v_cost||' pts',0,v_cost-v_old_cost,'league_contracts',v_id::text,null,jsonb_build_object('years',p_length_years,'cap_cost',v_cost,'start_year',p_start_year));
  return jsonb_build_object('ok',true,'contract_id',v_id,'cap_used',v_used+v_cost,'cap_limit',v_cap);
end;
$$;
grant execute on function public.league_commish_upsert_contract(text,text,uuid,text,integer,integer) to anon,authenticated;

create or replace function public.league_commish_void_contract(
  p_room_code text,p_commish_pin text,p_contract_id bigint
) returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room public.rooms%rowtype; v_season uuid; v_c public.league_contracts%rowtype;
begin
  select * into v_room from public.rooms where code=p_room_code;
  if v_room.id is null or not public._valid_commish_pin(v_room.id,p_commish_pin) then raise exception 'Commissioner authorization failed.'; end if;
  v_season:=public._league_current_season_id(p_room_code);
  select * into v_c from public.league_contracts where id=p_contract_id and season_id=v_season and status='active' for update;
  if v_c.id is null then raise exception 'Active contract not found.'; end if;
  update public.league_contracts set status='void',updated_at=now() where id=p_contract_id;
  insert into public.league_audit_log(season_id,action,entity_type,entity_id) values(v_season,'void_contract','league_contracts',p_contract_id::text);
  perform public._league_log_transaction(v_season,'contract_voided',v_c.team_id,null,v_c.player_key,v_c.player_name,v_c.player_name||' contract voided by commissioner',0,-v_c.cap_cost,'league_contracts',p_contract_id::text,null,'{}'::jsonb);
  return jsonb_build_object('ok',true);
end;
$$;
grant execute on function public.league_commish_void_contract(text,text,bigint) to anon,authenticated;

-- Add extension-deadline option as an explicit configurable rule label.
with s as (select id from public.league_seasons where id=public._league_current_season_id('GLSK26'))
insert into public.league_rule_settings(season_id,rule_key,category,label,boolean_value,sort_order,locked)
select id,'trade_extension_current_season','Contracts','Traded contracts may be extended only in the trade season',true,25,false from s
on conflict(season_id,rule_key) do nothing;


-- Refresh the extension-cost reference from the current season's completed Auction sales.
create or replace function public.league_commish_refresh_extension_costs(
  p_room_code text,p_commish_pin text
) returns jsonb
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room public.rooms%rowtype; v_season uuid;
begin
  select * into v_room from public.rooms where code=p_room_code;
  if v_room.id is null or not public._valid_commish_pin(v_room.id,p_commish_pin) then raise exception 'Commissioner authorization failed.'; end if;
  v_season:=public._league_current_season_id(p_room_code);
  with ranked as (
    select p.position,sa.price,row_number() over(partition by p.position order by sa.price desc,sa.sold_at asc) rn
    from public.sales sa join public.players p on p.id=sa.player_id
    where sa.room_id=v_room.id and sa.undone=false and p.position in ('QB','RB','WR','TE')
  ), top3 as (
    select position,max(price) filter(where rn=1) b1,max(price) filter(where rn=2) b2,max(price) filter(where rn=3) b3,
           avg(price::numeric) filter(where rn<=3) avg_bid,count(*) filter(where rn<=3) cnt
    from ranked group by position
  )
  insert into public.league_extension_costs(season_id,position,top_bid_1,top_bid_2,top_bid_3,average_bid,cost_2_to_3,cost_3_to_4,calculated_at)
  select v_season,position,b1,b2,b3,round(avg_bid,2),case when cnt=3 then round(avg_bid*0.25)::int end,
         case when cnt=3 then round(avg_bid*0.40)::int end,now() from top3
  on conflict(season_id,position) do update set top_bid_1=excluded.top_bid_1,top_bid_2=excluded.top_bid_2,top_bid_3=excluded.top_bid_3,
    average_bid=excluded.average_bid,cost_2_to_3=excluded.cost_2_to_3,cost_3_to_4=excluded.cost_3_to_4,calculated_at=now();
  return jsonb_build_object('ok',true);
end;
$$;
grant execute on function public.league_commish_refresh_extension_costs(text,text) to anon,authenticated;

-- Keep draft-room results in the permanent transaction ledger automatically.
create or replace function public._league_tx_from_sale() returns trigger
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_season uuid; v_name text; v_key text; v_pos text;
begin
  v_season:=(select ls.id from public.league_seasons ls where ls.room_id=new.room_id and ls.is_current order by season_year desc limit 1);
  if v_season is null then return new; end if;
  select name,public._league_roster_key(name),position into v_name,v_key,v_pos from public.players where id=new.player_id;
  if tg_op='INSERT' then
    perform public._league_log_transaction(v_season,'auction',new.team_id,null,v_key,v_name,v_name||' won in Free Agent Auction for '||new.price||' bid dollars',-new.price,0,'sales',new.id::text,'auction:'||new.id::text,jsonb_build_object('price',new.price,'position',v_pos));
  elsif new.undone and not old.undone then
    update public.league_transactions set status='reversed',reversed_at=now() where season_id=v_season and external_key='auction:'||new.id::text and status<>'reversed';
  end if;
  return new;
end;
$$;
drop trigger if exists trg_league_tx_sale on public.sales;
create trigger trg_league_tx_sale after insert or update on public.sales for each row execute function public._league_tx_from_sale();

create or replace function public._league_tx_from_supp_pick() returns trigger
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_season uuid; v_name text; v_key text;
begin
  if tg_op='INSERT' then
    v_season:=(select ls.id from public.league_seasons ls where ls.room_id=new.room_id and ls.is_current order by season_year desc limit 1);
    if v_season is null then return new; end if;
    select name,public._league_roster_key(name) into v_name,v_key from public.supplemental_players where id=new.player_id;
    perform public._league_log_transaction(v_season,'supplemental',new.winner_team_id,null,v_key,v_name,
      v_name||' acquired in Supplemental Draft'||case when new.price>0 then ' for '||new.price||' bid dollars' else ' for free' end,
      -new.price,0,'supplemental_picks',new.id::text,'supplemental:'||new.id::text,jsonb_build_object('pick_no',new.pick_no,'round',new.round,'outcome',new.outcome,'price',new.price));
    return new;
  else
    v_season:=(select ls.id from public.league_seasons ls where ls.room_id=old.room_id and ls.is_current order by season_year desc limit 1);
    if v_season is null then return old; end if;
    update public.league_transactions set status='reversed',reversed_at=now() where season_id=v_season and external_key='supplemental:'||old.id::text and status<>'reversed';
    return old;
  end if;
end;
$$;
drop trigger if exists trg_league_tx_supp_pick on public.supplemental_picks;
create trigger trg_league_tx_supp_pick after insert or delete on public.supplemental_picks for each row execute function public._league_tx_from_supp_pick();

create or replace function public._league_tx_from_phase3_pick() returns trigger
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_season uuid; v_name text; v_key text;
begin
  if tg_op='INSERT' then
    v_season:=(select ls.id from public.league_seasons ls where ls.room_id=new.room_id and ls.is_current order by season_year desc limit 1);
    if v_season is null then return new; end if;
    select name,public._league_roster_key(name) into v_name,v_key from public.phase3_players where id=new.player_id;
    perform public._league_log_transaction(v_season,'phase3',new.team_id,null,v_key,v_name,v_name||' selected in Roster-Fill Snake Draft',0,0,'phase3_picks',new.id::text,'phase3:'||new.id::text,jsonb_build_object('pick_no',new.pick_no,'round',new.round));
    return new;
  else
    v_season:=(select ls.id from public.league_seasons ls where ls.room_id=old.room_id and ls.is_current order by season_year desc limit 1);
    if v_season is null then return old; end if;
    update public.league_transactions set status='reversed',reversed_at=now() where season_id=v_season and external_key='phase3:'||old.id::text and status<>'reversed';
    return old;
  end if;
end;
$$;
drop trigger if exists trg_league_tx_phase3_pick on public.phase3_picks;
create trigger trg_league_tx_phase3_pick after insert or delete on public.phase3_picks for each row execute function public._league_tx_from_phase3_pick();

create or replace function public._league_tx_from_rights_transfer() returns trigger
language plpgsql security definer set search_path=public,pg_temp as $$
declare v_season uuid; v_name text; v_key text;
begin
  v_season:=(select ls.id from public.league_seasons ls where ls.room_id=new.room_id and ls.is_current order by season_year desc limit 1);
  select name,public._league_roster_key(name) into v_name,v_key from public.players where id=new.player_id;
  perform public._league_log_transaction(v_season,'rookie_rights_transfer',new.to_team_id,new.from_team_id,v_key,v_name,
    v_name||' transferred to rookie-rights holder for '||new.price||' bid dollars',-new.price,0,'auction_rights_transfers',new.id::text,'rights-transfer:'||new.id::text,jsonb_build_object('price',new.price));
  return new;
end;
$$;
drop trigger if exists trg_league_tx_rights_transfer on public.auction_rights_transfers;
create trigger trg_league_tx_rights_transfer after insert on public.auction_rights_transfers for each row execute function public._league_tx_from_rights_transfer();

-- Realtime updates for the new league ledgers.
do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='league_transactions') then alter publication supabase_realtime add table public.league_transactions; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='league_future_picks') then alter publication supabase_realtime add table public.league_future_picks; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='league_rookie_rights') then alter publication supabase_realtime add table public.league_rookie_rights; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='league_trades') then alter publication supabase_realtime add table public.league_trades; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='league_trade_assets') then alter publication supabase_realtime add table public.league_trade_assets; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='league_contract_extension_eligibility') then alter publication supabase_realtime add table public.league_contract_extension_eligibility; end if;
end $$;

commit;

-- Sanity check.
select
  ls.season_year,
  (select count(*) from public.league_future_picks fp where fp.room_id=ls.room_id and fp.draft_year=ls.season_year+1 and fp.status='active') as next_year_pick_assets,
  (select count(*) from public.league_rookie_rights rr where rr.room_id=ls.room_id and rr.status='active') as active_rookie_rights,
  (select count(*) from public.league_extension_costs ec where ec.season_id=ls.id and ec.cost_2_to_3 is not null) as extension_positions,
  (select count(*) from public.league_transactions tx where tx.season_id=ls.id) as transaction_rows
from public.league_seasons ls
join public.rooms r on r.id=ls.room_id
where r.code='GLSK26' and ls.is_current;
