-- GREAT LAKE STATE KEEPERS — SHARED LIVE ROSTER / "MY TEAM"
-- Version 11. Safe migration.
-- Adds one canonical roster table used by Auction, Supplemental and Phase 3.
-- Seeds it from the current Phase 3 roster snapshot, then keeps it synchronized
-- automatically when Auction/Supplemental/Phase 3 results are added, transferred,
-- undone or reset.
--
-- Does NOT alter team PINs, bid balances, draft orders, timers or current draft state.
-- Run in Supabase SQL Editor using "Run without RLS".

begin;

create or replace function public._league_roster_key(p_name text)
returns text
language sql
immutable
as $$
  select lower(regexp_replace(coalesce(p_name,''), '[^a-zA-Z0-9]+', '', 'g'));
$$;

create table if not exists public.league_roster_entries (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  team_id uuid not null references public.teams(id),
  player_key text not null,
  player_name text not null,
  nfl_team text,
  position text,
  acquisition_type text not null default 'current_roster'
    check(acquisition_type in ('current_roster','contract','rookie','auction','supplemental','rights_claim','phase3','manual')),
  acquisition_price integer,
  source_key text,
  active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(room_id,player_key)
);

create index if not exists league_roster_team_idx
  on public.league_roster_entries(room_id,team_id,active);

alter table public.league_roster_entries enable row level security;
drop policy if exists "public read league roster" on public.league_roster_entries;
create policy "public read league roster"
  on public.league_roster_entries for select to anon,authenticated using(true);
grant select on public.league_roster_entries to anon,authenticated;
revoke insert,update,delete on public.league_roster_entries from anon,authenticated;

-- Seed the canonical roster from the authoritative pre-Phase-3/current roster snapshot.
insert into public.league_roster_entries(
  room_id,team_id,player_key,player_name,nfl_team,position,acquisition_type,source_key,active
)
select re.room_id,re.team_id,public._league_roster_key(re.player_name),
       re.player_name,re.nfl_team,re.position,
       case when re.source='phase3' then 'phase3' else 'current_roster' end,
       case when re.phase3_pick_id is not null then 'phase3:'||re.phase3_pick_id::text else 'snapshot:'||re.id::text end,
       true
from public.phase3_roster_entries re
where re.room_id=(select id from public.rooms where code='GLSK26')
on conflict(room_id,player_key) do update
set team_id=excluded.team_id,
    player_name=excluded.player_name,
    nfl_team=excluded.nfl_team,
    position=excluded.position,
    active=true,
    updated_at=now();

-- Replay known Auction provenance/ownership over the snapshot.
insert into public.league_roster_entries(
  room_id,team_id,player_key,player_name,nfl_team,position,acquisition_type,acquisition_price,source_key,active
)
select s.room_id,s.team_id,public._league_roster_key(p.name),p.name,p.nfl_team,p.position,
       'auction',s.price,'auction:'||s.id::text,true
from public.sales s
join public.players p on p.id=s.player_id
where s.room_id=(select id from public.rooms where code='GLSK26')
  and s.undone=false
on conflict(room_id,player_key) do update
set team_id=excluded.team_id,
    player_name=excluded.player_name,
    nfl_team=excluded.nfl_team,
    position=excluded.position,
    acquisition_type='auction',
    acquisition_price=excluded.acquisition_price,
    source_key=excluded.source_key,
    active=true,
    updated_at=now();

-- Replay known Supplemental provenance/ownership.
insert into public.league_roster_entries(
  room_id,team_id,player_key,player_name,nfl_team,position,acquisition_type,acquisition_price,source_key,active
)
select pk.room_id,pk.winner_team_id,public._league_roster_key(p.name),p.name,p.nfl_team,p.position,
       'supplemental',pk.price,'supplemental:'||pk.id::text,true
from public.supplemental_picks pk
join public.supplemental_players p on p.id=pk.player_id
where pk.room_id=(select id from public.rooms where code='GLSK26')
on conflict(room_id,player_key) do update
set team_id=excluded.team_id,
    player_name=excluded.player_name,
    nfl_team=excluded.nfl_team,
    position=excluded.position,
    acquisition_type='supplemental',
    acquisition_price=excluded.acquisition_price,
    source_key=excluded.source_key,
    active=true,
    updated_at=now();

-- Replay any Phase 3 picks already made.
insert into public.league_roster_entries(
  room_id,team_id,player_key,player_name,nfl_team,position,acquisition_type,source_key,active
)
select pk.room_id,pk.team_id,public._league_roster_key(p.name),p.name,p.nfl_team,p.position,
       'phase3','phase3:'||pk.id::text,true
from public.phase3_picks pk
join public.phase3_players p on p.id=pk.player_id
where pk.room_id=(select id from public.rooms where code='GLSK26')
on conflict(room_id,player_key) do update
set team_id=excluded.team_id,
    player_name=excluded.player_name,
    nfl_team=excluded.nfl_team,
    position=excluded.position,
    acquisition_type='phase3',
    acquisition_price=null,
    source_key=excluded.source_key,
    active=true,
    updated_at=now();

-- ----------------------------
-- Auction synchronization
-- ----------------------------
create or replace function public._sync_roster_from_sale()
returns trigger
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare v_player public.players%rowtype;
begin
  if tg_op='DELETE' then
    delete from public.league_roster_entries
      where room_id=old.room_id and source_key='auction:'||old.id::text;
    return old;
  end if;

  select * into v_player from public.players where id=new.player_id;

  if new.undone then
    delete from public.league_roster_entries
      where room_id=new.room_id and source_key='auction:'||new.id::text;
  else
    insert into public.league_roster_entries(
      room_id,team_id,player_key,player_name,nfl_team,position,acquisition_type,acquisition_price,source_key,active
    )
    values(new.room_id,new.team_id,public._league_roster_key(v_player.name),v_player.name,v_player.nfl_team,v_player.position,
           'auction',new.price,'auction:'||new.id::text,true)
    on conflict(room_id,player_key) do update
    set team_id=excluded.team_id,
        player_name=excluded.player_name,
        nfl_team=excluded.nfl_team,
        position=excluded.position,
        acquisition_type='auction',
        acquisition_price=excluded.acquisition_price,
        source_key=excluded.source_key,
        active=true,
        updated_at=now();
  end if;
  return new;
end;
$$;

drop trigger if exists trg_sync_roster_sale on public.sales;
create trigger trg_sync_roster_sale
after insert or update or delete on public.sales
for each row execute function public._sync_roster_from_sale();

-- ----------------------------
-- Supplemental synchronization
-- ----------------------------
create or replace function public._sync_roster_from_supp_pick()
returns trigger
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare v_player public.supplemental_players%rowtype;
begin
  if tg_op='DELETE' then
    delete from public.league_roster_entries
      where room_id=old.room_id and source_key='supplemental:'||old.id::text;
    return old;
  end if;

  select * into v_player from public.supplemental_players where id=new.player_id;

  insert into public.league_roster_entries(
    room_id,team_id,player_key,player_name,nfl_team,position,acquisition_type,acquisition_price,source_key,active
  )
  values(new.room_id,new.winner_team_id,public._league_roster_key(v_player.name),v_player.name,v_player.nfl_team,v_player.position,
         'supplemental',new.price,'supplemental:'||new.id::text,true)
  on conflict(room_id,player_key) do update
  set team_id=excluded.team_id,
      player_name=excluded.player_name,
      nfl_team=excluded.nfl_team,
      position=excluded.position,
      acquisition_type='supplemental',
      acquisition_price=excluded.acquisition_price,
      source_key=excluded.source_key,
      active=true,
      updated_at=now();

  return new;
end;
$$;

drop trigger if exists trg_sync_roster_supp_pick on public.supplemental_picks;
create trigger trg_sync_roster_supp_pick
after insert or update or delete on public.supplemental_picks
for each row execute function public._sync_roster_from_supp_pick();

-- ----------------------------
-- Phase 3 synchronization
-- ----------------------------
create or replace function public._sync_roster_from_phase3_pick()
returns trigger
language plpgsql
security definer
set search_path=public,pg_temp
as $$
declare v_player public.phase3_players%rowtype;
begin
  if tg_op='DELETE' then
    delete from public.league_roster_entries
      where room_id=old.room_id and source_key='phase3:'||old.id::text;
    return old;
  end if;

  select * into v_player from public.phase3_players where id=new.player_id;

  insert into public.league_roster_entries(
    room_id,team_id,player_key,player_name,nfl_team,position,acquisition_type,source_key,active
  )
  values(new.room_id,new.team_id,public._league_roster_key(v_player.name),v_player.name,v_player.nfl_team,v_player.position,
         'phase3','phase3:'||new.id::text,true)
  on conflict(room_id,player_key) do update
  set team_id=excluded.team_id,
      player_name=excluded.player_name,
      nfl_team=excluded.nfl_team,
      position=excluded.position,
      acquisition_type='phase3',
      acquisition_price=null,
      source_key=excluded.source_key,
      active=true,
      updated_at=now();

  return new;
end;
$$;

drop trigger if exists trg_sync_roster_phase3_pick on public.phase3_picks;
create trigger trg_sync_roster_phase3_pick
after insert or update or delete on public.phase3_picks
for each row execute function public._sync_roster_from_phase3_pick();

do $$
begin
  if not exists(
    select 1 from pg_publication_tables
    where pubname='supabase_realtime' and schemaname='public' and tablename='league_roster_entries'
  ) then
    alter publication supabase_realtime add table public.league_roster_entries;
  end if;
end $$;

commit;

-- Sanity check: current roster totals should match the Phase 3 roster snapshot.
select
  count(*) filter(where active) as active_roster_players,
  count(distinct team_id) filter(where active) as teams_with_rosters
from public.league_roster_entries
where room_id=(select id from public.rooms where code='GLSK26');
