-- GREAT LAKE STATE KEEPERS - PHASE 3 ROSTER-FILL SNAKE DRAFT
-- Version 10. Safe migration: does NOT reset or alter Phase 1 Auction, Phase 2 Supplemental,
-- team PINs, rookie-rights transfers, or bid-dollar balances.
-- 2026 Phase 2.5 is already complete; current roster counts are seeded from the Yahoo roster snapshot.
-- Run in Supabase SQL Editor using "Run without RLS".

begin;

create table if not exists public.phase3_settings (
  room_id uuid primary key references public.rooms(id) on delete cascade,
  status text not null default 'setup' check(status in ('setup','live','paused','complete')),
  pick_seconds integer not null default 30 check(pick_seconds between 5 and 600),
  current_turn_no integer not null default 1 check(current_turn_no > 0),
  pick_ends_at timestamptz,
  pause_remaining_seconds integer,
  max_roster_size integer not null default 18 check(max_roster_size between 1 and 100),
  updated_at timestamptz not null default now()
);

create table if not exists public.phase3_order (
  room_id uuid not null references public.rooms(id) on delete cascade,
  slot integer not null check(slot between 1 and 64),
  team_id uuid not null references public.teams(id),
  primary key(room_id,slot),
  unique(room_id,team_id)
);

create table if not exists public.phase3_roster_state (
  room_id uuid not null references public.rooms(id) on delete cascade,
  team_id uuid not null references public.teams(id),
  initial_count integer not null check(initial_count >= 0),
  roster_count integer not null check(roster_count >= 0),
  max_roster_size integer not null default 18 check(max_roster_size > 0),
  primary key(room_id,team_id)
);

create table if not exists public.phase3_players (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  source_player_id uuid references public.supplemental_players(id),
  yahoo_rank integer not null,
  name text not null,
  nfl_team text not null,
  position text not null check(position in ('QB','RB','WR','TE','K','DST')),
  pos_rank integer,
  bye integer,
  projection_stats jsonb not null default '{}'::jsonb,
  ranking_source text,
  projection_source text,
  status text not null default 'available' check(status in ('available','drafted')),
  drafted_team_id uuid references public.teams(id),
  drafted_turn_no integer,
  unique(room_id,yahoo_rank,name)
);

create table if not exists public.phase3_picks (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  pick_no integer not null,
  turn_no integer not null,
  round integer not null,
  team_id uuid not null references public.teams(id),
  player_id uuid not null references public.phase3_players(id),
  created_at timestamptz not null default now(),
  unique(room_id,pick_no),
  unique(room_id,turn_no)
);

create table if not exists public.phase3_roster_entries (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  team_id uuid not null references public.teams(id),
  player_name text not null,
  nfl_team text,
  position text,
  source text not null check(source in ('pre_phase3','phase3')),
  yahoo_pick integer,
  phase3_pick_id bigint references public.phase3_picks(id) on delete cascade,
  created_at timestamptz not null default now()
);

create index if not exists phase3_players_room_status_idx on public.phase3_players(room_id,status,yahoo_rank);
create index if not exists phase3_picks_room_pick_idx on public.phase3_picks(room_id,pick_no);
create index if not exists phase3_roster_entries_team_idx on public.phase3_roster_entries(room_id,team_id);

alter table public.phase3_settings enable row level security;
alter table public.phase3_order enable row level security;
alter table public.phase3_roster_state enable row level security;
alter table public.phase3_players enable row level security;
alter table public.phase3_picks enable row level security;
alter table public.phase3_roster_entries enable row level security;

drop policy if exists "public read phase3 settings" on public.phase3_settings;
drop policy if exists "public read phase3 order" on public.phase3_order;
drop policy if exists "public read phase3 roster state" on public.phase3_roster_state;
drop policy if exists "public read phase3 players" on public.phase3_players;
drop policy if exists "public read phase3 picks" on public.phase3_picks;
drop policy if exists "public read phase3 roster entries" on public.phase3_roster_entries;

create policy "public read phase3 settings" on public.phase3_settings for select to anon,authenticated using(true);
create policy "public read phase3 order" on public.phase3_order for select to anon,authenticated using(true);
create policy "public read phase3 roster state" on public.phase3_roster_state for select to anon,authenticated using(true);
create policy "public read phase3 players" on public.phase3_players for select to anon,authenticated using(true);
create policy "public read phase3 picks" on public.phase3_picks for select to anon,authenticated using(true);
create policy "public read phase3 roster entries" on public.phase3_roster_entries for select to anon,authenticated using(true);

grant select on public.phase3_settings,public.phase3_order,public.phase3_roster_state,public.phase3_players,public.phase3_picks,public.phase3_roster_entries to anon,authenticated;
revoke insert,update,delete on public.phase3_settings,public.phase3_order,public.phase3_roster_state,public.phase3_players,public.phase3_picks,public.phase3_roster_entries from anon,authenticated;

insert into public.phase3_settings(room_id,pick_seconds,current_turn_no,max_roster_size)
select id,30,1,18 from public.rooms where code='GLSK26'
on conflict(room_id) do update
set pick_seconds=30,max_roster_size=18,updated_at=now();

-- Same Round-1 order as Supplemental; snake direction reverses every round.
delete from public.phase3_order where room_id=(select id from public.rooms where code='GLSK26');
insert into public.phase3_order(room_id,slot,team_id)
select r.id,x.slot,t.id
from public.rooms r
join (values
 (1,'Klyde Frogs'),
 (2,'Slim Charles'),
 (3,'hugs not drugs'),
 (4,'The Real McCoy'),
 (5,'Suburban White Kid'),
 (6,'Weiss Tea & Lemonade'),
 (7,'kerwinning it'),
 (8,'7th Floor Crew'),
 (9,'Team Ramrod'),
 (10,'Reggie Kush'),
 (11,'MEGATRONS V2'),
 (12,'The Hebrew Hammer')
) as x(slot,team_name) on true
join public.teams t on t.room_id=r.id and t.name=x.team_name
where r.code='GLSK26';

-- Authoritative pre-Phase-3 roster counts from the 2026 Yahoo snapshot.
delete from public.phase3_roster_state where room_id=(select id from public.rooms where code='GLSK26');
insert into public.phase3_roster_state(room_id,team_id,initial_count,roster_count,max_roster_size)
select r.id,t.id,x.initial_count,x.initial_count,x.max_size
from public.rooms r
join (values
 ('Klyde Frogs',10,18),
 ('Slim Charles',16,18),
 ('hugs not drugs',12,18),
 ('The Real McCoy',11,18),
 ('Suburban White Kid',13,18),
 ('Weiss Tea & Lemonade',11,18),
 ('kerwinning it',9,18),
 ('7th Floor Crew',9,18),
 ('Team Ramrod',12,18),
 ('Reggie Kush',10,18),
 ('MEGATRONS V2',11,18),
 ('The Hebrew Hammer',10,18)
) as x(team_name,initial_count,max_size) on true
join public.teams t on t.room_id=r.id and t.name=x.team_name
where r.code='GLSK26';

-- Current rosters after Auction, Supplemental, and the already-completed 2026 Rookie Rights claim window.
delete from public.phase3_roster_entries where room_id=(select id from public.rooms where code='GLSK26');
insert into public.phase3_roster_entries(room_id,team_id,player_name,nfl_team,position,source,yahoo_pick)
select r.id,t.id,x.player_name,x.nfl_team,x.position,'pre_phase3',x.yahoo_pick
from public.rooms r
join (values
 ('Klyde Frogs','Matthew Golden','GB','WR',97),
 ('Klyde Frogs','Tucker Kraft','GB','TE',120),
 ('Klyde Frogs','Breece Hall','NYJ','RB',121),
 ('Klyde Frogs','DeVonta Smith','Phi','WR',144),
 ('Klyde Frogs','A.J. Brown','NE','WR',145),
 ('Klyde Frogs','Carnell Tate','Ten','WR',168),
 ('Klyde Frogs','Jeremiyah Love','Ari','RB',169),
 ('Klyde Frogs','Marvin Harrison Jr.','Ari','WR',192),
 ('Klyde Frogs','Luther Burden III','Chi','WR',193),
 ('Klyde Frogs','Kenneth Walker III','KC','RB',216),
 ('Slim Charles','Ollie Gordon II','Mia','RB',26),
 ('Slim Charles','Jacory Croskey-Merritt','Was','RB',47),
 ('Slim Charles','Dallas Goedert','Phi','TE',50),
 ('Slim Charles','Kyle Monangai','Chi','RB',71),
 ('Slim Charles','Brandon Aubrey','Dal','K',74),
 ('Slim Charles','Trevor Lawrence','Jax','QB',95),
 ('Slim Charles','Parker Washington','Jax','WR',98),
 ('Slim Charles','D''Andre Swift','Chi','RB',119),
 ('Slim Charles','George Pickens','Dal','WR',122),
 ('Slim Charles','Ja''Kobi Lane','Bal','WR',143),
 ('Slim Charles','Jadarian Price','Sea','RB',146),
 ('Slim Charles','Ricky Pearsall','SF','WR',167),
 ('Slim Charles','Jalen Hurts','Phi','QB',170),
 ('Slim Charles','Jonathon Brooks','Car','RB',191),
 ('Slim Charles','Chase Brown','Cin','RB',194),
 ('Slim Charles','Mike Evans','SF','WR',215),
 ('hugs not drugs','Mike Washington Jr.','LV','RB',75),
 ('hugs not drugs','Tank Bigsby','Phi','RB',94),
 ('hugs not drugs','Rams','LAR','DST',99),
 ('hugs not drugs','Joe Burrow','Cin','QB',118),
 ('hugs not drugs','Colston Loveland','Chi','TE',123),
 ('hugs not drugs','Saquon Barkley','Phi','RB',142),
 ('hugs not drugs','De''Zhaun Stribling','SF','WR',147),
 ('hugs not drugs','Kenyon Sadiq','NYJ','TE',166),
 ('hugs not drugs','Brian Thomas Jr.','Jax','WR',171),
 ('hugs not drugs','Ashton Jeanty','LV','RB',190),
 ('hugs not drugs','Amon-Ra St. Brown','Det','WR',195),
 ('hugs not drugs','Derrick Henry','Bal','RB',214),
 ('The Real McCoy','Dak Prescott','Dal','QB',93),
 ('The Real McCoy','Sam LaPorta','Det','TE',100),
 ('The Real McCoy','Bhayshul Tuten','Jax','RB',117),
 ('The Real McCoy','Jaylen Waddle','Den','WR',124),
 ('The Real McCoy','Zay Flowers','Bal','WR',141),
 ('The Real McCoy','Fernando Mendoza','LV','QB',148),
 ('The Real McCoy','Makai Lemon','Phi','WR',165),
 ('The Real McCoy','Malik Nabers','NYG','WR',172),
 ('The Real McCoy','Bucky Irving','TB','RB',189),
 ('The Real McCoy','Bijan Robinson','Atl','RB',196),
 ('The Real McCoy','CeeDee Lamb','Dal','WR',213),
 ('Suburban White Kid','RJ Harvey','Den','RB',68),
 ('Suburban White Kid','Jakobi Meyers','Jax','WR',77),
 ('Suburban White Kid','Rico Dowdle','Pit','RB',92),
 ('Suburban White Kid','Rachaad White','Was','RB',101),
 ('Suburban White Kid','Quinshon Judkins','Cle','RB',116),
 ('Suburban White Kid','Davante Adams','LAR','WR',125),
 ('Suburban White Kid','Christian Watson','GB','WR',140),
 ('Suburban White Kid','Javonte Williams','Dal','RB',149),
 ('Suburban White Kid','Omar Cooper Jr.','NYJ','WR',164),
 ('Suburban White Kid','KC Concepcion','Cle','WR',173),
 ('Suburban White Kid','TreVeyon Henderson','NE','RB',188),
 ('Suburban White Kid','Ja''Marr Chase','Cin','WR',197),
 ('Suburban White Kid','Chris Olave','NO','WR',212),
 ('Weiss Tea & Lemonade','Tre'' Harris','LAC','WR',91),
 ('Weiss Tea & Lemonade','Cam Ward','Ten','QB',102),
 ('Weiss Tea & Lemonade','Caleb Williams','Chi','QB',115),
 ('Weiss Tea & Lemonade','Blake Corum','LAR','RB',126),
 ('Weiss Tea & Lemonade','Kyren Williams','LAR','RB',139),
 ('Weiss Tea & Lemonade','Jaxon Smith-Njigba','Sea','WR',150),
 ('Weiss Tea & Lemonade','Germie Bernard','Pit','WR',163),
 ('Weiss Tea & Lemonade','Jonah Coleman','Den','RB',174),
 ('Weiss Tea & Lemonade','Rashee Rice','KC','WR',187),
 ('Weiss Tea & Lemonade','Tee Higgins','Cin','WR',198),
 ('Weiss Tea & Lemonade','Courtland Sutton','Den','WR',211),
 ('kerwinning it','Travis Hunter','Jax','WR',114),
 ('kerwinning it','Rome Odunze','Chi','WR',127),
 ('kerwinning it','Cam Skattebo','NYG','RB',138),
 ('kerwinning it','Jahmyr Gibbs','Det','RB',151),
 ('kerwinning it','Eli Raridon','NE','TE',162),
 ('kerwinning it','Jordyn Tyson','NO','WR',175),
 ('kerwinning it','Jameson Williams','Det','WR',186),
 ('kerwinning it','Jayden Daniels','Was','QB',199),
 ('kerwinning it','Drake London','Atl','WR',210),
 ('7th Floor Crew','Jaxson Dart','NYG','QB',113),
 ('7th Floor Crew','Patrick Mahomes','KC','QB',128),
 ('7th Floor Crew','Michael Wilson','Ari','WR',137),
 ('7th Floor Crew','Nico Collins','Hou','WR',152),
 ('7th Floor Crew','Omarion Hampton','LAC','RB',161),
 ('7th Floor Crew','Zachariah Branch','Atl','WR',176),
 ('7th Floor Crew','Kaelon Black','SF','RB',185),
 ('7th Floor Crew','Brock Bowers','LV','TE',200),
 ('7th Floor Crew','George Kittle','SF','TE',209),
 ('Team Ramrod','Jordan Mason','Min','RB',81),
 ('Team Ramrod','Chris Rodriguez Jr.','Jax','RB',88),
 ('Team Ramrod','Tony Pollard','Ten','RB',105),
 ('Team Ramrod','DK Metcalf','Pit','WR',112),
 ('Team Ramrod','Drake Maye','NE','QB',129),
 ('Team Ramrod','Travis Etienne Jr.','NO','RB',136),
 ('Team Ramrod','Garrett Wilson','NYJ','WR',153),
 ('Team Ramrod','Chris Bell','Mia','WR',160),
 ('Team Ramrod','Dont''e Thornton Jr.','LV','WR',177),
 ('Team Ramrod','Emeka Egbuka','TB','WR',184),
 ('Team Ramrod','Tetairoa McMillan','Car','WR',201),
 ('Team Ramrod','Christian McCaffrey','SF','RB',208),
 ('Reggie Kush','Justin Herbert','LAC','QB',106),
 ('Reggie Kush','Dylan Sampson','Cle','RB',111),
 ('Reggie Kush','Chris Godwin Jr.','TB','WR',130),
 ('Reggie Kush','David Montgomery','Hou','RB',135),
 ('Reggie Kush','Tyler Warren','Ind','TE',154),
 ('Reggie Kush','James Cook III','Buf','RB',159),
 ('Reggie Kush','Nicholas Singleton','Ten','RB',178),
 ('Reggie Kush','Denzel Boston','Cle','WR',183),
 ('Reggie Kush','Ladd McConkey','LAC','WR',202),
 ('Reggie Kush','Justin Jefferson','Min','WR',207),
 ('MEGATRONS V2','Cameron Dicker','LAC','K',86),
 ('MEGATRONS V2','Broncos','Den','DST',107),
 ('MEGATRONS V2','DJ Moore','Buf','WR',110),
 ('MEGATRONS V2','Josh Allen','Buf','QB',131),
 ('MEGATRONS V2','De''Von Achane','Mia','RB',134),
 ('MEGATRONS V2','Antonio Williams','Was','WR',155),
 ('MEGATRONS V2','Eli Stowers','Phi','TE',158),
 ('MEGATRONS V2','Trey McBride','Ari','TE',179),
 ('MEGATRONS V2','Terry McLaurin','Was','WR',182),
 ('MEGATRONS V2','Jonathan Taylor','Ind','RB',203),
 ('MEGATRONS V2','Josh Jacobs','GB','RB',206),
 ('The Hebrew Hammer','Dalton Kincaid','Buf','TE',108),
 ('The Hebrew Hammer','Woody Marks','Hou','RB',109),
 ('The Hebrew Hammer','Jayden Reed','GB','WR',132),
 ('The Hebrew Hammer','MarShawn Lloyd','GB','RB',133),
 ('The Hebrew Hammer','Jaylen Warren','Pit','RB',156),
 ('The Hebrew Hammer','Rhamondre Stevenson','NE','RB',157),
 ('The Hebrew Hammer','Puka Nacua','LAR','WR',180),
 ('The Hebrew Hammer','Cyrus Allen','KC','WR',181),
 ('The Hebrew Hammer','Emmett Johnson','KC','RB',204),
 ('The Hebrew Hammer','Lamar Jackson','Bal','QB',205)
) as x(team_name,player_name,nfl_team,position,yahoo_pick) on true
join public.teams t on t.room_id=r.id and t.name=x.team_name
where r.code='GLSK26';

-- Build Phase 3 player pool from the same Yahoo Half-PPR source used by Supplemental,
-- then remove every player already present on the current roster snapshot.
delete from public.phase3_players where room_id=(select id from public.rooms where code='GLSK26');
insert into public.phase3_players(
  room_id,source_player_id,yahoo_rank,name,nfl_team,position,pos_rank,bye,
  projection_stats,ranking_source,projection_source,status
)
select sp.room_id,sp.id,sp.yahoo_rank,sp.name,sp.nfl_team,sp.position,sp.pos_rank,sp.bye,
       sp.projection_stats,sp.ranking_source,sp.projection_source,'available'
from public.supplemental_players sp
where sp.room_id=(select id from public.rooms where code='GLSK26')
  and not exists (
    select 1 from public.phase3_roster_entries re
    where re.room_id=sp.room_id
      and regexp_replace(lower(re.player_name),'[^a-z0-9]','','g')
          = regexp_replace(lower(sp.name),'[^a-z0-9]','','g')
  );

-- If re-running this migration before Phase 3 starts, make sure the Phase 3 state is clean.
delete from public.phase3_picks where room_id=(select id from public.rooms where code='GLSK26');
update public.phase3_settings
set status='setup',current_turn_no=1,pick_ends_at=null,pause_remaining_seconds=null,updated_at=now()
where room_id=(select id from public.rooms where code='GLSK26');

-- ---------------------------------------------------------------------------
-- Phase 3 helper functions
-- ---------------------------------------------------------------------------
create or replace function public._phase3_team_for_turn(p_room_id uuid,p_turn_no integer)
returns uuid language plpgsql stable security definer set search_path=public,pg_temp as $$
declare v_round integer; v_pos integer; v_slot integer; v_team uuid;
begin
  v_round := ((p_turn_no-1)/12)+1;
  v_pos := ((p_turn_no-1)%12)+1;
  v_slot := case when mod(v_round,2)=1 then v_pos else 13-v_pos end;
  select team_id into v_team from public.phase3_order where room_id=p_room_id and slot=v_slot;
  return v_team;
end; $$;

create or replace function public._phase3_next_eligible_turn(p_room_id uuid,p_start_turn integer)
returns integer language plpgsql stable security definer set search_path=public,pg_temp as $$
declare v_turn integer := greatest(1,p_start_turn); v_team uuid; v_rs public.phase3_roster_state%rowtype; v_i integer := 0;
begin
  if not exists(select 1 from public.phase3_roster_state where room_id=p_room_id and roster_count < max_roster_size) then
    return null;
  end if;
  loop
    v_i := v_i + 1;
    if v_i > 10000 then return null; end if;
    v_team := public._phase3_team_for_turn(p_room_id,v_turn);
    select * into v_rs from public.phase3_roster_state where room_id=p_room_id and team_id=v_team;
    if v_rs.team_id is not null and v_rs.roster_count < v_rs.max_roster_size then return v_turn; end if;
    v_turn := v_turn + 1;
  end loop;
end; $$;

create or replace function public._phase3_advance(p_room_id uuid)
returns void language plpgsql security definer set search_path=public,pg_temp as $$
declare v_s public.phase3_settings%rowtype; v_next integer;
begin
  select * into v_s from public.phase3_settings where room_id=p_room_id for update;
  if not exists(select 1 from public.phase3_roster_state where room_id=p_room_id and roster_count < max_roster_size) then
    update public.phase3_settings
      set status='complete',pick_ends_at=null,pause_remaining_seconds=null,updated_at=now()
      where room_id=p_room_id;
    return;
  end if;
  v_next := public._phase3_next_eligible_turn(p_room_id,v_s.current_turn_no+1);
  if v_next is null then
    update public.phase3_settings set status='complete',pick_ends_at=null,pause_remaining_seconds=null,updated_at=now() where room_id=p_room_id;
  else
    update public.phase3_settings
      set current_turn_no=v_next,
          pick_ends_at=case when status='live' then now()+make_interval(secs=>pick_seconds) else null end,
          pause_remaining_seconds=null,
          updated_at=now()
      where room_id=p_room_id;
  end if;
end; $$;

create or replace function public._phase3_select(
  p_room_id uuid,p_team_id uuid,p_player_id uuid,p_commish_override boolean default false
) returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare
  v_s public.phase3_settings%rowtype;
  v_expected uuid;
  v_rs public.phase3_roster_state%rowtype;
  v_p public.phase3_players%rowtype;
  v_pick_no integer;
  v_round integer;
  v_pick_id bigint;
begin
  select * into v_s from public.phase3_settings where room_id=p_room_id for update;
  if v_s.status<>'live' then return jsonb_build_object('ok',false,'error','Phase 3 draft is not live.'); end if;

  v_expected := public._phase3_team_for_turn(p_room_id,v_s.current_turn_no);
  if not p_commish_override and p_team_id<>v_expected then
    return jsonb_build_object('ok',false,'error','It is not your turn to pick.');
  end if;
  if p_commish_override then p_team_id := v_expected; end if;

  select * into v_rs from public.phase3_roster_state where room_id=p_room_id and team_id=p_team_id for update;
  if v_rs.team_id is null then return jsonb_build_object('ok',false,'error','Roster state was not found.'); end if;
  if v_rs.roster_count>=v_rs.max_roster_size then
    return jsonb_build_object('ok',false,'error','That team already has a full roster.');
  end if;

  select * into v_p from public.phase3_players where room_id=p_room_id and id=p_player_id for update;
  if v_p.id is null or v_p.status<>'available' then
    return jsonb_build_object('ok',false,'error','That player is no longer available.');
  end if;

  select coalesce(max(pick_no),0)+1 into v_pick_no from public.phase3_picks where room_id=p_room_id;
  v_round := ((v_s.current_turn_no-1)/12)+1;

  insert into public.phase3_picks(room_id,pick_no,turn_no,round,team_id,player_id)
  values(p_room_id,v_pick_no,v_s.current_turn_no,v_round,p_team_id,p_player_id)
  returning id into v_pick_id;

  update public.phase3_players
    set status='drafted',drafted_team_id=p_team_id,drafted_turn_no=v_s.current_turn_no
    where id=p_player_id;

  update public.phase3_roster_state
    set roster_count=roster_count+1
    where room_id=p_room_id and team_id=p_team_id;

  insert into public.phase3_roster_entries(room_id,team_id,player_name,nfl_team,position,source,phase3_pick_id)
  values(p_room_id,p_team_id,v_p.name,v_p.nfl_team,v_p.position,'phase3',v_pick_id);

  perform public._phase3_advance(p_room_id);
  return jsonb_build_object('ok',true,'player',v_p.name,'pick_no',v_pick_no,'team_id',p_team_id);
end; $$;

-- ---------------------------------------------------------------------------
-- Team + Commissioner RPCs
-- ---------------------------------------------------------------------------
create or replace function public.phase3_select_player(p_room_code text,p_team_id uuid,p_pin text,p_player_id uuid)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room uuid;
begin
  select id into v_room from public.rooms where code=p_room_code;
  if v_room is null then return jsonb_build_object('ok',false,'error','Room not found.'); end if;
  if not exists(select 1 from public.teams where id=p_team_id and room_id=v_room)
     or not public._valid_team_pin(p_team_id,p_pin) then
    return jsonb_build_object('ok',false,'error','Team authorization failed.');
  end if;
  return public._phase3_select(v_room,p_team_id,p_player_id,false);
end; $$;

create or replace function public.phase3_commish_select_player(p_room_code text,p_commish_pin text,p_player_id uuid)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room uuid; v_team uuid;
begin
  select id into v_room from public.rooms where code=p_room_code;
  if v_room is null or not public._valid_commish_pin(v_room,p_commish_pin) then
    return jsonb_build_object('ok',false,'error','Commissioner authorization failed.');
  end if;
  select public._phase3_team_for_turn(v_room,current_turn_no) into v_team
  from public.phase3_settings where room_id=v_room;
  return public._phase3_select(v_room,v_team,p_player_id,true);
end; $$;

create or replace function public.phase3_commish_start(p_room_code text,p_commish_pin text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room uuid; v_s public.phase3_settings%rowtype; v_turn integer;
begin
  select id into v_room from public.rooms where code=p_room_code;
  if v_room is null or not public._valid_commish_pin(v_room,p_commish_pin) then
    return jsonb_build_object('ok',false,'error','Commissioner authorization failed.');
  end if;
  select * into v_s from public.phase3_settings where room_id=v_room for update;
  if v_s.status='complete' then return jsonb_build_object('ok',false,'error','Phase 3 is complete. Reset it before starting again.'); end if;
  v_turn := public._phase3_next_eligible_turn(v_room,v_s.current_turn_no);
  if v_turn is null then
    update public.phase3_settings set status='complete',pick_ends_at=null,updated_at=now() where room_id=v_room;
    return jsonb_build_object('ok',true,'complete',true);
  end if;
  update public.phase3_settings
    set status='live',current_turn_no=v_turn,pick_ends_at=now()+make_interval(secs=>pick_seconds),
        pause_remaining_seconds=null,updated_at=now()
    where room_id=v_room;
  return jsonb_build_object('ok',true);
end; $$;

create or replace function public.phase3_commish_pause(p_room_code text,p_commish_pin text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room uuid; v_s public.phase3_settings%rowtype; v_rem integer;
begin
  select id into v_room from public.rooms where code=p_room_code;
  if v_room is null or not public._valid_commish_pin(v_room,p_commish_pin) then return jsonb_build_object('ok',false,'error','Commissioner authorization failed.'); end if;
  select * into v_s from public.phase3_settings where room_id=v_room for update;
  if v_s.status<>'live' then return jsonb_build_object('ok',false,'error','Phase 3 is not live.'); end if;
  v_rem := greatest(0,ceil(extract(epoch from (v_s.pick_ends_at-now())))::integer);
  update public.phase3_settings set status='paused',pause_remaining_seconds=v_rem,pick_ends_at=null,updated_at=now() where room_id=v_room;
  return jsonb_build_object('ok',true);
end; $$;

create or replace function public.phase3_commish_resume(p_room_code text,p_commish_pin text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room uuid; v_s public.phase3_settings%rowtype; v_rem integer;
begin
  select id into v_room from public.rooms where code=p_room_code;
  if v_room is null or not public._valid_commish_pin(v_room,p_commish_pin) then return jsonb_build_object('ok',false,'error','Commissioner authorization failed.'); end if;
  select * into v_s from public.phase3_settings where room_id=v_room for update;
  if v_s.status<>'paused' then return jsonb_build_object('ok',false,'error','Phase 3 is not paused.'); end if;
  v_rem := greatest(1,coalesce(v_s.pause_remaining_seconds,v_s.pick_seconds));
  update public.phase3_settings set status='live',pick_ends_at=now()+make_interval(secs=>v_rem),pause_remaining_seconds=null,updated_at=now() where room_id=v_room;
  return jsonb_build_object('ok',true);
end; $$;

create or replace function public.phase3_commish_add_time(p_room_code text,p_commish_pin text,p_seconds integer default 30)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room uuid; v_s public.phase3_settings%rowtype; v_add integer;
begin
  select id into v_room from public.rooms where code=p_room_code;
  if v_room is null or not public._valid_commish_pin(v_room,p_commish_pin) then return jsonb_build_object('ok',false,'error','Commissioner authorization failed.'); end if;
  v_add:=greatest(1,least(coalesce(p_seconds,30),600));
  select * into v_s from public.phase3_settings where room_id=v_room for update;
  if v_s.status='paused' then
    update public.phase3_settings set pause_remaining_seconds=coalesce(pause_remaining_seconds,0)+v_add,updated_at=now() where room_id=v_room;
  elsif v_s.status='live' then
    update public.phase3_settings set pick_ends_at=coalesce(pick_ends_at,now())+make_interval(secs=>v_add),updated_at=now() where room_id=v_room;
  else
    return jsonb_build_object('ok',false,'error','Draft must be live or paused to add time.');
  end if;
  return jsonb_build_object('ok',true);
end; $$;

create or replace function public.phase3_commish_update_settings(p_room_code text,p_commish_pin text,p_pick_seconds integer)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room uuid;
begin
  select id into v_room from public.rooms where code=p_room_code;
  if v_room is null or not public._valid_commish_pin(v_room,p_commish_pin) then return jsonb_build_object('ok',false,'error','Commissioner authorization failed.'); end if;
  if p_pick_seconds not between 5 and 600 then return jsonb_build_object('ok',false,'error','Pick clock must be between 5 and 600 seconds.'); end if;
  update public.phase3_settings set pick_seconds=p_pick_seconds,updated_at=now() where room_id=v_room;
  return jsonb_build_object('ok',true);
end; $$;

create or replace function public.phase3_commish_set_order(p_room_code text,p_commish_pin text,p_team_ids jsonb)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room uuid; v_count integer; v_distinct integer;
begin
  select id into v_room from public.rooms where code=p_room_code;
  if v_room is null or not public._valid_commish_pin(v_room,p_commish_pin) then return jsonb_build_object('ok',false,'error','Commissioner authorization failed.'); end if;
  if jsonb_typeof(p_team_ids)<>'array' or jsonb_array_length(p_team_ids)<>12 then return jsonb_build_object('ok',false,'error','Draft order must contain exactly 12 teams.'); end if;
  select count(*),count(distinct value) into v_count,v_distinct from jsonb_array_elements_text(p_team_ids);
  if v_count<>12 or v_distinct<>12 then return jsonb_build_object('ok',false,'error','Draft order contains duplicate or missing teams.'); end if;
  if exists(
    select 1 from jsonb_array_elements_text(p_team_ids) x
    where not exists(select 1 from public.teams t where t.room_id=v_room and t.id::text=x.value)
  ) then return jsonb_build_object('ok',false,'error','Draft order contains an invalid team.'); end if;
  delete from public.phase3_order where room_id=v_room;
  insert into public.phase3_order(room_id,slot,team_id)
  select v_room,ordinality,value::uuid from jsonb_array_elements_text(p_team_ids) with ordinality;
  return jsonb_build_object('ok',true);
end; $$;

create or replace function public.phase3_commish_skip_turn(p_room_code text,p_commish_pin text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room uuid; v_s public.phase3_settings%rowtype;
begin
  select id into v_room from public.rooms where code=p_room_code;
  if v_room is null or not public._valid_commish_pin(v_room,p_commish_pin) then return jsonb_build_object('ok',false,'error','Commissioner authorization failed.'); end if;
  select * into v_s from public.phase3_settings where room_id=v_room for update;
  if v_s.status not in ('live','paused') then return jsonb_build_object('ok',false,'error','Phase 3 must be live or paused.'); end if;
  perform public._phase3_advance(v_room);
  return jsonb_build_object('ok',true);
end; $$;

create or replace function public.phase3_finalize_if_expired(p_room_code text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room uuid; v_s public.phase3_settings%rowtype;
begin
  select id into v_room from public.rooms where code=p_room_code;
  if v_room is null then return jsonb_build_object('ok',false,'error','Room not found.'); end if;
  select * into v_s from public.phase3_settings where room_id=v_room for update;
  if v_s.status<>'live' or v_s.pick_ends_at is null or now()<v_s.pick_ends_at then
    return jsonb_build_object('ok',true,'finalized',false);
  end if;
  update public.phase3_settings
    set status='paused',pick_ends_at=null,pause_remaining_seconds=0,updated_at=now()
    where room_id=v_room;
  return jsonb_build_object('ok',true,'finalized',true,'expired_pick',true);
end; $$;

create or replace function public.phase3_commish_undo_last_pick(p_room_code text,p_commish_pin text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room uuid; v_pick public.phase3_picks%rowtype;
begin
  select id into v_room from public.rooms where code=p_room_code;
  if v_room is null or not public._valid_commish_pin(v_room,p_commish_pin) then return jsonb_build_object('ok',false,'error','Commissioner authorization failed.'); end if;
  select * into v_pick from public.phase3_picks where room_id=v_room order by pick_no desc limit 1 for update;
  if v_pick.id is null then return jsonb_build_object('ok',false,'error','There is no Phase 3 pick to undo.'); end if;

  delete from public.phase3_picks where id=v_pick.id;
  update public.phase3_players set status='available',drafted_team_id=null,drafted_turn_no=null where id=v_pick.player_id;
  update public.phase3_roster_state set roster_count=greatest(initial_count,roster_count-1) where room_id=v_room and team_id=v_pick.team_id;
  update public.phase3_settings
    set status='live',current_turn_no=v_pick.turn_no,pick_ends_at=now()+make_interval(secs=>pick_seconds),
        pause_remaining_seconds=null,updated_at=now()
    where room_id=v_room;
  return jsonb_build_object('ok',true,'pick_no',v_pick.pick_no,'turn_no',v_pick.turn_no);
end; $$;

create or replace function public.phase3_commish_reset(p_room_code text,p_commish_pin text)
returns jsonb language plpgsql security definer set search_path=public,pg_temp as $$
declare v_room uuid;
begin
  select id into v_room from public.rooms where code=p_room_code;
  if v_room is null or not public._valid_commish_pin(v_room,p_commish_pin) then return jsonb_build_object('ok',false,'error','Commissioner authorization failed.'); end if;

  delete from public.phase3_picks where room_id=v_room;
  update public.phase3_players set status='available',drafted_team_id=null,drafted_turn_no=null where room_id=v_room;
  update public.phase3_roster_state set roster_count=initial_count where room_id=v_room;
  update public.phase3_settings
    set status='setup',current_turn_no=1,pick_ends_at=null,pause_remaining_seconds=null,updated_at=now()
    where room_id=v_room;
  return jsonb_build_object('ok',true);
end; $$;

revoke all on function public._phase3_team_for_turn(uuid,integer) from public,anon,authenticated;
revoke all on function public._phase3_next_eligible_turn(uuid,integer) from public,anon,authenticated;
revoke all on function public._phase3_advance(uuid) from public,anon,authenticated;
revoke all on function public._phase3_select(uuid,uuid,uuid,boolean) from public,anon,authenticated;

grant execute on function public.phase3_select_player(text,uuid,text,uuid) to anon,authenticated;
grant execute on function public.phase3_commish_select_player(text,text,uuid) to anon,authenticated;
grant execute on function public.phase3_commish_start(text,text) to anon,authenticated;
grant execute on function public.phase3_commish_pause(text,text) to anon,authenticated;
grant execute on function public.phase3_commish_resume(text,text) to anon,authenticated;
grant execute on function public.phase3_commish_add_time(text,text,integer) to anon,authenticated;
grant execute on function public.phase3_commish_update_settings(text,text,integer) to anon,authenticated;
grant execute on function public.phase3_commish_set_order(text,text,jsonb) to anon,authenticated;
grant execute on function public.phase3_commish_skip_turn(text,text) to anon,authenticated;
grant execute on function public.phase3_finalize_if_expired(text) to anon,authenticated;
grant execute on function public.phase3_commish_undo_last_pick(text,text) to anon,authenticated;
grant execute on function public.phase3_commish_reset(text,text) to anon,authenticated;

do $$ begin
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='phase3_settings') then alter publication supabase_realtime add table public.phase3_settings; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='phase3_order') then alter publication supabase_realtime add table public.phase3_order; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='phase3_roster_state') then alter publication supabase_realtime add table public.phase3_roster_state; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='phase3_players') then alter publication supabase_realtime add table public.phase3_players; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='phase3_picks') then alter publication supabase_realtime add table public.phase3_picks; end if;
  if not exists(select 1 from pg_publication_tables where pubname='supabase_realtime' and schemaname='public' and tablename='phase3_roster_entries') then alter publication supabase_realtime add table public.phase3_roster_entries; end if;
end $$;

commit;

-- Sanity check. Expected: 12 order slots, 134 current rostered players, 82 open roster spots,
-- 30-second pick clock, and a Phase 3 player pool large enough to fill all open slots.
select
  s.status,
  s.current_turn_no,
  s.pick_seconds,
  s.max_roster_size,
  (select count(*) from public.phase3_order o where o.room_id=s.room_id) as order_slots,
  (select count(*) from public.phase3_roster_entries re where re.room_id=s.room_id and re.source='pre_phase3') as current_rostered_players,
  (select sum(max_roster_size-roster_count) from public.phase3_roster_state rs where rs.room_id=s.room_id) as open_roster_spots,
  (select count(*) from public.phase3_players p where p.room_id=s.room_id and p.status='available') as available_players
from public.phase3_settings s
join public.rooms r on r.id=s.room_id
where r.code='GLSK26';
