-- GREAT LAKE STATE KEEPERS — 2026 AUCTION DATABASE (FIXED v2)
-- Safe to run now BEFORE the auction begins. This resets only the GLSK auction objects.
-- The script is wrapped in a transaction: if anything fails, the reset/install rolls back.

begin;

create schema if not exists extensions;
create extension if not exists pgcrypto with schema extensions;

-- Clean up any partial installation from the earlier failed run.
drop table if exists public.sales cascade;
drop table if exists public.bids cascade;
drop table if exists public.room_secrets cascade;
drop table if exists public.team_secrets cascade;
drop table if exists public.players cascade;
drop table if exists public.teams cascade;
drop table if exists public.rooms cascade;
drop table if exists generated_credentials;

create table public.rooms (
  id uuid primary key default gen_random_uuid(),
  code text not null unique,
  name text not null,
  status text not null default 'setup' check (status in ('setup','live','paused','complete')),
  timer_seconds integer not null default 30 check (timer_seconds between 5 and 300),
  min_bid integer not null default 1 check (min_bid > 0),
  bid_increment integer not null default 1 check (bid_increment > 0),
  active_player_id uuid,
  active_bid integer not null default 0 check (active_bid >= 0),
  active_bidder_team_id uuid,
  auction_ends_at timestamptz,
  pause_remaining_seconds integer,
  sold_count integer not null default 0 check (sold_count >= 0),
  created_at timestamptz not null default now()
);

create table public.teams (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  name text not null,
  starting_budget integer not null check (starting_budget >= 0),
  remaining_budget integer not null check (remaining_budget >= 0),
  sort_order integer not null,
  unique(room_id, name),
  unique(room_id, sort_order)
);

create table public.team_secrets (
  team_id uuid primary key references public.teams(id) on delete cascade,
  pin_hash text not null
);

create table public.room_secrets (
  room_id uuid primary key references public.rooms(id) on delete cascade,
  commish_pin_hash text not null
);

create table public.players (
  id uuid primary key default gen_random_uuid(),
  room_id uuid not null references public.rooms(id) on delete cascade,
  rank integer not null,
  name text not null,
  nfl_team text not null,
  position text not null check (position in ('QB','RB','WR','TE')),
  note text,
  status text not null default 'queued' check (status in ('available','queued','active','sold')),
  queue_order integer,
  sold_team_id uuid references public.teams(id),
  sold_price integer,
  unique(room_id, rank)
);

alter table public.rooms
  add constraint rooms_active_player_fk foreign key (active_player_id) references public.players(id),
  add constraint rooms_active_bidder_fk foreign key (active_bidder_team_id) references public.teams(id);

create table public.bids (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  player_id uuid not null references public.players(id) on delete cascade,
  team_id uuid not null references public.teams(id) on delete cascade,
  amount integer not null check (amount > 0),
  created_at timestamptz not null default now()
);

create table public.sales (
  id bigint generated by default as identity primary key,
  room_id uuid not null references public.rooms(id) on delete cascade,
  player_id uuid not null references public.players(id),
  team_id uuid not null references public.teams(id),
  price integer not null check (price > 0),
  sold_at timestamptz not null default now(),
  undone boolean not null default false
);

create index bids_room_created_idx on public.bids(room_id, created_at desc);
create index players_room_status_idx on public.players(room_id, status, queue_order);
create index sales_room_sold_idx on public.sales(room_id, sold_at desc);

alter table public.rooms enable row level security;
alter table public.teams enable row level security;
alter table public.players enable row level security;
alter table public.bids enable row level security;
alter table public.sales enable row level security;
alter table public.team_secrets enable row level security;
alter table public.room_secrets enable row level security;

create policy "public read rooms" on public.rooms for select to anon, authenticated using (true);
create policy "public read teams" on public.teams for select to anon, authenticated using (true);
create policy "public read players" on public.players for select to anon, authenticated using (true);
create policy "public read bids" on public.bids for select to anon, authenticated using (true);
create policy "public read sales" on public.sales for select to anon, authenticated using (true);

revoke all on public.team_secrets from anon, authenticated;
revoke all on public.room_secrets from anon, authenticated;
revoke insert, update, delete on public.rooms, public.teams, public.players, public.bids, public.sales from anon, authenticated;

grant select on public.rooms, public.teams, public.players, public.bids, public.sales to anon, authenticated;

-- Seed room
insert into public.rooms (code, name, status, timer_seconds, min_bid, bid_increment)
values ('GLSK26', 'Great Lake State Keepers', 'setup', 30, 1, 1);

-- Revised starting budgets: exactly $1 removed from each Drafty total.
insert into public.teams (room_id, name, starting_budget, remaining_budget, sort_order)
select r.id, x.name, x.budget, x.budget, x.ord
from public.rooms r
cross join (values
  (1, 'Weiss Tea & Lemonade', 99),
  (2, 'The Real McCoy', 104),
  (3, 'Team Ramrod', 95),
  (4, 'Slim Charles', 96),
  (5, 'The Hebrew Hammer', 114),
  (6, 'MEGATRONS V2', 98),
  (7, 'Klyde Frogs', 137),
  (8, 'hugs not drugs', 91),
  (9, 'kerwinning it', 106),
  (10, 'Reggie Kush', 107),
  (11, 'Suburban White Kid', 99),
  (12, '7th Floor Crew', 100)
) as x(ord, name, budget)
where r.code = 'GLSK26';

-- Exact 40-player pool. The list is pre-queued in rank order.
insert into public.players (room_id, rank, name, nfl_team, position, note, status, queue_order)
select r.id, x.rank, x.name, x.nfl, x.pos, x.note, 'queued', x.rank
from public.rooms r
cross join (values
  (1, 'Jahmyr Gibbs', 'DET', 'RB', null),
  (2, 'Puka Nacua', 'LAR', 'WR', null),
  (3, 'Jaxon Smith-Njigba', 'SEA', 'WR', null),
  (4, 'James Cook III', 'BUF', 'RB', null),
  (5, 'Saquon Barkley', 'PHI', 'RB', null),
  (6, 'Omarion Hampton', 'LAC', 'RB', 'R — MEGATRONS V2'),
  (7, 'De''Von Achane', 'MIA', 'RB', null),
  (8, 'Nico Collins', 'HOU', 'WR', null),
  (9, 'George Pickens', 'DAL', 'WR', null),
  (10, 'AJ Brown', 'NE', 'WR', null),
  (11, 'DeVonta Smith', 'PHI', 'WR', null),
  (12, 'Kyren Williams', 'LAR', 'RB', null),
  (13, 'Javonte Williams', 'DAL', 'RB', null),
  (14, 'Breece Hall', 'NYJ', 'RB', null),
  (15, 'Zay Flowers', 'BAL', 'WR', null),
  (16, 'Jaylen Waddle', 'DEN', 'WR', null),
  (17, 'Josh Allen', 'BUF', 'QB', null),
  (18, 'Garrett Wilson', 'NYJ', 'WR', null),
  (19, 'Colston Loveland', 'CHI', 'TE', 'R — hugs not drugs'),
  (20, 'Travis Etienne Jr', 'NO', 'RB', null),
  (21, 'D''Andre Swift', 'CHI', 'RB', null),
  (22, 'DJ Moore', 'BUF', 'WR', null),
  (23, 'Tyler Warren', 'IND', 'TE', null),
  (24, 'Cam Skattebo', 'NYG', 'RB', 'R — kerwinning it'),
  (25, 'Rome Odunze', 'CHI', 'WR', null),
  (26, 'Christian Watson', 'GB', 'WR', null),
  (27, 'Parker Washington', 'JAX', 'WR', null),
  (28, 'Davante Adams', 'LAR', 'WR', null),
  (29, 'Quinshon Judkins', 'CLE', 'RB', 'R — Suburban White Kid'),
  (30, 'David Montgomery', 'DET', 'RB', null),
  (31, 'Bhayshul Tuten', 'JAX', 'RB', 'R — The Real McCoy'),
  (32, 'Drake Maye', 'NE', 'QB', null),
  (33, 'Rhamondre Stevenson', 'NE', 'RB', null),
  (34, 'Joe Burrow', 'CIN', 'QB', null),
  (35, 'Tucker Kraft', 'GB', 'TE', null),
  (36, 'Jaylen Warren', 'PIT', 'RB', null),
  (37, 'MarShawn Lloyd', 'GB', 'RB', null),
  (38, 'DK Metcalf', 'PIT', 'WR', null),
  (39, 'Tony Pollard', 'TEN', 'RB', null),
  (40, 'Chris Godwin Jr.', 'TB', 'WR', null)
) as x(rank, name, nfl, pos, note)
where r.code = 'GLSK26';

-- Generate 6-digit credentials without putting plaintext secrets in the repository.
create temp table generated_credentials (
  team_id uuid,
  label text not null,
  pin text not null
) on commit preserve rows;

insert into generated_credentials(team_id, label, pin)
select t.id, t.name, lpad((100000 + floor(random() * 900000))::int::text, 6, '0')
from public.teams t
join public.rooms r on r.id = t.room_id
where r.code = 'GLSK26'
order by t.sort_order;

insert into generated_credentials(team_id, label, pin)
select null, 'COMMISSIONER', lpad((100000 + floor(random() * 900000))::int::text, 6, '0');

insert into public.team_secrets(team_id, pin_hash)
select team_id, extensions.crypt(pin, extensions.gen_salt('bf')) from generated_credentials where team_id is not null;

insert into public.room_secrets(room_id, commish_pin_hash)
select r.id, extensions.crypt(g.pin, extensions.gen_salt('bf'))
from public.rooms r
join generated_credentials g on g.label = 'COMMISSIONER'
where r.code = 'GLSK26';

-- Credential helpers
create or replace function public._valid_team_pin(p_team_id uuid, p_pin text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.team_secrets s
    where s.team_id = p_team_id
      and s.pin_hash = extensions.crypt(p_pin, s.pin_hash)
  );
$$;

create or replace function public._valid_commish_pin(p_room_id uuid, p_pin text)
returns boolean
language sql
stable
security definer
set search_path = public, pg_temp
as $$
  select exists (
    select 1 from public.room_secrets s
    where s.room_id = p_room_id
      and s.commish_pin_hash = extensions.crypt(p_pin, s.commish_pin_hash)
  );
$$;

-- Internal helper. Caller must already hold a lock on the room row.
create or replace function public._activate_next(p_room_id uuid)
returns void
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_next uuid;
  v_timer integer;
begin
  select p.id into v_next
  from public.players p
  where p.room_id = p_room_id and p.status = 'queued'
  order by p.queue_order nulls last, p.rank
  limit 1
  for update;

  if v_next is null then
    return;
  end if;

  select timer_seconds into v_timer from public.rooms where id = p_room_id;

  update public.players
  set status = 'active', queue_order = null
  where id = v_next;

  update public.rooms
  set active_player_id = v_next,
      active_bid = 0,
      active_bidder_team_id = null,
      auction_ends_at = now() + make_interval(secs => v_timer),
      pause_remaining_seconds = null
  where id = p_room_id;
end;
$$;

create or replace function public.join_room(p_room_code text, p_team_id uuid, p_pin text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_room uuid;
begin
  select r.id into v_room
  from public.rooms r
  join public.teams t on t.room_id = r.id
  where r.code = p_room_code and t.id = p_team_id;

  if v_room is null then return jsonb_build_object('ok', false, 'error', 'Team not found in this room.'); end if;
  if not public._valid_team_pin(p_team_id, p_pin) then return jsonb_build_object('ok', false, 'error', 'Incorrect team PIN.'); end if;
  return jsonb_build_object('ok', true, 'team_id', p_team_id);
end;
$$;

create or replace function public.commish_login(p_room_code text, p_pin text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_room uuid;
begin
  select id into v_room from public.rooms where code = p_room_code;
  if v_room is null then return jsonb_build_object('valid', false); end if;
  return jsonb_build_object('valid', public._valid_commish_pin(v_room, p_pin));
end;
$$;

create or replace function public.submit_bid(p_room_code text, p_team_id uuid, p_pin text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_room public.rooms%rowtype;
  v_team public.teams%rowtype;
  v_next integer;
begin
  select * into v_room from public.rooms where code = p_room_code for update;
  if v_room.id is null then return jsonb_build_object('ok', false, 'error', 'Room not found.'); end if;
  if v_room.status <> 'live' then return jsonb_build_object('ok', false, 'error', 'The auction is not live.'); end if;
  if v_room.active_player_id is null then return jsonb_build_object('ok', false, 'error', 'No player is currently on the block.'); end if;
  if v_room.auction_ends_at is null or now() >= v_room.auction_ends_at then return jsonb_build_object('ok', false, 'error', 'That auction has expired.'); end if;
  if not public._valid_team_pin(p_team_id, p_pin) then return jsonb_build_object('ok', false, 'error', 'Your team PIN is no longer valid.'); end if;
  if v_room.active_bidder_team_id = p_team_id then return jsonb_build_object('ok', false, 'error', 'You already have the high bid.'); end if;

  select * into v_team from public.teams where id = p_team_id and room_id = v_room.id for update;
  if v_team.id is null then return jsonb_build_object('ok', false, 'error', 'Team not found.'); end if;

  v_next := case when v_room.active_bid = 0 then v_room.min_bid else v_room.active_bid + v_room.bid_increment end;
  if v_team.remaining_budget < v_next then return jsonb_build_object('ok', false, 'error', 'You do not have enough bid dollars remaining.'); end if;

  update public.rooms
  set active_bid = v_next,
      active_bidder_team_id = p_team_id,
      auction_ends_at = now() + make_interval(secs => timer_seconds)
  where id = v_room.id;

  insert into public.bids(room_id, player_id, team_id, amount)
  values (v_room.id, v_room.active_player_id, p_team_id, v_next);

  return jsonb_build_object('ok', true, 'bid', v_next);
end;
$$;

create or replace function public.finalize_if_expired(p_room_code text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare
  v_room public.rooms%rowtype;
  v_total integer;
  v_new_sold integer;
begin
  select * into v_room from public.rooms where code = p_room_code for update;
  if v_room.id is null then return jsonb_build_object('ok', false, 'error', 'Room not found.'); end if;
  if v_room.status <> 'live' or v_room.active_player_id is null or v_room.auction_ends_at is null or now() < v_room.auction_ends_at then
    return jsonb_build_object('ok', true, 'finalized', false);
  end if;

  if v_room.active_bidder_team_id is null or v_room.active_bid = 0 then
    update public.players set status = 'available', queue_order = null where id = v_room.active_player_id;
    update public.rooms set active_player_id = null, active_bid = 0, active_bidder_team_id = null, auction_ends_at = null where id = v_room.id;
    perform public._activate_next(v_room.id);
    return jsonb_build_object('ok', true, 'finalized', true, 'sold', false);
  end if;

  perform 1 from public.teams where id = v_room.active_bidder_team_id for update;
  update public.teams
  set remaining_budget = remaining_budget - v_room.active_bid
  where id = v_room.active_bidder_team_id and remaining_budget >= v_room.active_bid;
  if not found then return jsonb_build_object('ok', false, 'error', 'Winning team no longer has sufficient budget. Commissioner intervention required.'); end if;

  update public.players
  set status = 'sold', sold_team_id = v_room.active_bidder_team_id, sold_price = v_room.active_bid, queue_order = null
  where id = v_room.active_player_id;

  insert into public.sales(room_id, player_id, team_id, price)
  values (v_room.id, v_room.active_player_id, v_room.active_bidder_team_id, v_room.active_bid);

  v_new_sold := v_room.sold_count + 1;
  select count(*) into v_total from public.players where room_id = v_room.id;

  update public.rooms
  set active_player_id = null,
      active_bid = 0,
      active_bidder_team_id = null,
      auction_ends_at = null,
      sold_count = v_new_sold,
      status = case when v_new_sold >= v_total then 'complete' else status end
  where id = v_room.id;

  if v_new_sold < v_total then perform public._activate_next(v_room.id); end if;
  return jsonb_build_object('ok', true, 'finalized', true, 'sold', true, 'sold_count', v_new_sold);
end;
$$;

create or replace function public.commish_start_draft(p_room_code text, p_commish_pin text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_room public.rooms%rowtype;
begin
  select * into v_room from public.rooms where code = p_room_code for update;
  if v_room.id is null then return jsonb_build_object('ok', false, 'error', 'Room not found.'); end if;
  if not public._valid_commish_pin(v_room.id, p_commish_pin) then return jsonb_build_object('ok', false, 'error', 'Incorrect commissioner PIN.'); end if;
  if v_room.status = 'complete' then return jsonb_build_object('ok', false, 'error', 'This auction is already complete.'); end if;
  update public.rooms set status = 'live' where id = v_room.id;
  if v_room.active_player_id is null then perform public._activate_next(v_room.id); end if;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.commish_pause_draft(p_room_code text, p_commish_pin text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_room public.rooms%rowtype; v_left integer;
begin
  select * into v_room from public.rooms where code = p_room_code for update;
  if v_room.id is null or not public._valid_commish_pin(v_room.id, p_commish_pin) then return jsonb_build_object('ok', false, 'error', 'Commissioner authorization failed.'); end if;
  if v_room.status <> 'live' then return jsonb_build_object('ok', false, 'error', 'Auction is not live.'); end if;
  v_left := case when v_room.auction_ends_at is null then null else greatest(1, ceil(extract(epoch from (v_room.auction_ends_at - now())))::integer) end;
  update public.rooms set status = 'paused', pause_remaining_seconds = v_left, auction_ends_at = null where id = v_room.id;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.commish_resume_draft(p_room_code text, p_commish_pin text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_room public.rooms%rowtype;
begin
  select * into v_room from public.rooms where code = p_room_code for update;
  if v_room.id is null or not public._valid_commish_pin(v_room.id, p_commish_pin) then return jsonb_build_object('ok', false, 'error', 'Commissioner authorization failed.'); end if;
  if v_room.status <> 'paused' then return jsonb_build_object('ok', false, 'error', 'Auction is not paused.'); end if;
  update public.rooms set status = 'live', auction_ends_at = case when active_player_id is null then null else now() + make_interval(secs => coalesce(pause_remaining_seconds, timer_seconds)) end, pause_remaining_seconds = null where id = v_room.id;
  if v_room.active_player_id is null then perform public._activate_next(v_room.id); end if;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.commish_queue_player(p_room_code text, p_commish_pin text, p_player_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_room public.rooms%rowtype; v_order integer;
begin
  select * into v_room from public.rooms where code = p_room_code for update;
  if v_room.id is null or not public._valid_commish_pin(v_room.id, p_commish_pin) then return jsonb_build_object('ok', false, 'error', 'Commissioner authorization failed.'); end if;
  if not exists(select 1 from public.players where id = p_player_id and room_id = v_room.id and status = 'available') then return jsonb_build_object('ok', false, 'error', 'Player is not available to queue.'); end if;
  select coalesce(max(queue_order),0)+1 into v_order from public.players where room_id = v_room.id and status = 'queued';
  update public.players set status = 'queued', queue_order = v_order where id = p_player_id;
  if v_room.status = 'live' and v_room.active_player_id is null then perform public._activate_next(v_room.id); end if;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.commish_unqueue_player(p_room_code text, p_commish_pin text, p_player_id uuid)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_room public.rooms%rowtype;
begin
  select * into v_room from public.rooms where code = p_room_code;
  if v_room.id is null or not public._valid_commish_pin(v_room.id, p_commish_pin) then return jsonb_build_object('ok', false, 'error', 'Commissioner authorization failed.'); end if;
  update public.players set status = 'available', queue_order = null where id = p_player_id and room_id = v_room.id and status = 'queued';
  if not found then return jsonb_build_object('ok', false, 'error', 'Player is not currently queued.'); end if;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.commish_skip_active(p_room_code text, p_commish_pin text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_room public.rooms%rowtype;
begin
  select * into v_room from public.rooms where code = p_room_code for update;
  if v_room.id is null or not public._valid_commish_pin(v_room.id, p_commish_pin) then return jsonb_build_object('ok', false, 'error', 'Commissioner authorization failed.'); end if;
  if v_room.active_player_id is null then return jsonb_build_object('ok', false, 'error', 'No active player to skip.'); end if;
  update public.players set status = 'available', queue_order = null where id = v_room.active_player_id;
  update public.rooms set active_player_id = null, active_bid = 0, active_bidder_team_id = null, auction_ends_at = null where id = v_room.id;
  if v_room.status = 'live' then perform public._activate_next(v_room.id); end if;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.commish_force_sale(p_room_code text, p_commish_pin text, p_team_id uuid, p_price integer)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_room public.rooms%rowtype; v_total integer; v_new_sold integer;
begin
  select * into v_room from public.rooms where code = p_room_code for update;
  if v_room.id is null or not public._valid_commish_pin(v_room.id, p_commish_pin) then return jsonb_build_object('ok', false, 'error', 'Commissioner authorization failed.'); end if;
  if v_room.active_player_id is null then return jsonb_build_object('ok', false, 'error', 'No active player.'); end if;
  if p_price is null or p_price < 1 then return jsonb_build_object('ok', false, 'error', 'Sale price must be at least $1.'); end if;
  perform 1 from public.teams where id = p_team_id and room_id = v_room.id and remaining_budget >= p_price for update;
  if not found then return jsonb_build_object('ok', false, 'error', 'Selected team does not have enough bid dollars.'); end if;

  update public.teams set remaining_budget = remaining_budget - p_price where id = p_team_id;
  update public.players set status = 'sold', sold_team_id = p_team_id, sold_price = p_price, queue_order = null where id = v_room.active_player_id;
  insert into public.sales(room_id, player_id, team_id, price) values(v_room.id, v_room.active_player_id, p_team_id, p_price);
  v_new_sold := v_room.sold_count + 1;
  select count(*) into v_total from public.players where room_id = v_room.id;
  update public.rooms set active_player_id = null, active_bid = 0, active_bidder_team_id = null, auction_ends_at = null, sold_count = v_new_sold, status = case when v_new_sold >= v_total then 'complete' else status end where id = v_room.id;
  if v_new_sold < v_total and v_room.status = 'live' then perform public._activate_next(v_room.id); end if;
  return jsonb_build_object('ok', true);
end;
$$;

create or replace function public.commish_undo_last_sale(p_room_code text, p_commish_pin text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_room public.rooms%rowtype; v_sale public.sales%rowtype;
begin
  select * into v_room from public.rooms where code = p_room_code for update;
  if v_room.id is null or not public._valid_commish_pin(v_room.id, p_commish_pin) then return jsonb_build_object('ok', false, 'error', 'Commissioner authorization failed.'); end if;
  select * into v_sale from public.sales where room_id = v_room.id and undone = false order by sold_at desc limit 1 for update;
  if v_sale.id is null then return jsonb_build_object('ok', false, 'error', 'There is no completed sale to undo.'); end if;
  perform 1 from public.teams where id = v_sale.team_id for update;
  update public.teams set remaining_budget = remaining_budget + v_sale.price where id = v_sale.team_id;
  update public.players set status = 'available', sold_team_id = null, sold_price = null, queue_order = null where id = v_sale.player_id;
  update public.sales set undone = true where id = v_sale.id;
  update public.rooms set sold_count = greatest(0, sold_count - 1), status = case when status = 'complete' then 'live' else status end where id = v_room.id;
  return jsonb_build_object('ok', true);
end;
$$;


create or replace function public.commish_reset_draft(p_room_code text, p_commish_pin text)
returns jsonb
language plpgsql
security definer
set search_path = public, pg_temp
as $$
declare v_room public.rooms%rowtype; v_player_count integer; v_team_count integer;
begin
  select * into v_room from public.rooms where code = p_room_code for update;
  if v_room.id is null then return jsonb_build_object('ok', false, 'error', 'Room not found.'); end if;
  if not public._valid_commish_pin(v_room.id, p_commish_pin) then return jsonb_build_object('ok', false, 'error', 'Commissioner authorization failed.'); end if;

  delete from public.bids where room_id = v_room.id;
  delete from public.sales where room_id = v_room.id;
  update public.teams set remaining_budget = starting_budget where room_id = v_room.id;
  get diagnostics v_team_count = row_count;
  update public.players set status = 'queued', queue_order = rank, sold_team_id = null, sold_price = null where room_id = v_room.id;
  get diagnostics v_player_count = row_count;
  update public.rooms set status = 'setup', active_player_id = null, active_bid = 0, active_bidder_team_id = null, auction_ends_at = null, pause_remaining_seconds = null, sold_count = 0 where id = v_room.id;
  return jsonb_build_object('ok', true, 'teams_restored', v_team_count, 'players_restored', v_player_count);
end;
$$;

-- Only expose the intended RPC surface.
revoke all on function public._valid_team_pin(uuid,text) from public, anon, authenticated;
revoke all on function public._valid_commish_pin(uuid,text) from public, anon, authenticated;
revoke all on function public._activate_next(uuid) from public, anon, authenticated;

grant execute on function public.join_room(text,uuid,text) to anon, authenticated;
grant execute on function public.commish_login(text,text) to anon, authenticated;
grant execute on function public.submit_bid(text,uuid,text) to anon, authenticated;
grant execute on function public.finalize_if_expired(text) to anon, authenticated;
grant execute on function public.commish_start_draft(text,text) to anon, authenticated;
grant execute on function public.commish_pause_draft(text,text) to anon, authenticated;
grant execute on function public.commish_resume_draft(text,text) to anon, authenticated;
grant execute on function public.commish_queue_player(text,text,uuid) to anon, authenticated;
grant execute on function public.commish_unqueue_player(text,text,uuid) to anon, authenticated;
grant execute on function public.commish_skip_active(text,text) to anon, authenticated;
grant execute on function public.commish_force_sale(text,text,uuid,integer) to anon, authenticated;
grant execute on function public.commish_undo_last_sale(text,text) to anon, authenticated;
grant execute on function public.commish_reset_draft(text,text) to anon, authenticated;

-- Enable live updates for every connected phone/laptop.
do $$
begin
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'rooms') then
    alter publication supabase_realtime add table public.rooms;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'teams') then
    alter publication supabase_realtime add table public.teams;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'players') then
    alter publication supabase_realtime add table public.players;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'bids') then
    alter publication supabase_realtime add table public.bids;
  end if;
  if not exists (select 1 from pg_publication_tables where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'sales') then
    alter publication supabase_realtime add table public.sales;
  end if;
end
$$;

commit;

-- IMPORTANT: Copy/save this result grid before closing the SQL editor.
-- Send each manager only their team's PIN. Keep the COMMISSIONER PIN private.
select label as "Team / Role", pin as "6-digit PIN"
from generated_credentials
order by case when label = 'COMMISSIONER' then 2 else 1 end, label;
