import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
const room='00000000-0000-0000-0000-000000000001',other='00000000-0000-0000-0000-000000000002';
const commish='00000000-0000-0000-0000-000000000011',owner='00000000-0000-0000-0000-000000000012',outsider='00000000-0000-0000-0000-000000000013';
await db.exec(`create role anon;create role authenticated;create schema auth;
create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.auth_uid',true),'')::uuid$$;
grant usage on schema public,auth to anon,authenticated;
create table rooms(id uuid primary key,code text unique);
insert into rooms values('${room}','GLSK26'),('${other}','OTHER');
create table league_owner_accounts(room_id uuid,user_id uuid,active boolean,is_commissioner boolean);
insert into league_owner_accounts values('${room}','${commish}',true,true),('${room}','${owner}',true,false),('${other}','${outsider}',true,true);`);
const tables=['league_player_stats','league_player_projections','league_weekly_player_scores'];
for (const table of tables) await db.exec(`create table ${table}(room_id uuid,points integer);
insert into ${table} values('${room}',42),('${other}',99);
alter table ${table} enable row level security;
create policy old_public_read on ${table} for select to anon,authenticated using(true);
grant select on ${table} to anon,authenticated;`);
await db.exec(`create view league_matchup_live_scores as select * from league_weekly_player_scores;
create view league_shadow_standings as select * from league_matchup_live_scores;
grant select on league_matchup_live_scores,league_shadow_standings to anon,authenticated;`);
const migration=fs.readFileSync(new URL('../supabase/msf-trial-v1.sql',import.meta.url),'utf8');
await db.exec(migration);await db.exec(migration); // repeat installation is safe
const identity=async(user,role='authenticated')=>{
  await db.exec('reset role');await db.query("select set_config('test.auth_uid',$1,false)",[user]);await db.exec('set role '+role);
};
const rpc=action=>db.query('select league_msf_trial_context($1,$2)',[action,'players']);
await identity('', 'anon');
for (const table of [...tables,'league_matchup_live_scores','league_shadow_standings']) await assert.rejects(()=>db.query('select * from '+table),/permission denied/);
await assert.rejects(()=>rpc('status'),/permission denied/);
await identity(outsider);await assert.rejects(()=>rpc('status'),/MSF_FORBIDDEN/);
for (const table of [...tables,'league_matchup_live_scores','league_shadow_standings']) assert.deepEqual((await db.query('select points from '+table)).rows,[{points:99}]);
await identity(owner);await assert.rejects(()=>rpc('claim'),/MSF_FORBIDDEN/);
for (const table of [...tables,'league_matchup_live_scores','league_shadow_standings']) assert.deepEqual((await db.query('select points from '+table)).rows,[{points:42}]);
await identity(commish);await rpc('status');await rpc('claim');await assert.rejects(()=>rpc('claim'),/MSF_COOLDOWN/);
await assert.rejects(()=>db.exec('delete from league_msf_trial_checks'),/permission denied/);
await db.exec('reset role');await db.exec("update league_msf_trial_checks set requested_at=now()-interval '4 minutes'");
await identity(commish);await rpc('claim');
await db.exec('reset role');await db.exec(`update league_owner_accounts set active=false where user_id='${owner}'`);
await identity(owner);assert.equal((await db.query('select * from league_player_stats')).rows.length,0);
await db.close();console.log('PASS: migration repeatability, anonymous denial, room isolation, inactive-member denial, commissioner-only checks, cooldown and invoker views.');
