import {Window} from 'happy-dom';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const window=new Window();globalThis.document=window.document;globalThis.confirm=()=>true;
const source=fs.readFileSync(new URL('../src/season-rollover.js',import.meta.url),'utf8');
const {bindRollover,rolloverView}=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const state={session:{commishPin:'AUTH',teamId:'A'},room:{code:'TEST'},season:{id:'2026',season_year:2026},teams:[{id:'A',name:'Team A'}]};
const calls=[];const plan={source_year:2026,target_year:2027,teams:[{team_id:'A',name:'Team A',regular_finish:1,draft_slot:1,allocation:100,adjustment:0,new_bids:100,cap_used:15}],players:[],rights:[],picks:[],notes:['Drafts archived.']};
let applied=false;
const rpc=async(name,args)=>{calls.push({name,args});if(name==='league_commish_get_rollovers')return {runs:applied?[{id:'run',status:'applied',preview:plan,can_undo:true}]:[]};if(name==='league_commish_preview_rollover')return{id:'run',preview:plan};if(name==='league_commish_apply_rollover'){applied=true;return{ok:true}}if(name==='league_commish_undo_rollover'){applied=false;return{ok:true}}throw Error('Unexpected RPC');};
const refresh=async()=>{state.season=applied?{id:'2027',season_year:2027}:{id:'2026',season_year:2026};document.body.innerHTML=rolloverView();bindRollover({state,rpc,refresh});};
const flush=async()=>{for(let i=0;i<5;i++)await new Promise(r=>setTimeout(r,0));};
document.body.innerHTML=rolloverView();bindRollover({state,rpc,refresh});await flush();
const form=document.querySelector('#ro-form');form.elements.bid_pool.value='100';form.elements.results_confirmed.checked=true;form.querySelector('[data-field="regular_finish"]').value='1';form.querySelector('[data-field="finish"]').value='1';
form.dispatchEvent(new window.Event('submit',{cancelable:true}));await flush();
assert(document.querySelector('#ro-apply'));assert.equal(calls.filter(x=>x.name==='league_commish_preview_rollover').length,1);
document.querySelector('#ro-confirm-year').value='2026';document.querySelector('#ro-apply').click();await flush();assert.equal(calls.filter(x=>x.name==='league_commish_apply_rollover').length,0);
document.querySelector('#ro-confirm-year').value='2027';document.querySelector('#ro-apply').click();await flush();assert.equal(calls.filter(x=>x.name==='league_commish_apply_rollover').length,1);assert.equal(state.season.season_year,2027);
document.querySelector('[data-ro-undo-year]').value='2026';document.querySelector('[data-ro-undo]').click();await flush();assert.equal(state.season.season_year,2026);assert.equal(calls.filter(x=>x.name==='league_commish_undo_rollover').length,1);
state.session.commishPin='';document.body.innerHTML=rolloverView();bindRollover({state,rpc,refresh});assert.match(document.body.textContent,/Commissioner access is required/);assert.equal(document.querySelectorAll('form').length,0);
console.log('PASS: UI history load, preview, typed-year confirmation, apply refresh, undo refresh, and owner access denial.');
