import {PGlite} from '@electric-sql/pglite';
import fs from 'node:fs';
import assert from 'node:assert/strict';
const db=new PGlite();
const query=(s,p=[])=>db.query(s,p);
const one=async(s,p=[])=>Object.values((await query(s,p)).rows[0])[0];
await db.exec(`create role anon;create role authenticated;create schema auth;create function auth.uid() returns uuid language sql as $$select nullif(current_setting('test.auth_uid',true),'')::uuid$$;`);
await db.exec(fs.readFileSync(new URL('./schema-fixture.sql',import.meta.url),'utf8'));
await db.exec(`alter table league_roster_entries add column roster_slot text default 'ACTIVE';
create function public._valid_commish_pin(uuid,text) returns boolean language sql as $$select $2='test-commish'$$;
create function public._league_current_season_id(text) returns uuid language sql as $$select s.id from league_seasons s join rooms r on r.id=s.room_id where r.code=$1 and s.is_current$$;`);
await db.exec(fs.readFileSync(new URL('../supabase/season-rollover-v737.sql',import.meta.url),'utf8'));
const room=await one("insert into rooms(code,name) values('TEST','Test') returning id");
const sid=await one("insert into league_seasons(room_id,season_year,is_current) values($1,2026,true) returning id",[room]);
const teams=[];
for(const [i,name] of ['A','B'].entries())teams.push(await one('insert into teams(room_id,name,starting_budget,remaining_budget,sort_order) values($1,$2,100,80,$3) returning id',[room,name,i+1]));
await query("insert into redistribution_rules(season_id,bracket,finish,label,percentage,sort_order) values($1,'championship',1,'Winner',60,1),($1,'championship',2,'Runner',40,2)",[sid]);
await query('insert into contract_options(season_id,years,cap_cost) values($1,2,15)',[sid]);
await query('insert into league_game_settings(season_id,room_id,current_week) values($1,$2,18)',[sid,room]);
await query("insert into league_lineup_slots(season_id,room_id,slot_code,label,slot_order,allowed_positions) values($1,$2,'QB','QB',1,ARRAY['QB'])",[sid,room]);
for(const key of ['keep','expire','rookie'])await query("insert into league_roster_entries(room_id,team_id,player_key,player_name,position,roster_slot) values($1,$2,$3,$3,'QB','IR')",[room,teams[0],key]);
for(const [key,end] of [['keep',2027],['expire',2026]])await query('insert into league_contracts(season_id,team_id,player_key,player_name,start_year,end_year,length_years,cap_cost) values($1,$2,$3,$3,2026,$4,2,15)',[sid,teams[0],key,end]);
await query("insert into league_rookie_rights(room_id,player_key,player_name,rookie_draft_year,owner_team_id) values($1,'rookie','rookie',2026,$2)",[room,teams[0]]);
await query("insert into league_future_picks(room_id,draft_year,draft_type,round,original_team_id,owner_team_id) values($1,2027,'rookie',1,$2,$3)",[room,teams[0],teams[1]]);
const input={bid_pool:101,results_confirmed:true,teams:teams.map((id,i)=>({team_id:id,regular_finish:i+1,bracket:'championship',finish:i+1,adjustment:0}))};
const rpc=(name,...args)=>one(`select public.${name}(${args.map((_,i)=>'$'+(i+1)).join(',')})`,args);
const preview=()=>rpc('league_commish_preview_rollover','TEST','test-commish',JSON.stringify(input));
const apply=p=>rpc('league_commish_apply_rollover','TEST','test-commish',p.id,2027);
const undo=p=>rpc('league_commish_undo_rollover','TEST','test-commish',p.id,2026);
await assert.rejects(()=>rpc('league_commish_preview_rollover','TEST','wrong',JSON.stringify(input)),/authorization/);
await db.exec(`create function public.league_current_account(text) returns jsonb language sql as $$select jsonb_build_object('team_id','${teams[0]}','is_commissioner',auth.uid()='00000000-0000-0000-0000-000000000001'::uuid)$$;`);
await assert.rejects(()=>rpc('league_commish_preview_rollover','TEST','AUTH',JSON.stringify(input)),/signed-in/);
await query("select set_config('test.auth_uid','00000000-0000-0000-0000-000000000002',false)");
await assert.rejects(()=>rpc('league_commish_preview_rollover','TEST','AUTH',JSON.stringify(input)),/authorization/);
await query("select set_config('test.auth_uid','00000000-0000-0000-0000-000000000001',false)");
assert((await rpc('league_commish_preview_rollover','TEST','AUTH',JSON.stringify(input))).ok);

let p=await preview();assert.deepEqual(p.preview.teams.map(t=>t.new_bids),[61,40]);assert.deepEqual(p.preview.teams.map(t=>t.draft_slot),[2,1]);
await query('update teams set remaining_budget=79 where id=$1',[teams[0]]);
await assert.rejects(()=>apply(p),/changed/);
p=await preview();const before=await one('select public._rollover_snapshot($1,$2)',[room,sid]);
await apply(p);
assert.equal(await one('select season_year from league_seasons where is_current'),2027);
assert.equal(await one('select count(*)::int from league_roster_entries where active'),1);
assert.equal(await one("select roster_slot from league_roster_entries where player_key='keep'"),'ACTIVE');
assert.equal(await one('select count(*)::int from league_contracts c join league_seasons s on s.id=c.season_id where s.is_current'),1);
assert.equal(await one('select owner_team_id from league_rookie_rights'),teams[0]);
assert.equal(await one('select owner_team_id from league_future_picks'),teams[1]);
assert.equal(await one('select current_week from league_game_settings g join league_seasons s on s.id=g.season_id where is_current'),1);
await query('update teams set remaining_budget=remaining_budget where id=$1',[teams[0]]);
assert((await rpc('league_commish_get_rollovers','TEST','test-commish')).runs[0].can_undo);
await assert.rejects(()=>query("update rooms set status='live' where id=$1",[room]),/archived/);
await assert.rejects(()=>apply(p),/already used/);
await undo(p);
assert.deepEqual(await one('select public._rollover_snapshot($1,$2)',[room,sid]),before);
await assert.rejects(()=>undo(p),/once/);
// A late failure must roll back the entire transition, including the current flag.
await db.exec(`create function fail_budget_test() returns trigger language plpgsql as $$begin raise exception 'Injected budget failure';end$$;
create trigger test_budget_failure before update on teams for each row execute function fail_budget_test();`);
p=await preview();await assert.rejects(()=>apply(p),/Injected budget failure/);
assert.equal(await one('select season_year from league_seasons where is_current'),2026);
assert.equal(await one('select count(*)::int from league_seasons'),1);
await db.exec('drop trigger test_budget_failure on teams;drop function fail_budget_test();');
// Permissions: no owner can read snapshots or call private plan helpers.
await db.exec('set role authenticated');
await assert.rejects(()=>one('select before_state from league_season_rollovers'),/permission denied/);
await assert.rejects(()=>one('select public._rollover_snapshot($1,$2)',[room,sid]),/permission denied/);
await db.exec('reset role');
p=await preview();await apply(p);
await query('update teams set remaining_budget=remaining_budget+1 where id=$1',[teams[1]]);
await assert.rejects(()=>undo(p),/activity occurred/);
assert(!(await rpc('league_commish_get_rollovers','TEST','test-commish')).runs[0].can_undo);
console.log('PASS: PostgreSQL engine migration, authorization, allocations, stale previews, contracts, roster/IR, settings, rights/picks, archive guard, duplicate apply/undo, exact restoration and activity block.');
await db.close();
