import {parseMetricsCSV} from './draft-tools.js';
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const number=v=>v==null||v===''||!Number.isFinite(Number(v))?'—':Number(v).toLocaleString('en-US',{maximumFractionDigits:1});
const position=v=>v==='DST'?'DEF':v||'—';
const drafted=p=>['sold','drafted'].includes(p.status);
const initials=name=>String(name||'?').split(/\s+/).slice(0,2).map(x=>x[0]).join('');
export function createDraftRoom(phase,roomCode){
 let config,storageKey='',ui={queue:[],selected:null,search:'',position:'ALL',showDrafted:false};
 const persist=()=>{try{localStorage.setItem(storageKey,JSON.stringify({queue:ui.queue}));}catch{}};
 const pick=id=>config.players.find(p=>String(p.id)===String(id));
 const availableQueue=()=>ui.queue.map(pick).filter(p=>p&&!drafted(p));
 const selectButton=p=>`<button type="button" class="desk-player-name" data-desk-select="${esc(p.id)}">${esc(p.name)}</button>`;
 const star=p=>`<button type="button" class="desk-star ${ui.queue.includes(String(p.id))?'is-queued':''}" data-desk-star="${esc(p.id)}" aria-label="${ui.queue.includes(String(p.id))?'Remove from':'Add to'} queue: ${esc(p.name)}" aria-pressed="${ui.queue.includes(String(p.id))}" ${drafted(p)?'disabled':''}>${ui.queue.includes(String(p.id))?'★':'☆'}</button>`;
 const stat=(p,key)=>number(p.projection_stats?.[key]);
 function playerTable(){
  const ranks=new Map((config.tools?.ordered(config.players)||config.players).map((p,i)=>[String(p.id),i+1]));
  const rows=config.players.filter(p=>(ui.showDrafted||!drafted(p))&&(ui.position==='ALL'||position(p.position)===ui.position)&&(!ui.search||`${p.name} ${p.nfl_team} ${p.position}`.toLowerCase().includes(ui.search.toLowerCase()))).sort((a,b)=>{const mode=config.tools?.state.editing?'personal':ui.sort||'personal';if(mode==='personal')return ranks.get(String(a.id))-ranks.get(String(b.id));if(mode==='rank')return Number(a.yahoo_rank??a.rank??99999)-Number(b.yahoo_rank??b.rank??99999);const av=config.tools?.metric(a)?.[mode],bv=config.tools?.metric(b)?.[mode];if(av==null)return bv==null?0:1;if(bv==null)return -1;return mode==='yahoo_adp'?av-bv:bv-av;});
  return `${rankTools()}<div class="desk-filters"><label><span class="desk-sr">Position</span><select data-desk-position>${['ALL','QB','RB','WR','TE','K','DEF'].map(v=>`<option value="${v}" ${ui.position===v?'selected':''}>${v==='ALL'?'All positions':v}</option>`).join('')}</select></label><label class="desk-search"><span aria-hidden="true">⌕</span><input data-desk-search placeholder="Search for a player" aria-label="Search for a player" value="${esc(ui.search)}"></label><label class="desk-checkbox"><input type="checkbox" data-desk-drafted ${ui.showDrafted?'checked':''}>Show drafted</label><label>Sort <select data-desk-sort ${config.tools?.state.editing?'disabled':''}>${[['personal','My Rankings'],['rank','Yahoo Rank'],['yahoo_adp','Yahoo ADP'],['previous_fantasy_points','Previous points'],['projected_fantasy_points','Projected points']].map(([v,l])=>`<option value="${v}" ${(ui.sort||'personal')===v?'selected':''}>${l}</option>`).join('')}</select></label><span class="desk-count">${rows.length} players</span></div>
  <div class="desk-table-scroll" data-desk-scroll="players"><table class="desk-player-table"><thead><tr><th scope="col">Queue</th><th scope="col">My Rank</th><th scope="col">Yahoo Rank</th><th scope="col">Player</th><th scope="col">Yahoo ADP</th><th scope="col">${config.tools?.state.context?.season_year?config.tools.state.context.season_year-1:"Previous"} FPTS</th><th scope="col">${config.tools?.state.context?.season_year||"Current"} Proj FPTS</th><th scope="col">Bye</th><th scope="col">Pass Yds</th><th scope="col">Rush Yds</th><th scope="col">Rec</th><th scope="col">Rec Yds</th><th scope="col">Status / Action</th></tr></thead><tbody>${rows.map(p=>`<tr class="${String(p.id)===String(ui.selected||config.activePlayer?.id)?'is-selected':''} ${drafted(p)?'is-drafted':''}"><td>${star(p)}</td><td>${config.tools?.state.editing?`<input class="desk-rank-input" type="number" min="1" max="${config.players.length}" value="${ranks.get(String(p.id))}" data-personal-rank="${esc(p.id)}" aria-label="Rank ${esc(p.name)}" ${config.tools.state.busy?'disabled':''}>`:ranks.get(String(p.id))}</td><td>${number(p.yahoo_rank??p.rank)}</td><td>${selectButton(p)}<div class="desk-player-meta">${esc(p.nfl_team||'—')} · ${esc(position(p.position))}${p.rights_team_id?` · Rights: ${esc(config.teams.find(t=>t.id===p.rights_team_id)?.name||'Assigned')}`:''}</div></td><td title="${esc(config.tools?.metric(p)?.source||'Yahoo ADP not loaded')}">${number(config.tools?.metric(p)?.yahoo_adp)}</td><td title="${esc(config.tools?.metric(p)?.previous_source||'Previous season points not loaded')}">${number(config.tools?.metric(p)?.previous_fantasy_points)}</td><td title="${esc(config.tools?.metric(p)?.source||'Season projection not loaded')}">${number(config.tools?.metric(p)?.projected_fantasy_points)}</td><td>${number(p.bye)}</td><td>${stat(p,'PassYds')}</td><td>${stat(p,'RunYds')}</td><td>${stat(p,'REC')}</td><td>${stat(p,'RecYds')}</td><td>${drafted(p)?'Drafted':config.playerAction(p)||esc(p.status==='queued'?'Nominated':p.id===config.activePlayer?.id?'On the block':'Available')}</td></tr>`).join('')||'<tr><td colspan="13" class="desk-empty">No matching players.</td></tr>'}</tbody></table></div><div class="desk-data-note">${esc(config.sourceNote)} Yahoo ADP and full-season fantasy totals appear when verified data is loaded; missing figures display as dashes.</div>`;
 }

 function teamsPanel(){
  const rank={QB:1,RB:2,WR:3,TE:4,K:5,DST:6,DEF:6};
  return `<div class="desk-other-panel"><div class="desk-team-list">${config.teams.map(t=>{const roster=(config.allRoster||[]).filter(r=>r.team_id===t.id&&r.active!==false).sort((a,b)=>Number(a.roster_slot==='IR')-Number(b.roster_slot==='IR')||(rank[a.position]||9)-(rank[b.position]||9)||a.player_name.localeCompare(b.player_name));return `<details class="desk-team-card" data-desk-detail="team-${esc(t.id)}"><summary><strong>${esc(t.name)}</strong><span>${roster.length} players · $${number(t.remaining_budget)} <b>⌄</b></span></summary><div>${roster.map(r=>`<div class="desk-expanded-player"><span>${esc(r.roster_slot==='IR'?'IR':position(r.position))}</span><strong>${esc(r.player_name)}</strong><small>${esc(r.nfl_team||'')}</small></div>`).join('')||'<p class="desk-data-note">No active roster entries.</p>'}</div></details>`}).join('')}</div></div>`;
 }
 function rankTools(){const t=config.tools;if(!t)return '';const s=t.state;return `<div class="desk-rank-tools">${s.editing?`<button data-rank-save ${s.busy?'disabled':''}>${s.busy?'Saving…':'Save Rankings'}</button><button data-rank-cancel ${s.busy?'disabled':''}>Cancel</button><button data-rank-reset ${s.busy?'disabled':''}>Reset to Yahoo order</button>`:`<button data-rank-edit ${!s.context?'disabled':''}>Edit My Rankings</button><button data-rank-reload>Reload Saved</button>`}<span role="status">${esc(s.error||s.notice||'Your rankings are private and saved to your account.')}</span></div>`;}
 function metricsImportView(){const t=config.tools;if(!t?.state.context?.is_commissioner)return '';const s=t.state;return `<div class="desk-metrics-import"><h3>Draft statistics import</h3><p>CSV columns: player_name, yahoo_adp, previous_fantasy_points, projected_fantasy_points. Use ${s.context.season_year-1} actual points and ${s.context.season_year} projections with league scoring. Blank cells clear that imported figure.</p><label>Source and date<input data-metrics-source value="${esc(s.importSource)}" placeholder="Provider, scoring format, date"></label><label>CSV file<input data-metrics-file type="file" accept=".csv,text/csv"></label>${s.pendingImport?`<p>${s.pendingImport.length} records ready for ${s.context.season_year}.</p><div style="overflow:auto;max-height:200px"><table><thead><tr><th>Player</th><th>Yahoo ADP</th><th>Previous FPTS</th><th>Projected FPTS</th></tr></thead><tbody>${s.pendingImport.map(r=>`<tr><td>${esc(r.player_name)}</td><td>${number(r.yahoo_adp)}</td><td>${number(r.previous_fantasy_points)}</td><td>${number(r.projected_fantasy_points)}</td></tr>`).join('')}</tbody></table></div><button data-metrics-confirm ${s.busy?'disabled':''}>Confirm Import</button>`:''}<p role="status">${esc(s.notice)}</p></div>`;}
 function preview(){
  const p=pick(ui.selected)||config.activePlayer||config.players.find(p=>!drafted(p));
  if(!p)return '<div class="desk-preview"><div><span class="desk-eyebrow">Player details</span><h2>No players available</h2></div></div>';
  return `<section class="desk-preview" aria-label="Player details"><div class="desk-avatar" aria-hidden="true">${esc(initials(p.name))}</div><div class="desk-preview-copy"><span class="desk-eyebrow">Player details</span><h2>${esc(p.name)}</h2><div>${esc(position(p.position))} · ${esc(p.nfl_team||'—')} · ${drafted(p)?'Drafted':p.id===config.activePlayer?.id?'On the block':'Available'}</div></div><dl><div><dt>Rank</dt><dd>${number(p.yahoo_rank??p.rank)}</dd></div><div><dt>Bye</dt><dd>${number(p.bye)}</dd></div></dl>${star(p)}</section>`;
 }
 function queueView(){
  const rows=availableQueue();
  return `<section class="desk-side-section"><h2>☆ My Queue <span>${rows.length}</span></h2><p class="desk-hint">Your shortlist on this device. Use the arrows to prioritize players.</p><div class="desk-queue" data-desk-scroll="queue">${rows.map((p,i)=>`<div class="desk-queue-row"><div>${selectButton(p)}<div class="desk-player-meta">${esc(position(p.position))} · ${esc(p.nfl_team||'—')}</div></div><div class="desk-queue-controls"><button data-desk-move="${esc(p.id)}" data-direction="-1" aria-label="Move ${esc(p.name)} up" ${i===0?'disabled':''}>↑</button><button data-desk-move="${esc(p.id)}" data-direction="1" aria-label="Move ${esc(p.name)} down" ${i===rows.length-1?'disabled':''}>↓</button><button data-desk-star="${esc(p.id)}" aria-label="Remove ${esc(p.name)} from queue">×</button></div></div>`).join('')||'<p class="desk-empty">Star a player in the table to add them here.</p>'}</div></section>`;
 }
 function rosterView(){
  const rank={QB:1,RB:2,WR:3,TE:4,K:5,DST:6,DEF:6};
  const rows=config.roster.filter(r=>r.active!==false).slice().sort((a,b)=>(rank[a.position]||9)-(rank[b.position]||9)||String(a.player_name).localeCompare(String(b.player_name)));
  return `<section class="desk-side-section"><h2>My Team <span>${rows.length}${config.rosterLimit?' / '+config.rosterLimit:''}</span></h2><p class="desk-team-title">${esc(config.myTeam?.name||'Sign in as an owner')}</p><div class="desk-roster" data-desk-scroll="roster">${rows.map(r=>`<div class="desk-roster-row"><span>${esc(position(r.position))}</span><div><strong>${esc(r.player_name)}</strong><small>${esc(r.nfl_team||'')}</small></div></div>`).join('')||'<p class="desk-empty">No players rostered yet.</p>'}</div><button class="desk-side-link" data-draft-comms>League Chat &amp; Video</button></section>`;
 }
 function view(c){
  config=c;
  const key=`glsk-draft-shortlist-${roomCode}-${phase}-${c.myTeam?.id||'guest'}`;
  if(key!==storageKey){storageKey=key;ui={queue:[],selected:null,search:'',position:'ALL',showDrafted:false};try{const saved=JSON.parse(localStorage.getItem(key)||'{}');if(Array.isArray(saved.queue))ui.queue=[...new Set(saved.queue.filter(x=>typeof x==='string'))];}catch{}}
  const activeTab=c.tabs.find(x=>x.active)?.key;
  const live=c.stageHtml.replace(/ id="(?:timer|supp-timer|phase3-timer)"/g,'');
  return `<div class="draft-desk"><aside class="desk-left"><section class="desk-clock"><div id="${esc(c.timerId)}" class="timer" role="timer" aria-label="Draft countdown">--</div><span class="desk-eyebrow">${esc(c.clockLabel)}</span><strong>${esc(c.clockDetail)}</strong><div class="desk-turn-note">${esc(c.turnNote)}</div></section><details class="desk-order" open><summary>${esc(c.orderTitle)}</summary><div class="desk-order-scroll" data-desk-scroll="order">${c.orderHtml||'<p class="desk-empty">Waiting for the draft order.</p>'}</div></details></aside>
  <main class="desk-center">${preview()}<div class="desk-live">${live}</div>${c.commissionerHtml?`<details class="desk-commissioner"><summary>Commissioner controls</summary>${c.commissionerHtml}${metricsImportView()}</details>`:''}<section class="desk-workspace"><nav class="desk-tabs" aria-label="Draft views">${c.tabs.map(t=>`<button data-tab="${esc(t.key)}" class="${activeTab===t.key?'active':''}" aria-current="${t.active?'page':'false'}">${esc(t.label)}</button>`).join('')}</nav>${activeTab==='teams'?teamsPanel():c.contentHtml==null?playerTable():`<div class="desk-other-panel" data-desk-scroll="panel">${c.contentHtml}</div>`}</section></main><aside class="desk-right">${queueView()}${rosterView()}</aside></div>`;
 }
 function bind(root,rerender){
  const t=config.tools;
  root.querySelector('[data-desk-sort]')?.addEventListener('change',e=>{ui.sort=e.target.value;rerender();});
  root.querySelector('[data-rank-edit]')?.addEventListener('click',()=>{t.edit(config.players);ui.sort='personal';rerender();});
  root.querySelector('[data-rank-cancel]')?.addEventListener('click',()=>{t.state.editing=false;t.state.order=[...t.state.saved];t.state.notice='';rerender();});
  root.querySelector('[data-rank-reset]')?.addEventListener('click',()=>{t.state.order=config.players.slice().sort((a,b)=>Number(a.yahoo_rank??a.rank??99999)-Number(b.yahoo_rank??b.rank??99999)).map(p=>String(p.id));rerender();});
  root.querySelectorAll('[data-personal-rank]').forEach(el=>el.addEventListener('change',()=>{t.move(el.dataset.personalRank,Number(el.value));rerender();}));
  root.querySelector('[data-rank-save]')?.addEventListener('click',async()=>{const save=t.save();rerender();await save;rerender();});
  root.querySelector('[data-rank-reload]')?.addEventListener('click',async()=>{await t.load(true);rerender();});
  root.querySelector('[data-metrics-source]')?.addEventListener('input',e=>{t.state.importSource=e.target.value;});
  root.querySelector('[data-metrics-file]')?.addEventListener('change',async e=>{const file=e.target.files?.[0];if(!file)return;try{if(file.size>1000000)throw new Error('Use a CSV smaller than 1 MB.');const rows=parseMetricsCSV(await file.text());if(!rows.length||rows.length>3000)throw new Error('Import 1–3,000 records.');t.state.pendingImport=rows;t.state.notice='Review the figures before confirming.';}catch(e){t.state.pendingImport=null;t.state.notice=e.message;}rerender();});
  root.querySelector('[data-metrics-confirm]')?.addEventListener('click',async()=>{const p=t.importMetrics();rerender();await p;rerender();});
  root.querySelector('[data-draft-comms]')?.addEventListener('click',()=>document.getElementById('draft-comms')?.scrollIntoView({behavior:'smooth',block:'start'}));
  root.querySelectorAll('[data-desk-select]').forEach(b=>b.addEventListener('click',()=>{ui.selected=b.dataset.deskSelect;rerender();}));
  root.querySelectorAll('[data-desk-star]').forEach(b=>b.addEventListener('click',()=>{const id=b.dataset.deskStar,p=pick(id);if(!p||drafted(p))return;ui.queue=ui.queue.includes(id)?ui.queue.filter(x=>x!==id):[...ui.queue,id];persist();rerender();}));
  root.querySelectorAll('[data-desk-move]').forEach(b=>b.addEventListener('click',()=>{const rows=availableQueue().map(p=>String(p.id)),i=rows.indexOf(b.dataset.deskMove),j=i+Number(b.dataset.direction);if(i<0||j<0||j>=rows.length)return;[rows[i],rows[j]]=[rows[j],rows[i]];ui.queue=rows;persist();rerender();}));
  root.querySelector('[data-desk-search]')?.addEventListener('input',e=>{ui.search=e.target.value;rerender();});
  root.querySelector('[data-desk-position]')?.addEventListener('change',e=>{ui.position=e.target.value;rerender();});
  root.querySelector('[data-desk-drafted]')?.addEventListener('change',e=>{ui.showDrafted=e.target.checked;rerender();});
 }
 function capture(root){
  const focused=root.querySelector('[data-desk-search]'),hasFocus=focused&&document.activeElement===focused,start=focused?.selectionStart,end=focused?.selectionEnd;
  const scrolls=[...root.querySelectorAll('[data-desk-scroll]')].map(e=>[e.dataset.deskScroll,e.scrollTop,e.scrollLeft]);
  const details=[...root.querySelectorAll('.desk-order,.desk-commissioner')].map(e=>[e.className,e.open]);
  const teamOpen=[...root.querySelectorAll('[data-desk-detail]')].filter(e=>e.open).map(e=>e.dataset.deskDetail);
  return ()=>{if(hasFocus){const e=root.querySelector('[data-desk-search]');e?.focus({preventScroll:true});e?.setSelectionRange(start,end);}for(const [key,top,left] of scrolls){const e=root.querySelector(`[data-desk-scroll="${key}"]`);if(e){e.scrollTop=top;e.scrollLeft=left;}}for(const [cls,open]of details){const e=root.querySelector('.'+cls);if(e)e.open=open;}for(const e of root.querySelectorAll('[data-desk-detail]'))e.open=teamOpen.includes(e.dataset.deskDetail);};
 }
 return {view,bind,capture};
}
