import './league.css';
import { supabase, configured } from './supabase.js';
import { ROOM_CODE, LEAGUE_NAME } from './config.js';

const app = document.querySelector('#app');
const STORAGE_KEY = `glsk-auction-session-${ROOM_CODE}`;
const COMMISH_TEAM_NAME = 'Weiss Tea & Lemonade';

const state = {
  room:null, teams:[], season:null, roster:[], contracts:[], rules:[], distro:[], deadlines:[], deadlineStatus:[], finance:[], contractOptions:[],
  session:loadSession(), tab:'home', loading:true, realtime:null,
};

function loadSession(){ try{return JSON.parse(localStorage.getItem(STORAGE_KEY)||'null');}catch{return null;} }
function saveSession(s){state.session=s; if(s)localStorage.setItem(STORAGE_KEY,JSON.stringify(s));else localStorage.removeItem(STORAGE_KEY);}
function esc(v=''){return String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));}
function money(n){return `$${(Number(n||0)/100).toFixed(2)}`;}
function bidMoney(n){return `$${Number(n||0).toFixed(0)}`;}
function teamById(id){return state.teams.find(t=>t.id===id);}
function myTeam(){return state.session?.teamId?teamById(state.session.teamId):null;}
function isCommish(){return Boolean(state.session?.commishPin);}
function rosterFor(id){return state.roster.filter(r=>r.team_id===id&&r.active!==false);}
function contractsFor(id){return state.contracts.filter(c=>c.team_id===id&&c.status==='active');}
function capUsed(id){return contractsFor(id).reduce((s,c)=>s+Number(c.cap_cost||0),0);}
function ruleNum(key,fallback=0){const r=state.rules.find(x=>x.rule_key===key);return r?.numeric_value==null?fallback:Number(r.numeric_value);}
function fmtDate(v){if(!v)return '—'; const d=new Date(v); return new Intl.DateTimeFormat('en-US',{month:'short',day:'numeric',year:'numeric',hour:'numeric',minute:'2-digit',timeZoneName:'short'}).format(d);}
function fmtDateOnly(v){if(!v)return '—'; const [y,m,d]=String(v).split('-'); return `${Number(m)}/${Number(d)}/${y}`;}
function toast(msg,type=''){let w=document.querySelector('.toast-wrap');if(!w){w=document.createElement('div');w.className='toast-wrap';document.body.appendChild(w);}const n=document.createElement('div');n.className=`toast ${type}`;n.textContent=msg;w.appendChild(n);setTimeout(()=>n.remove(),3200);}

async function rpc(name,args={}){const {data,error}=await supabase.rpc(name,args);if(error)throw new Error(error.message);if(data&&data.ok===false)throw new Error(data.error||'Request failed.');return data;}
async function q(table,select='*',eq=[]){let x=supabase.from(table).select(select);for(const [k,v] of eq)x=x.eq(k,v);const {data,error}=await x;if(error)throw error;return data||[];}

async function loadFinance(){
  state.finance=[];
  if(!state.session||state.session.spectator)return;
  try{
    const {data,error}=await supabase.rpc('league_get_finances',{p_room_code:ROOM_CODE,p_team_id:state.session.teamId||null,p_pin:state.session.pin||'',p_commish_pin:state.session.commishPin||null});
    if(error)throw error; state.finance=data||[];
  }catch(e){console.warn('finance load',e.message);}
}

async function loadData(){
  const {data:room,error:re}=await supabase.from('rooms').select('*').eq('code',ROOM_CODE).single(); if(re)throw re; state.room=room;
  const [teams,seasons,roster,contracts,rules,distro,deadlines,statuses,options]=await Promise.all([
    q('teams','*',[['room_id',room.id]]),q('league_seasons','*',[['room_id',room.id]]),q('league_roster_entries','*',[['room_id',room.id]]),
    q('league_contracts','*'),q('league_rule_settings','*'),q('redistribution_rules','*'),q('league_deadlines','*'),q('league_deadline_team_status','*'),q('contract_options','*')
  ]);
  state.teams=teams.sort((a,b)=>a.sort_order-b.sort_order); state.season=seasons.find(s=>s.is_current)||seasons.sort((a,b)=>b.season_year-a.season_year)[0]||null;
  const sid=state.season?.id; state.roster=roster; state.contracts=contracts.filter(x=>x.season_id===sid); state.rules=rules.filter(x=>x.season_id===sid).sort((a,b)=>a.sort_order-b.sort_order);
  state.distro=distro.filter(x=>x.season_id===sid).sort((a,b)=>a.sort_order-b.sort_order); state.deadlines=deadlines.filter(x=>x.season_id===sid).sort((a,b)=>new Date(a.due_at)-new Date(b.due_at));
  state.deadlineStatus=statuses; state.contractOptions=options.filter(x=>x.season_id===sid&&x.active).sort((a,b)=>a.years-b.years); await loadFinance();
}

function topBar(){const t=myTeam();return `<header class="topbar"><div class="topbar-inner"><div class="brand"><div class="brand-kicker">League Office</div><div class="brand-title">${esc(LEAGUE_NAME)}</div></div><div class="user-chip"><span class="status-dot live"></span><div class="user-chip-text"><div class="user-team">${t?`${esc(t.name)}${isCommish()?' • Commish':''}`:state.session?.spectator?'Spectator':'League'}</div><div class="user-budget">${t?`${bidMoney(t.remaining_budget)} bids • ${rosterFor(t.id).length}/${state.season?.roster_limit||18} roster`:`${state.season?.season_year||2026} season`}</div></div><button class="btn-link" data-action="leave" style="color:#cbd4e3">Leave</button></div></div></header>`;}
function bottomNav(){const items=[['home','⌂','Home'],['teams','♟','Teams'],['contracts','▤','Contracts'],['rules','⚙','Rules'],['deadlines','◷','Deadlines'],['finances','$','Finances']];return `<nav class="bottom-nav office-bottom-nav"><div class="bottom-nav-inner">${items.map(([t,i,l])=>`<button class="nav-btn ${state.tab===t?'active':''}" data-tab="${t}"><span>${i}</span>${l}</button>`).join('')}</div></nav>`;}

function dashboard(){
 const rosterLimit=state.season?.roster_limit||18,full=state.teams.filter(t=>rosterFor(t.id).length>=rosterLimit).length,totalBids=state.teams.reduce((s,t)=>s+Number(t.remaining_budget||0),0),open=state.deadlines.filter(d=>d.status==='open').length;
 const next=state.deadlines.find(d=>d.status==='open'&&new Date(d.due_at)>new Date());
 return `<section class="office-hero"><div class="office-kicker">${state.season?.season_year||2026} League Year</div><h1>Great Lake State Keepers</h1><p>Rosters, contracts, bid dollars, rules, deadlines and league operations in one place.</p></section>
 <div class="kpi-grid"><div class="card kpi"><div class="kpi-label">Teams Full</div><div class="kpi-value">${full}/12</div><div class="kpi-sub">${rosterLimit}-player limit</div></div><div class="card kpi"><div class="kpi-label">Bid Dollars</div><div class="kpi-value">${totalBids}</div><div class="kpi-sub">remaining league-wide</div></div><div class="card kpi"><div class="kpi-label">Contracts</div><div class="kpi-value">${state.contracts.filter(c=>c.status==='active').length}</div><div class="kpi-sub">active</div></div><div class="card kpi"><div class="kpi-label">Deadlines</div><div class="kpi-value">${open}</div><div class="kpi-sub">currently open</div></div></div>
 ${next?`<div class="owner-banner"><strong>Next deadline:</strong> ${esc(next.title)} • ${fmtDate(next.due_at)}</div>`:''}
 <div class="office-grid two"><div><div class="office-section"><div class="office-section-head"><h2>League Snapshot</h2><button class="btn btn-sm btn-outline" data-tab="teams">All Teams</button></div>${teamCards()}</div></div><div><div class="office-section"><div class="office-section-head"><h2>Draft Rooms</h2></div><div class="draft-links"><a class="draft-link" href="/"><strong>⚡</strong>Auction</a><a class="draft-link" href="/supplemental"><strong>↔</strong>Supplemental</a><a class="draft-link" href="/phase3"><strong>⇅</strong>Roster Fill</a></div></div><div class="office-section"><div class="office-section-head"><h2>Commissioner Tools</h2></div><div class="card card-pad"><div class="small muted">${isCommish()?'You have commissioner access. Rules, contracts, deadlines and finance controls are unlocked.':'Commissioner controls are only available to Weiss Tea & Lemonade.'}</div></div></div></div></div>`;
}
function teamCards(){const lim=state.season?.roster_limit||18,cap=state.season?.salary_cap_points||100;return `<div class="team-office-grid">${state.teams.map(t=>`<div class="card office-team-card"><div class="office-team-name">${esc(t.name)}</div><div class="cap-badge">${capUsed(t.id)}/${cap} pts</div><div class="office-team-metrics"><div class="office-mini"><span>Roster</span><strong>${rosterFor(t.id).length}/${lim}</strong></div><div class="office-mini"><span>Bids</span><strong>${bidMoney(t.remaining_budget)}</strong></div><div class="office-mini"><span>Contracts</span><strong>${contractsFor(t.id).length}</strong></div></div></div>`).join('')}</div>`;}
function teamsView(){const lim=state.season?.roster_limit||18,cap=state.season?.salary_cap_points||100;return `<div class="office-section-head"><h2>Teams & Rosters</h2><div class="small muted">Live from the shared league roster</div></div><div class="team-office-grid">${state.teams.map(t=>{const roster=rosterFor(t.id).slice().sort((a,b)=>(a.position||'').localeCompare(b.position||'')||a.player_name.localeCompare(b.player_name));return `<details class="card office-team-card"><summary style="cursor:pointer;list-style:none"><div class="row between gap-8"><div class="office-team-name">${esc(t.name)}</div><div><strong>${roster.length}/${lim}</strong> • ${bidMoney(t.remaining_budget)} • ${capUsed(t.id)}/${cap} pts</div></div></summary><div style="grid-column:1/-1;margin-top:8px">${roster.map(r=>`<div class="contract-row"><div><div class="contract-player">${esc(r.player_name)}</div><div class="contract-sub">${esc(r.position||'')} • ${esc(r.nfl_team||'')} • ${esc(r.acquisition_type||'roster')}</div></div>${state.contracts.some(c=>c.team_id===t.id&&c.player_key===r.player_key&&c.status==='active')?'<span class="tag tag-next">CONTRACT</span>':''}</div>`).join('')||'<div class="empty-tight">No roster entries.</div>'}</div></details>`;}).join('')}</div>`;}

function contractsView(){const cap=state.season?.salary_cap_points||100;const body=state.teams.map(t=>{const rows=contractsFor(t.id).sort((a,b)=>a.end_year-b.end_year||a.player_name.localeCompare(b.player_name));return `<section class="contract-team"><div class="contract-team-head"><div class="contract-team-name">${esc(t.name)}</div><strong>${capUsed(t.id)}/${cap} pts</strong></div><div class="contract-list">${rows.length?rows.map(c=>`<div class="contract-row"><div><div class="contract-player">${esc(c.player_name)}</div><div class="contract-sub">${c.length_years} yr • ${c.start_year}–${c.end_year} • ${c.cap_cost} pts</div></div><div>${isCommish()?`<button class="btn btn-sm btn-reset" data-void-contract="${c.id}">Void</button>`:`<span class="cap-badge">${c.cap_cost}</span>`}</div></div>`).join(''):'<div class="empty-tight">No active contracts.</div>'}</div></section>`;}).join('');
 return `<div class="office-section-head"><h2>Contracts & Salary Cap</h2><div class="small muted">${state.contractOptions.map(o=>`${o.years}yr = ${o.cap_cost}pts`).join(' • ')}</div></div>${isCommish()?contractForm():''}${body}`;}
function contractForm(){return `<section class="card office-form office-section"><div class="section-title">Commissioner • Add / Update Contract</div><div class="form-grid"><div class="field"><label>Team</label><select id="contract-team" class="input">${state.teams.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></div><div class="field"><label>Player</label><input id="contract-player" class="input" list="roster-player-list" placeholder="Player name"><datalist id="roster-player-list">${state.roster.map(r=>`<option value="${esc(r.player_name)}"></option>`).join('')}</datalist></div><div class="field"><label>Length</label><select id="contract-years" class="input">${state.contractOptions.map(o=>`<option value="${o.years}">${o.years} years • ${o.cap_cost} pts</option>`).join('')}</select></div><div class="field"><label>Start year</label><input id="contract-start" type="number" class="input" value="${state.season?.season_year||2026}"></div></div><button class="btn btn-primary" data-action="save-contract">Save Contract</button></section>`;}

function rulesView(){const groups=[...new Set(state.rules.map(r=>r.category))];const total=state.distro.reduce((s,r)=>s+Number(r.percentage||0),0);return `<div class="office-section-head"><h2>League Rules</h2><div class="small muted">Season-versioned settings</div></div><div class="office-grid two"><div><section class="card card-pad">${groups.map(g=>`<div class="rule-category"><h3>${esc(g)}</h3>${state.rules.filter(r=>r.category===g).map(r=>`<div class="rule-row"><div class="rule-label">${esc(r.label)}${r.unit?` <span class="small muted">(${esc(r.unit)})</span>`:''}</div><div>${r.numeric_value!=null?(isCommish()?`<input class="rule-input" data-rule-key="${esc(r.rule_key)}" type="number" step="1" value="${Number(r.numeric_value)}">`:`<div class="rule-value">${Number(r.numeric_value)} ${esc(r.unit||'')}</div>`):`<div class="rule-value">${r.boolean_value?'On':'Off'}</div>`}</div></div>`).join('')}</div>`).join('')}${isCommish()?'<button class="btn btn-primary" data-action="save-rules">Save Rule Defaults</button>':''}</section></div><div><section class="card card-pad"><div class="office-section-head"><h2>Bid Redistribution</h2><div id="distro-total" class="${Math.abs(total-100)>.001?'distro-total bad':'distro-total'}">${total.toFixed(2)}%</div></div><div class="redistribution-grid">${state.distro.map(r=>`<div class="distro-row"><div class="rule-label">${esc(r.label)}</div>${isCommish()?`<input class="rule-input distro-input" data-bracket="${r.bracket}" data-finish="${r.finish}" type="number" step="0.05" min="0" max="100" value="${Number(r.percentage).toFixed(2)}">`:`<div class="rule-value">${Number(r.percentage).toFixed(2)}%</div>`}</div>`).join('')}</div><div class="distro-total"><span>Total</span><strong id="distro-total-bottom">${total.toFixed(2)}%</strong></div>${isCommish()?'<button class="btn btn-primary btn-block" style="margin-top:10px" data-action="save-distro">Save Redistribution</button>':''}<div class="small muted" style="margin-top:9px">The 2026 values were imported from the league workbook. Future seasons can use different versions without rewriting history.</div></section></div></div>`;}

function deadlinesView(){const mine=myTeam();return `<div class="office-section-head"><h2>Deadlines</h2><div class="small muted">Auto-lock + timestamped submissions</div></div>${isCommish()?deadlineForm():''}<div class="list-stack">${state.deadlines.length?state.deadlines.map(d=>{const sts=state.deadlineStatus.filter(s=>s.deadline_id===d.id),done=sts.filter(s=>['submitted','late','waived'].includes(s.status)).length,my=mine?sts.find(s=>s.team_id===mine.id):null,pct=state.teams.length?done/state.teams.length*100:0;return `<div class="card deadline-card"><div class="row between gap-8"><div><div class="deadline-title">${esc(d.title)}</div><div class="deadline-meta">${esc(d.deadline_type)} • ${fmtDate(d.due_at)}${d.auto_lock?' • auto-lock':''}</div></div><span class="deadline-status ${d.status}">${esc(d.status)}</span></div>${d.notes?`<div class="small muted" style="margin-top:7px">${esc(d.notes)}</div>`:''}<div class="deadline-progress"><div style="width:${pct}%"></div></div><div class="row between gap-8 wrap" style="margin-top:8px"><div class="small muted">${done}/${state.teams.length} submitted${my?` • Your status: ${esc(my.status)}`:''}</div><div class="inline-actions">${mine&&d.status==='open'&&(!my||my.status==='pending')?`<button class="btn btn-sm btn-green" data-submit-deadline="${d.id}">Mark Submitted</button>`:''}${isCommish()&&d.status==='open'?`<button class="btn btn-sm btn-outline" data-deadline-status="closed" data-deadline-id="${d.id}">Close</button>`:''}${isCommish()&&d.status==='closed'?`<button class="btn btn-sm btn-outline" data-deadline-status="open" data-deadline-id="${d.id}">Reopen</button>`:''}${isCommish()&&d.status!=='completed'?`<button class="btn btn-sm btn-outline" data-deadline-status="completed" data-deadline-id="${d.id}">Complete</button>`:''}</div></div></div>`;}).join(''):'<div class="card empty">No league deadlines have been created yet.</div>'}</div>`;}
function deadlineForm(){return `<section class="card office-form office-section"><div class="section-title">Create Deadline</div><div class="form-grid"><div class="field"><label>Title</label><input id="deadline-title" class="input" placeholder="Contract assignments due"></div><div class="field"><label>Type</label><select id="deadline-type" class="input"><option value="contracts">Contracts</option><option value="rookie_rights">Rookie Rights</option><option value="dues">Dues</option><option value="trade">Trade / Transaction</option><option value="general">General</option></select></div><div class="field"><label>Due date & time</label><input id="deadline-due" type="datetime-local" class="input"></div><div class="field"><label>Automatic lock</label><select id="deadline-lock" class="input"><option value="true">Yes</option><option value="false">No</option></select></div></div><div class="field"><label>Notes</label><textarea id="deadline-notes" class="input" placeholder="Optional instructions"></textarea></div><button class="btn btn-primary" data-action="create-deadline">Create Deadline</button></section>`;}

function financesView(){const sumDue=state.finance.filter(x=>x.status==='due').reduce((s,x)=>s+Number(x.amount_cents||0),0),sumPaid=state.finance.filter(x=>x.status==='paid').reduce((s,x)=>s+Number(x.amount_cents||0),0);return `<div class="office-section-head"><h2>League Finances</h2><div class="small muted">PIN-validated private ledger</div></div><div class="kpi-grid"><div class="card kpi"><div class="kpi-label">Due</div><div class="kpi-value">${money(sumDue)}</div></div><div class="card kpi"><div class="kpi-label">Paid</div><div class="kpi-value">${money(sumPaid)}</div></div></div>${isCommish()?financeForm():''}<div class="list-stack">${state.finance.length?state.finance.map(f=>{const t=teamById(f.team_id);return `<div class="finance-row"><div><div class="log-name">${esc(f.description)}</div><div class="small muted">${esc(t?.name||'League')} • ${esc(f.category)}${f.due_at?` • due ${fmtDateOnly(f.due_at)}`:''}</div><div class="finance-status">${esc(f.status)}</div></div><div style="text-align:right"><div class="finance-amount ${Number(f.amount_cents)<0?'negative':''}">${money(f.amount_cents)}</div>${isCommish()?`<div class="inline-actions" style="justify-content:flex-end;margin-top:5px">${f.status!=='paid'?`<button class="btn btn-sm btn-green" data-finance-status="paid" data-finance-id="${f.id}">Paid</button>`:''}${f.status!=='waived'?`<button class="btn btn-sm btn-outline" data-finance-status="waived" data-finance-id="${f.id}">Waive</button>`:''}</div>`:''}</div></div>`;}).join(''):'<div class="card empty">No finance entries yet.</div>'}</div><div class="notice" style="margin-top:12px">Financial rows are not publicly readable from Supabase; owners can retrieve only their own items with their team PIN, while the commissioner can retrieve the full ledger.</div>`;}
function financeForm(){return `<section class="card office-form office-section"><div class="section-title">Commissioner • Add Finance Entry</div><div class="form-grid"><div class="field"><label>Team</label><select id="finance-team" class="input"><option value="">League-wide</option>${state.teams.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('')}</select></div><div class="field"><label>Category</label><select id="finance-category" class="input"><option value="dues">Dues</option><option value="prize">Prize</option><option value="expense">Expense</option><option value="adjustment">Adjustment</option><option value="other">Other</option></select></div><div class="field"><label>Amount ($)</label><input id="finance-amount" type="number" step="0.01" class="input" placeholder="100.00"></div><div class="field"><label>Due date</label><input id="finance-due" type="date" class="input"></div></div><div class="field"><label>Description</label><input id="finance-desc" class="input" placeholder="2026 league dues"></div><button class="btn btn-primary" data-action="add-finance">Add Entry</button></section>`;}

function loginView(){const options=state.teams.map(t=>`<option value="${t.id}">${esc(t.name)}</option>`).join('');return `<div class="login-wrap"><div class="login-card"><div class="login-head"><h1>${esc(LEAGUE_NAME)}</h1><p>League Office</p></div><div class="login-body"><div class="field"><label>Your team</label><select id="join-team" class="input"><option value="">Select your team…</option>${options}</select></div><div class="field"><label>Team PIN</label><input id="team-pin" class="input pin-input" inputmode="numeric" maxlength="6" placeholder="6-digit PIN"></div><div id="join-error"></div><button class="btn btn-primary btn-block" data-action="join">Enter League Office</button><button class="btn-link btn-block" data-action="spectate">View public league dashboard</button><a class="btn-link btn-block" href="/" style="display:block;text-align:center;text-decoration:none">← Auction Room</a></div></div></div>`;}
function setupError(){return `<div class="login-wrap"><div class="login-card"><div class="login-head"><h1>League Office Ready</h1><p>Database connection is missing.</p></div></div></div>`;}
function render(){if(!configured){app.innerHTML=setupError();return;}if(state.loading){app.innerHTML='<div class="login-wrap"><div style="color:white;font-weight:900">Loading League Office…</div></div>';return;}if(!state.session){app.innerHTML=loginView();bind();return;}let content=state.tab==='teams'?teamsView():state.tab==='contracts'?contractsView():state.tab==='rules'?rulesView():state.tab==='deadlines'?deadlinesView():state.tab==='finances'?financesView():dashboard();app.innerHTML=`<div class="office-shell">${topBar()}<main class="main">${content}</main>${bottomNav()}</div>`;bind();}

async function join(){const teamId=document.querySelector('#join-team')?.value,pin=document.querySelector('#team-pin')?.value.trim(),err=document.querySelector('#join-error');if(!teamId||!pin){err.innerHTML='<div class="error">Select your team and enter its PIN.</div>';return;}try{await rpc('join_room',{p_room_code:ROOM_CODE,p_team_id:teamId,p_pin:pin});const t=state.teams.find(x=>x.id===teamId);let commishPin=null;if(t?.name===COMMISH_TEAM_NAME){const valid=await rpc('commish_login',{p_room_code:ROOM_CODE,p_pin:pin});if(!valid?.valid)throw new Error('Commissioner access is not configured.');commishPin=pin;}saveSession({teamId,pin,commishPin,spectator:false});await loadFinance();render();}catch(e){err.innerHTML=`<div class="error">${esc(e.message)}</div>`;}}
function logout(){saveSession(null);render();}
async function commish(name,args={},msg='Saved.'){try{await rpc(name,{p_room_code:ROOM_CODE,p_commish_pin:state.session.commishPin,...args});toast(msg);await loadData();render();}catch(e){toast(e.message,'error');}}

function bind(){
 app.querySelectorAll('[data-tab]').forEach(b=>b.addEventListener('click',()=>{state.tab=b.dataset.tab;render();}));
 app.querySelector('[data-action="join"]')?.addEventListener('click',join); app.querySelector('[data-action="spectate"]')?.addEventListener('click',()=>{saveSession({spectator:true,teamId:null,pin:null,commishPin:null});render();}); app.querySelector('[data-action="leave"]')?.addEventListener('click',logout);
 app.querySelector('[data-action="save-rules"]')?.addEventListener('click',()=>{const updates=[...document.querySelectorAll('[data-rule-key]')].map(i=>({key:i.dataset.ruleKey,value:Number(i.value)}));commish('league_commish_set_rules',{p_updates:updates},'League rule defaults updated.');});
 const updateTotal=()=>{const t=[...document.querySelectorAll('.distro-input')].reduce((s,i)=>s+Number(i.value||0),0);for(const id of ['distro-total','distro-total-bottom']){const el=document.getElementById(id);if(el){el.textContent=`${t.toFixed(2)}%`;el.classList.toggle('bad',Math.abs(t-100)>.001);}}}; document.querySelectorAll('.distro-input').forEach(i=>i.addEventListener('input',updateTotal));
 app.querySelector('[data-action="save-distro"]')?.addEventListener('click',()=>{const rows=[...document.querySelectorAll('.distro-input')].map(i=>({bracket:i.dataset.bracket,finish:Number(i.dataset.finish),percentage:Number(i.value)}));commish('league_commish_save_redistribution',{p_rows:rows},'Redistribution saved.');});
 app.querySelector('[data-action="save-contract"]')?.addEventListener('click',()=>{const p_team_id=document.getElementById('contract-team').value,p_player_name=document.getElementById('contract-player').value.trim(),p_length_years=Number(document.getElementById('contract-years').value),p_start_year=Number(document.getElementById('contract-start').value);if(!p_player_name)return toast('Enter a player name.','error');commish('league_commish_upsert_contract',{p_team_id,p_player_name,p_length_years,p_start_year},'Contract saved.');});
 document.querySelectorAll('[data-void-contract]').forEach(b=>b.addEventListener('click',()=>{if(confirm('Void this contract?'))commish('league_commish_void_contract',{p_contract_id:Number(b.dataset.voidContract)},'Contract voided.');}));
 app.querySelector('[data-action="create-deadline"]')?.addEventListener('click',()=>{const title=document.getElementById('deadline-title').value.trim(),due=document.getElementById('deadline-due').value;if(!title||!due)return toast('Title and due date/time are required.','error');commish('league_commish_create_deadline',{p_title:title,p_deadline_type:document.getElementById('deadline-type').value,p_due_at:new Date(due).toISOString(),p_auto_lock:document.getElementById('deadline-lock').value==='true',p_notes:document.getElementById('deadline-notes').value},'Deadline created.');});
 document.querySelectorAll('[data-submit-deadline]').forEach(b=>b.addEventListener('click',async()=>{try{await rpc('league_mark_deadline_submitted',{p_room_code:ROOM_CODE,p_team_id:state.session.teamId,p_pin:state.session.pin,p_deadline_id:b.dataset.submitDeadline});toast('Submission recorded.');await loadData();render();}catch(e){toast(e.message,'error');}}));
 document.querySelectorAll('[data-deadline-status]').forEach(b=>b.addEventListener('click',()=>commish('league_commish_set_deadline_status',{p_deadline_id:b.dataset.deadlineId,p_status:b.dataset.deadlineStatus},'Deadline updated.')));
 app.querySelector('[data-action="add-finance"]')?.addEventListener('click',()=>{const amt=Math.round(Number(document.getElementById('finance-amount').value||0)*100),desc=document.getElementById('finance-desc').value.trim();if(!desc||!Number.isFinite(amt))return toast('Enter description and amount.','error');commish('league_commish_add_finance_item',{p_team_id:document.getElementById('finance-team').value||null,p_category:document.getElementById('finance-category').value,p_description:desc,p_amount_cents:amt,p_due_at:document.getElementById('finance-due').value||null,p_status:'due'},'Finance entry added.');});
 document.querySelectorAll('[data-finance-status]').forEach(b=>b.addEventListener('click',()=>commish('league_commish_set_finance_status',{p_finance_id:b.dataset.financeId,p_status:b.dataset.financeStatus},'Finance status updated.')));
}

async function subscribe(){if(state.realtime)await supabase.removeChannel(state.realtime);state.realtime=supabase.channel(`league-office-${ROOM_CODE}`).on('postgres_changes',{event:'*',schema:'public',table:'league_roster_entries'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'teams'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'league_contracts'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'league_rule_settings'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'redistribution_rules'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'league_deadlines'},refresh).on('postgres_changes',{event:'*',schema:'public',table:'league_deadline_team_status'},refresh).subscribe();}
let refreshTimer=null;function refresh(){clearTimeout(refreshTimer);refreshTimer=setTimeout(async()=>{try{await loadData();render();}catch(e){console.warn(e);}},180);}

async function init(){if(!configured){state.loading=false;render();return;}try{await loadData();state.loading=false;render();await subscribe();}catch(e){state.loading=false;app.innerHTML=`<div class="login-wrap"><div class="login-card"><div class="login-head"><h1>League Office</h1><p>Database migration required.</p></div><div class="login-body"><div class="error">${esc(e.message)}</div><p class="small muted">Run the League Office v1 Supabase migration, then refresh.</p></div></div></div>`;}}
init();
